using CSharpToJava.Core.Context;

namespace CSharpToJava.Core.Pipeline;

/// <summary>
/// Generates compatibility helper classes (Holder types, MSTest stubs,
/// XML/JSON wrappers, utility classes, regex/trace compatibility).
/// Extracted from ProjectConversionPipeline for maintainability.
/// </summary>
public static class CompatibilityClassGenerator
{
    internal const string MSTestCompatibilityPackage = "Microsoft.VisualStudio.TestTools.UnitTesting";

    public static List<ConversionResult> GenerateCompatibilitySupport(string compatibilityPackage, bool includeTestContext)
    {
        var results = new List<ConversionResult>();
        results.AddRange(GenerateHolderClasses(compatibilityPackage));
        results.AddRange(GenerateMSTestCompatibilityClasses(includeTestContext));
        results.AddRange(GenerateXmlWrappers(compatibilityPackage));
        results.AddRange(GenerateJsonWrappers(compatibilityPackage));
        results.AddRange(GenerateUtilityClasses(compatibilityPackage));
        results.AddRange(GenerateRegexCompatibilityClasses(compatibilityPackage));
        results.AddRange(GenerateTraceCompatibilityClasses(compatibilityPackage));
        return results;
    }

    /// <summary>
    /// Determines the base package by examining the most common package prefix in results.
    /// </summary>
    internal static string DetermineBasePackage(List<ConversionResult> results)
    {
        var packages = results
            .Where(r => !string.IsNullOrEmpty(r.Package))
            .Select(r => r.Package!)
            .GroupBy(p => p)
            .OrderByDescending(g => g.Count())
            .FirstOrDefault();

        if (packages != null)
        {
            var pkg = packages.Key;
            // Take only the first 2 root segments to form a stable base package for holder classes
            // (e.g. "Microsoft.Msagl.Core.Geometry" -> "Microsoft.Msagl")
            var parts = pkg.Split('.');
            return string.Join(".", parts.Take(Math.Min(parts.Length, 2)));
        }

        return "com.generated";
    }

    /// <summary>
    /// Generates Holder class files for ref/out parameter support.
    /// These are emitted unconditionally so all converted code can import them.
    /// </summary>
    internal static List<ConversionResult> GenerateHolderClasses(string basePackage)
    {
        var holders = new (string name, string type, string defaultValue)[]
        {
            ("IntHolder", "int", "0"),
            ("LongHolder", "long", "0L"),
            ("DoubleHolder", "double", "0.0"),
            ("FloatHolder", "float", "0.0f"),
            ("BoolHolder", "boolean", "false"),
            ("CharHolder", "char", "'\\0'"),
            ("ShortHolder", "short", "(short)0"),
            ("ByteHolder", "byte", "(byte)0"),
        };

        var results = new List<ConversionResult>();

        foreach (var (name, type, defaultValue) in holders)
        {
            var code = $@"package {basePackage};

/** Holder for ref/out {type} parameters (generated by CSharpToJava converter). */
public final class {name} {{
    public {type} value;
    public {name}() {{ this.value = {defaultValue}; }}
    public {name}({type} value) {{ this.value = value; }}
}}
";
            results.Add(new ConversionResult
            {
                Success = true,
                GeneratedCode = code,
                FileName = $"{name}.java",
                Package = basePackage,
                Diagnostics = new List<Context.DiagnosticMessage>()
            });
        }

        // Generic ObjectHolder<T>
        var objectHolderCode = $@"package {basePackage};

/** Holder for ref/out object parameters (generated by CSharpToJava converter). */
public final class ObjectHolder<T> {{
    public T value;
    public ObjectHolder() {{ this.value = null; }}
    public ObjectHolder(T value) {{ this.value = value; }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = objectHolderCode,
            FileName = "ObjectHolder.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // StopwatchHelper (replaces System.Diagnostics.Stopwatch)
        var stopwatchCode = $@"package {basePackage};

/** Stopwatch helper class (generated by CSharpToJava converter, replacing System.Diagnostics.Stopwatch). */
public final class StopwatchHelper {{
    private long startNanos;
    private long elapsedNanos;
    private boolean running;

    public StopwatchHelper() {{}}

    public static StopwatchHelper startNew() {{
        StopwatchHelper sw = new StopwatchHelper();
        sw.start();
        return sw;
    }}

    public void start() {{
        if (!running) {{
            startNanos = System.nanoTime();
            running = true;
        }}
    }}

    public void stop() {{
        if (running) {{
            elapsedNanos += System.nanoTime() - startNanos;
            running = false;
        }}
    }}

    public void reset() {{
        elapsedNanos = 0;
        running = false;
    }}

    public void restart() {{
        reset();
        start();
    }}

    public long getElapsedMilliseconds() {{
        long elapsed = elapsedNanos;
        if (running) elapsed += System.nanoTime() - startNanos;
        return elapsed / 1_000_000L;
    }}

    public boolean isRunning() {{ return running; }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = stopwatchCode,
            FileName = "StopwatchHelper.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        return results;
    }

    internal static bool RequiresTestContext(List<ConversionResult> results)
    {
        return results.Any(r =>
            (!string.IsNullOrEmpty(r.GeneratedCode) &&
             (r.GeneratedCode.Contains("Microsoft.VisualStudio.TestTools.UnitTesting", StringComparison.Ordinal)
              || r.GeneratedCode.Contains("TestContext", StringComparison.Ordinal)))
            || string.Equals(r.FileName, "TestContext.java", StringComparison.Ordinal));
    }

    internal static List<ConversionResult> GenerateMSTestCompatibilityClasses(bool includeTestContext)
    {
        if (!includeTestContext)
        {
            return new List<ConversionResult>();
        }

        const string packageName = MSTestCompatibilityPackage;
        var testContextCode = $@"package {packageName};

public class TestContext {{
    public static final String TestDir = System.getProperty(""user.dir"");
    public static final String DeploymentDirectory = System.getProperty(""user.dir"");
    public static final String TestRunDirectory = System.getProperty(""user.dir"");

    public static void writeLine(String line) {{
        System.out.println(line);
    }}

    public static void writeLine(String format, Object... args) {{
        System.out.println(String.format(format, args));
    }}
}}
";

        var assertCode = $@"package {packageName};

import java.util.Objects;

public final class Assert {{
    private Assert() {{}}

    public static void areSame(Object expected, Object actual, String message) {{
        if (expected != actual) {{
            fail(format(message, ""Expected references to be identical.""));
        }}
    }}

    public static void areEqual(Object expected, Object actual, String message) {{
        if (!Objects.equals(expected, actual)) {{
            fail(format(message, ""Expected <"" + expected + ""> but was <"" + actual + "">.""));
        }}
    }}

    public static void isTrue(boolean condition, String message) {{
        if (!condition) {{
            fail(format(message, ""Expected condition to be true.""));
        }}
    }}

    public static void isFalse(boolean condition, String message) {{
        if (condition) {{
            fail(format(message, ""Expected condition to be false.""));
        }}
    }}

    public static void isNotNull(Object value, String message) {{
        if (value == null) {{
            fail(format(message, ""Expected value to be non-null.""));
        }}
    }}

    public static void fail(String message) {{
        throw new AssertionError(message == null ? ""Assertion failed."" : message);
    }}

    private static String format(String message, String fallback) {{
        return message == null || message.isEmpty() ? fallback : message;
    }}
}}
";

        var collectionAssertCode = $@"package {packageName};

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public final class CollectionAssert {{
    private CollectionAssert() {{}}

    public static void areEqual(Iterable<?> expected, Iterable<?> actual) {{
        areEqual(expected, actual, null);
    }}

    public static void areEqual(Iterable<?> expected, Iterable<?> actual, String message) {{
        var expectedList = toList(expected);
        var actualList = toList(actual);
        if (!Objects.equals(expectedList, actualList)) {{
            throw new AssertionError(message == null || message.isEmpty()
                ? ""Expected collections to be equal.""
                : message);
        }}
    }}

    private static List<Object> toList(Iterable<?> source) {{
        ArrayList<Object> values = new ArrayList<>();
        for (Object item : source) {{
            values.add(item);
        }}
        return values;
    }}
}}
";

        return new List<ConversionResult>
        {
            new()
            {
                Success = true,
                GeneratedCode = testContextCode,
                FileName = "TestContext.java",
                Package = packageName,
                Diagnostics = new List<Context.DiagnosticMessage>()
            },
            new()
            {
                Success = true,
                GeneratedCode = assertCode,
                FileName = "Assert.java",
                Package = packageName,
                Diagnostics = new List<Context.DiagnosticMessage>()
            },
            new()
            {
                Success = true,
                GeneratedCode = collectionAssertCode,
                FileName = "CollectionAssert.java",
                Package = packageName,
                Diagnostics = new List<Context.DiagnosticMessage>()
            }
        };
    }

    internal static List<ConversionResult> GenerateRegexCompatibilityClasses(string basePackage)
    {
        var results = new List<ConversionResult>();

        var regexOptionsCode = $@"package {basePackage};

public final class RegexOptions {{
    public static final int None = 0;
    public static final int Compiled = 1;
    public static final int CultureInvariant = 2;
    public static final int IgnoreCase = 4;

    private RegexOptions() {{}}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = regexOptionsCode,
            FileName = "RegexOptions.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        var groupCode = $@"package {basePackage};

public final class Group {{
    public static final Group Empty = new Group("""");

    public final String Value;
    public final int Length;

    public Group(String value) {{
        this.Value = value == null ? """" : value;
        this.Length = this.Value.length();
    }}

    @Override
    public String toString() {{
        return Value;
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = groupCode,
            FileName = "Group.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        var groupCollectionCode = $@"package {basePackage};

import java.util.regex.Matcher;

public final class GroupCollection {{
    private final Matcher matcher;
    private final boolean success;

    public GroupCollection(Matcher matcher, boolean success) {{
        this.matcher = matcher;
        this.success = success;
    }}

    public Group get(String name) {{
        if (!success || matcher == null) return Group.Empty;
        try {{ return new Group(matcher.group(name)); }}
        catch (Exception ex) {{ return Group.Empty; }}
    }}

    public Group get(int index) {{
        if (!success || matcher == null) return Group.Empty;
        try {{ return new Group(matcher.group(index)); }}
        catch (Exception ex) {{ return Group.Empty; }}
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = groupCollectionCode,
            FileName = "GroupCollection.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        var matchCode = $@"package {basePackage};

import java.util.regex.Matcher;

public final class Match {{
    public static final Match Empty = new Match(null, false);

    public final boolean Success;
    public final GroupCollection Groups;

    public Match(Matcher matcher, boolean success) {{
        this.Success = success;
        this.Groups = new GroupCollection(matcher, success);
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = matchCode,
            FileName = "Match.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        var regexCode = $@"package {basePackage};

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class Regex {{
    private final Pattern pattern;

    public Regex(String pattern) {{
        this(pattern, RegexOptions.None);
    }}

    public Regex(String pattern, int options) {{
        this.pattern = Pattern.compile(pattern, toJavaFlags(options));
    }}

    public Match match(String input) {{
        Matcher matcher = pattern.matcher(input == null ? """" : input);
        return matcher.find() ? new Match(matcher, true) : Match.Empty;
    }}

    public boolean isMatch(String input) {{
        return pattern.matcher(input == null ? """" : input).find();
    }}

    public static Match match(String input, String pattern) {{
        return new Regex(pattern).match(input);
    }}

    public static boolean isMatch(String input, String pattern) {{
        return new Regex(pattern).isMatch(input);
    }}

    public static String[] split(String input, String pattern) {{
        return Pattern.compile(pattern).split(input == null ? """" : input);
    }}

    private static int toJavaFlags(int options) {{
        int flags = 0;
        if ((options & RegexOptions.IgnoreCase) != 0) {{
            flags |= Pattern.CASE_INSENSITIVE;
        }}
        return flags;
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = regexCode,
            FileName = "Regex.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        return results;
    }

    internal static List<ConversionResult> GenerateTraceCompatibilityClasses(string basePackage)
    {
        var results = new List<ConversionResult>();

        var defaultTraceListenerCode = $@"package {basePackage};

public class DefaultTraceListener {{
    public void fail(String message) {{
        throw new AssertionError(message);
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = defaultTraceListenerCode,
            FileName = "DefaultTraceListener.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        var traceCode = $@"package {basePackage};

import java.util.ArrayList;
import java.util.List;

public final class Trace {{
    public static final ListenerCollection Listeners = new ListenerCollection();

    private Trace() {{}}

    public static final class ListenerCollection extends ArrayList<Object> {{
        public <T> Iterable<T> ofType() {{
            List<T> result = new ArrayList<>();
            for (Object item : this) {{
                @SuppressWarnings(""unchecked"")
                T cast = (T)item;
                result.add(cast);
            }}
            return result;
        }}
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = traceCode,
            FileName = "Trace.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        return results;
    }

    /// <summary>
    /// Generates thin Java wrapper classes for System.Xml.* types, backed by javax.xml.stream (StAX).
    /// These match the Java method names that the converter generates from C# XmlReader/XmlWriter usage.
    /// </summary>
    internal static List<ConversionResult> GenerateXmlWrappers(string basePackage)
    {
        var results = new List<ConversionResult>();

        // ── XmlNodeType ──────────────────────────────────────────────────────────────
        var xmlNodeTypeCode = $@"package {basePackage};

import javax.xml.stream.XMLStreamConstants;

/** Replacement for System.Xml.XmlNodeType (generated by CSharpToJava converter). */
public class XmlNodeType {{
    public static final int None            = 0;
    public static final int Element         = XMLStreamConstants.START_ELEMENT;
    public static final int Attribute       = 10;
    public static final int Text            = XMLStreamConstants.CHARACTERS;
    public static final int CDATA           = XMLStreamConstants.CDATA;
    public static final int EndElement      = XMLStreamConstants.END_ELEMENT;
    public static final int EndDocument     = XMLStreamConstants.END_DOCUMENT;
    public static final int Comment         = XMLStreamConstants.COMMENT;
    public static final int ProcessingInstruction = XMLStreamConstants.PROCESSING_INSTRUCTION;

    /** Static getter — converter generates XmlNodeType.getNone() for enum-like access. */
    public static int getNone()             {{ return None; }}
    public static int getElement()          {{ return Element; }}
    public static int getAttribute()        {{ return Attribute; }}
    public static int getText()             {{ return Text; }}
    public static int getCDATA()            {{ return CDATA; }}
    public static int getEndElement()       {{ return EndElement; }}
    public static int getEndDocument()      {{ return EndDocument; }}
    public static int getComment()          {{ return Comment; }}
    public static int getProcessingInstruction() {{ return ProcessingInstruction; }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = xmlNodeTypeCode,
            FileName = "XmlNodeType.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── ReadState ─────────────────────────────────────────────────────────────────
        var readStateCode = $@"package {basePackage};

/** Replacement for System.Xml.ReadState (generated by CSharpToJava converter). */
public class ReadState {{
    public static final int Initial     = 0;
    public static final int Interactive = 1;
    public static final int Error       = 2;
    public static final int EndOfFile   = 3;
    public static final int Closed      = 4;

    public static int getInitial()     {{ return Initial; }}
    public static int getInteractive() {{ return Interactive; }}
    public static int getError()       {{ return Error; }}
    public static int getEndOfFile()   {{ return EndOfFile; }}
    public static int getClosed()      {{ return Closed; }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = readStateCode,
            FileName = "ReadState.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── XmlConvert ────────────────────────────────────────────────────────────────
        var xmlConvertCode = $@"package {basePackage};

/** Replacement for System.Xml.XmlConvert (generated by CSharpToJava converter). */
public class XmlConvert {{
    public static String toString(double  value) {{ return Double.toString(value); }}
    public static String toString(float   value) {{ return Float.toString(value); }}
    public static String toString(int     value) {{ return Integer.toString(value); }}
    public static String toString(long    value) {{ return Long.toString(value); }}
    public static String toString(boolean value) {{ return Boolean.toString(value); }}
    public static double  toDouble(String s)     {{ return Double.parseDouble(s); }}
    public static float   toSingle(String s)     {{ return Float.parseFloat(s); }}
    public static int     toInt32(String s)      {{ return Integer.parseInt(s); }}
    public static long    toInt64(String s)      {{ return Long.parseLong(s); }}
    public static boolean toBoolean(String s)    {{ return Boolean.parseBoolean(s); }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = xmlConvertCode,
            FileName = "XmlConvert.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── XmlReaderSettings ─────────────────────────────────────────────────────────
        var xmlReaderSettingsCode = $@"package {basePackage};

/** Replacement for System.Xml.XmlReaderSettings (generated by CSharpToJava converter). */
public class XmlReaderSettings {{
    // Public field aliases used by generated C#-style property access.
    public boolean IgnoreWhitespace = false;
    public boolean IgnoreComments = false;
    public boolean CheckCharacters = true;
    public boolean isIgnoreWhitespace()          {{ return IgnoreWhitespace; }}
    public void    setIgnoreWhitespace(boolean v) {{ IgnoreWhitespace = v; }}
    public boolean isIgnoreComments()           {{ return IgnoreComments; }}
    public void    setIgnoreComments(boolean v) {{ IgnoreComments = v; }}
    public boolean isCheckCharacters()           {{ return CheckCharacters; }}
    public void    setCheckCharacters(boolean v)  {{ CheckCharacters = v; }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = xmlReaderSettingsCode,
            FileName = "XmlReaderSettings.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── XmlWriterSettings ─────────────────────────────────────────────────────────
        var xmlWriterSettingsCode = $@"package {basePackage};

/** Replacement for System.Xml.XmlWriterSettings (generated by CSharpToJava converter). */
public class XmlWriterSettings {{
    // Public field aliases used by generated C#-style property access.
    public String Encoding = ""UTF-8"";
    public boolean Indent = false;
    public String IndentChars = ""  "";
    public boolean OmitXmlDeclaration = false;
    public String  getEncoding()                    {{ return Encoding; }}
    public void    setEncoding(String v)             {{ Encoding = v; }}
    public boolean isIndent()                       {{ return Indent; }}
    public void    setIndent(boolean v)              {{ Indent = v; }}
    public String  getIndentChars()                 {{ return IndentChars; }}
    public void    setIndentChars(String v)          {{ IndentChars = v; }}
    public boolean isOmitXmlDeclaration()           {{ return OmitXmlDeclaration; }}
    public void    setOmitXmlDeclaration(boolean v)  {{ OmitXmlDeclaration = v; }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = xmlWriterSettingsCode,
            FileName = "XmlWriterSettings.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── XmlReader ─────────────────────────────────────────────────────────────────
        var xmlReaderCode = $@"package {basePackage};

import java.io.InputStream;
import java.io.Reader;
import javax.xml.stream.*;
import javax.xml.stream.util.StreamReaderDelegate;

/** Replacement for System.Xml.XmlReader backed by StAX (generated by CSharpToJava converter). */
public class XmlReader implements AutoCloseable {{
    protected static XMLStreamReader reader;
    /** -1 = on element, 0+ = on attribute at given index (simulates MoveToFirstAttribute navigation) */
    private static int attributeIndex = -1;
    // C#-style static property aliases frequently emitted by the converter.
    public static int NodeType = XmlNodeType.getNone();
    public static boolean IsEmptyElement = false;
    public static String Name = """";
    public static String Value = """";
    public static int ReadState = 0;

    protected XmlReader() {{}}

    protected XmlReader(XMLStreamReader reader) {{
        XmlReader.reader = reader;
    }}

    /** Whitespace-skipping StAX delegate with look-ahead empty-element detection.
     *  Mimics C# XmlReaderSettings.IgnoreWhitespace = true and C# XmlReader.IsEmptyElement.
     *  After returning a START_ELEMENT, peeks ahead: if the next meaningful event is END_ELEMENT,
     *  the element is empty — the END is consumed internally and isEmptyElement is set to true.
     *  Saved START_ELEMENT state (name, attributes) is returned via overridden accessors. */
    private static final class WhitespaceFilteringReader extends StreamReaderDelegate {{
        /** true if the current START_ELEMENT is an empty/self-closing element (its END_ELEMENT was consumed) */
        boolean isEmptyElement = false;
        // Saved START_ELEMENT state (because look-ahead moves the underlying reader)
        private boolean hasSavedState = false;
        private String savedLocalName;
        private int savedAttrCount;
        private String[] savedAttrNames;
        private String[] savedAttrValues;
        // Buffered next event (from look-ahead when element is NOT empty)
        private boolean hasBuffered = false;
        private int bufferedEventType;
        WhitespaceFilteringReader(XMLStreamReader r) {{ super(r); }}
        private boolean isSkippable(int ev) throws XMLStreamException {{
            return (ev == XMLStreamConstants.CHARACTERS && super.isWhiteSpace())
                || ev == XMLStreamConstants.SPACE
                || ev == XMLStreamConstants.COMMENT;
        }}
        @Override
        public int next() throws XMLStreamException {{
            int ev;
            if (hasBuffered) {{
                ev = bufferedEventType;
                hasBuffered = false;
            }} else {{
                do {{ ev = super.next(); }} while (isSkippable(ev));
            }}
            hasSavedState = false;
            isEmptyElement = false;
            if (ev == XMLStreamConstants.START_ELEMENT) {{
                // Save state before look-ahead moves the underlying reader position
                savedLocalName = super.getLocalName();
                savedAttrCount = super.getAttributeCount();
                savedAttrNames = new String[savedAttrCount];
                savedAttrValues = new String[savedAttrCount];
                for (int i = 0; i < savedAttrCount; i++) {{
                    savedAttrNames[i] = super.getAttributeLocalName(i);
                    savedAttrValues[i] = super.getAttributeValue(i);
                }}
                hasSavedState = true;
                // Look ahead: is the next non-whitespace event END_ELEMENT?
                int peek;
                do {{ peek = super.next(); }} while (isSkippable(peek));
                if (peek == XMLStreamConstants.END_ELEMENT) {{
                    isEmptyElement = true; // END consumed; getIsEmptyElement() returns true
                }} else {{
                    hasBuffered = true;
                    bufferedEventType = peek;
                }}
            }}
            return ev;
        }}
        @Override public String getLocalName() {{
            return hasSavedState ? savedLocalName : super.getLocalName();
        }}
        @Override public int getEventType() {{
            return hasSavedState ? XMLStreamConstants.START_ELEMENT : super.getEventType();
        }}
        @Override public boolean isStartElement() {{
            return hasSavedState || super.isStartElement();
        }}
        @Override public boolean isEndElement() {{
            return !hasSavedState && super.isEndElement();
        }}
        @Override public int getAttributeCount() {{
            return hasSavedState ? savedAttrCount : super.getAttributeCount();
        }}
        @Override public String getAttributeLocalName(int i) {{
            return (hasSavedState && i >= 0 && i < savedAttrCount) ? savedAttrNames[i] : super.getAttributeLocalName(i);
        }}
        @Override public String getAttributeValue(int i) {{
            return (hasSavedState && i >= 0 && i < savedAttrCount) ? savedAttrValues[i] : super.getAttributeValue(i);
        }}
        @Override public String getAttributeValue(String ns, String name) {{
            if (hasSavedState) {{
                for (int i = 0; i < savedAttrCount; i++) {{
                    if (savedAttrNames[i].equals(name)) return savedAttrValues[i];
                }}
                return null;
            }}
            return super.getAttributeValue(ns, name);
        }}
        @Override public String getElementText() throws XMLStreamException {{
            if (isEmptyElement) {{
                hasSavedState = false;
                isEmptyElement = false;
                return """";
            }}
            StringBuilder sb = new StringBuilder();
            if (hasBuffered) {{
                if (bufferedEventType == XMLStreamConstants.CHARACTERS || bufferedEventType == XMLStreamConstants.CDATA) {{
                    sb.append(super.getText());
                }}
                if (bufferedEventType == XMLStreamConstants.END_ELEMENT) {{
                    hasBuffered = false;
                    hasSavedState = false;
                    return sb.toString();
                }}
                hasBuffered = false;
                hasSavedState = false;
            }} else {{
                hasSavedState = false;
            }}
            while (super.hasNext()) {{
                int ev = super.next();
                if (ev == XMLStreamConstants.END_ELEMENT) return sb.toString();
                if (ev == XMLStreamConstants.CHARACTERS || ev == XMLStreamConstants.CDATA) {{
                    sb.append(super.getText());
                }}
            }}
            throw new XMLStreamException(""Unexpected end of document in getElementText"");
        }}
    }}

    /** Factory — mirrors XmlReader.Create(source, settings) in C#. */
    public static XmlReader create(Object source, Object settings) {{
        try {{
            boolean ignoreWs = (settings instanceof XmlReaderSettings) && ((XmlReaderSettings) settings).isIgnoreWhitespace();
            XMLInputFactory factory = XMLInputFactory.newInstance();
            factory.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, false);
            factory.setProperty(XMLInputFactory.SUPPORT_DTD, false);
            if (source instanceof InputStream) {{
                XMLStreamReader base = factory.createXMLStreamReader((InputStream) source);
                return new XmlReader(ignoreWs ? new WhitespaceFilteringReader(base) : base);
            }} else if (source instanceof Reader) {{
                XMLStreamReader base = factory.createXMLStreamReader((Reader) source);
                return new XmlReader(ignoreWs ? new WhitespaceFilteringReader(base) : base);
            }} else if (source instanceof XmlReader) {{
                if (ignoreWs && reader != null && !(reader instanceof WhitespaceFilteringReader)) {{
                    reader = new WhitespaceFilteringReader(reader);
                }}
                return (XmlReader) source;
            }}
            throw new RuntimeException(""Unsupported XmlReader source: "" + (source == null ? ""null"" : source.getClass().getName()));
        }} catch (XMLStreamException e) {{
            throw new RuntimeException(e);
        }}
    }}

    /** Convenience overload used by converted code paths. */
    public static XmlReader create(Object source) {{
        return create(source, null);
    }}

    public static int getNodeType() {{
        attributeIndex = -1;
        return reader != null ? reader.getEventType() : XmlNodeType.getNone();
    }}

    public static boolean isStartElement() {{
        attributeIndex = -1;
        return reader != null && reader.isStartElement();
    }}

    public static boolean isStartElement(String name) {{
        attributeIndex = -1;
        return reader != null && reader.isStartElement()
            && name.equalsIgnoreCase(reader.getLocalName());
    }}

    /** Returns true if the current START_ELEMENT is a self-closing/empty element (e.g. &lt;foo/&gt;). */
    public static boolean getIsEmptyElement() {{
        return (reader instanceof WhitespaceFilteringReader) && ((WhitespaceFilteringReader) reader).isEmptyElement;
    }}

    public static String getName() {{
        try {{
            if (reader == null) return """";
            if (attributeIndex >= 0) return reader.getAttributeLocalName(attributeIndex);
            return reader.getLocalName();
        }}
        catch (Exception e) {{ return """"; }}
    }}

    public static String getValue() {{
        try {{
            if (reader == null) return """";
            if (attributeIndex >= 0) return reader.getAttributeValue(attributeIndex);
            return reader.getText();
        }}
        catch (Exception e) {{ return """"; }}
    }}

    public static String getAttribute(String name) {{
        return reader != null ? reader.getAttributeValue(null, name) : null;
    }}

    public static boolean read() {{
        try {{
            if (reader == null || !reader.hasNext()) return false;
            attributeIndex = -1;
            reader.next();
            return true;
        }} catch (XMLStreamException e) {{ return false; }}
    }}

    public static void readEndElement() {{
        try {{
            attributeIndex = -1;
            if (reader == null) return;
            // If on an empty element whose END was consumed by look-ahead, just advance.
            if (reader.isStartElement() && reader instanceof WhitespaceFilteringReader
                && ((WhitespaceFilteringReader) reader).isEmptyElement) {{
                if (reader.hasNext()) reader.next();
                return;
            }}
            while (reader.hasNext() && !reader.isEndElement()) reader.next();
            if (reader.hasNext()) reader.next();
        }} catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static double readElementContentAsDouble() {{
        try {{ return reader != null ? Double.parseDouble(reader.getElementText().trim()) : 0.0; }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static int readElementContentAsInt() {{
        try {{ return reader != null ? Integer.parseInt(reader.getElementText().trim()) : 0; }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static String readElementContentAsString() {{
        try {{ return reader != null ? reader.getElementText() : """"; }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static boolean readElementContentAsBoolean() {{
        try {{ return reader != null && Boolean.parseBoolean(reader.getElementText().trim()); }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static void moveToContent() {{
        try {{
            attributeIndex = -1;
            if (reader == null) return;
            while (reader.hasNext()) {{
                int t = reader.getEventType();
                if (t == XMLStreamConstants.START_ELEMENT
                    || t == XMLStreamConstants.END_ELEMENT
                    || t == XMLStreamConstants.END_DOCUMENT) return;
                reader.next();
            }}
        }} catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static boolean moveToFirstAttribute() {{
        if (reader != null && reader.isStartElement() && reader.getAttributeCount() > 0) {{
            attributeIndex = 0;
            return true;
        }}
        return false;
    }}

    public static void skip() {{
        try {{
            attributeIndex = -1;
            if (reader == null) return;
            if (!reader.isStartElement()) {{
                // In C#, XmlReader.Skip() on non-start-element acts like Read() (advances to next node).
                if (reader.hasNext()) reader.next();
                return;
            }}
            // If empty element, its END_ELEMENT was already consumed by look-ahead. Just advance.
            if (reader instanceof WhitespaceFilteringReader && ((WhitespaceFilteringReader) reader).isEmptyElement) {{
                if (reader.hasNext()) reader.next();
                return;
            }}
            int depth = 1;
            while (depth > 0 && reader.hasNext()) {{
                reader.next();
                if (reader.isStartElement()) {{
                    // If this child is an empty element, don't increment depth (its END was consumed)
                    if (!(reader instanceof WhitespaceFilteringReader) || !((WhitespaceFilteringReader) reader).isEmptyElement) {{
                        depth++;
                    }}
                }}
                else if (reader.isEndElement()) depth--;
            }}
            if (reader.hasNext()) reader.next();
        }} catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static int getReadState() {{
        if (reader == null) return {basePackage}.ReadState.getClosed();
        try {{ return reader.hasNext() ? {basePackage}.ReadState.getInteractive() : {basePackage}.ReadState.getEndOfFile(); }}
        catch (Exception e) {{ return {basePackage}.ReadState.getError(); }}
    }}

    @Override
    public void close() throws Exception {{
        if (reader != null) try {{ reader.close(); }} catch (XMLStreamException ignored) {{}}
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = xmlReaderCode,
            FileName = "XmlReader.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── XmlTextReader (alias of XmlReader) ───────────────────────────────────────
        var xmlTextReaderCode = $@"package {basePackage};

import java.io.InputStream;
import java.io.Reader;
import javax.xml.stream.*;

/** Replacement for System.Xml.XmlTextReader (generated by CSharpToJava converter). */
public class XmlTextReader extends XmlReader {{
    private int lineNumber = 0;
    private int linePosition = 0;
    public int LineNumber = 0;
    public int LinePosition = 0;

    public XmlTextReader() {{ super(); }}

    /** Constructs from a file path (mirrors XmlTextReader(string) in C#). */
    public XmlTextReader(String path) {{
        try {{
            XMLInputFactory factory = XMLInputFactory.newInstance();
            factory.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, false);
            factory.setProperty(XMLInputFactory.SUPPORT_DTD, false);
            java.io.FileInputStream fis = new java.io.FileInputStream(path);
            this.reader = factory.createXMLStreamReader(fis);
        }} catch (Exception e) {{ throw new RuntimeException(e); }}
    }}

    /** Constructs from an InputStream (mirrors XmlTextReader(Stream) in C#). */
    public XmlTextReader(InputStream stream) {{
        try {{
            XMLInputFactory factory = XMLInputFactory.newInstance();
            factory.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, false);
            factory.setProperty(XMLInputFactory.SUPPORT_DTD, false);
            this.reader = factory.createXMLStreamReader(stream);
        }} catch (Exception e) {{ throw new RuntimeException(e); }}
    }}

    /** Constructs from a Reader (mirrors XmlTextReader(TextReader) in C#). */
    public XmlTextReader(Reader r) {{
        try {{
            XMLInputFactory factory = XMLInputFactory.newInstance();
            factory.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, false);
            factory.setProperty(XMLInputFactory.SUPPORT_DTD, false);
            this.reader = factory.createXMLStreamReader(r);
        }} catch (Exception e) {{ throw new RuntimeException(e); }}
    }}

    public int getLineNumber() {{ return lineNumber; }}
    public int getLinePosition() {{ return linePosition; }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = xmlTextReaderCode,
            FileName = "XmlTextReader.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── XmlWriter ─────────────────────────────────────────────────────────────────
        var xmlWriterCode = $@"package {basePackage};

import java.io.InputStream;
import java.io.OutputStream;
import java.io.Writer;
import javax.xml.stream.*;

/** Replacement for System.Xml.XmlWriter backed by StAX (generated by CSharpToJava converter). */
public class XmlWriter {{
    protected static XMLStreamWriter writer;

    protected XmlWriter() {{}}

    protected XmlWriter(XMLStreamWriter writer) {{
        XmlWriter.writer = writer;
    }}

    /** Factory — mirrors XmlWriter.Create(output, settings) in C#. */
    public static XmlWriter create(Object output, Object settings) {{
        try {{
            XMLOutputFactory factory = XMLOutputFactory.newInstance();
            if (output instanceof OutputStream) {{
                return new XmlWriter(factory.createXMLStreamWriter((OutputStream) output, ""UTF-8""));
            }} else if (output instanceof Writer) {{
                return new XmlWriter(factory.createXMLStreamWriter((Writer) output));
            }}
            // InputStream passed as output is a C# idiom mismatch — return no-op writer
            return new XmlWriter();
        }} catch (XMLStreamException e) {{
            throw new RuntimeException(e);
        }}
    }}

    /** Convenience overload used by converted code paths. */
    public static XmlWriter create(Object output) {{
        return create(output, null);
    }}

    public static void writeStartElement(String localName) {{
        try {{ if (writer != null) writer.writeStartElement(localName); }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static void writeEndElement() {{
        try {{ if (writer != null) writer.writeEndElement(); }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static void writeAttributeString(String localName, String value) {{
        try {{ if (writer != null) writer.writeAttribute(localName, value != null ? value : """"); }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static void writeAttributeString(String prefix, String localName, String ns, String value) {{
        try {{
            if (writer != null) {{
                if (prefix != null && !prefix.isEmpty()) writer.writeAttribute(prefix, ns != null ? ns : """", localName, value != null ? value : """");
                else writer.writeAttribute(localName, value != null ? value : """");
            }}
        }} catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static void writeStartElement(String localName, String ns) {{
        try {{
            if (writer != null) {{
                if (ns != null && !ns.isEmpty()) writer.writeStartElement("""", localName, ns);
                else writer.writeStartElement(localName);
            }}
        }} catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static void writeElementString(String localName, String value) {{
        try {{
            if (writer != null) {{
                writer.writeStartElement(localName);
                writer.writeCharacters(value != null ? value : """");
                writer.writeEndElement();
            }}
        }} catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static void writeString(String text) {{
        try {{ if (writer != null) writer.writeCharacters(text != null ? text : """"); }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    /** Writes raw XML-ish text as character data (compatibility shim for converted calls). */
    public static void writeRaw(String text) {{
        writeString(text);
    }}

    public static void writeComment(String text) {{
        try {{ if (writer != null) writer.writeComment(text != null ? text : """"); }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static void writeEndDocument() {{
        try {{ if (writer != null) writer.writeEndDocument(); }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static void flush() {{
        try {{ if (writer != null) writer.flush(); }}
        catch (XMLStreamException e) {{ throw new RuntimeException(e); }}
    }}

    public static void close() {{
        if (writer != null) {{
            try {{ writer.flush(); }}  catch (XMLStreamException ignored) {{}}
            try {{ writer.close(); }}  catch (XMLStreamException ignored) {{}}
        }}
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = xmlWriterCode,
            FileName = "XmlWriter.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        return results;
    }

    /// <summary>
    /// Generates Java wrapper classes for System.Text.Json.* types, backed by Jackson.
    /// </summary>
    internal static List<ConversionResult> GenerateJsonWrappers(string basePackage)
    {
        var results = new List<ConversionResult>();

        // ── JsonSerializerOptions ─────────────────────────────────────────────────────
        var jsonOptionsCode = $@"package {basePackage};

/** Replacement for System.Text.Json.JsonSerializerOptions (generated by CSharpToJava converter). */
public class JsonSerializerOptions {{
    private boolean writeIndented = false;
    public boolean isWriteIndented()          {{ return writeIndented; }}
    public void    setWriteIndented(boolean v) {{ writeIndented = v; }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = jsonOptionsCode,
            FileName = "JsonSerializerOptions.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── JsonSerializer ────────────────────────────────────────────────────────────
        var jsonSerializerCode = $@"package {basePackage};

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

/** Replacement for System.Text.Json.JsonSerializer (generated by CSharpToJava converter). */
public class JsonSerializer {{
    private static final ObjectMapper MAPPER = new ObjectMapper()
        .configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);

    @SuppressWarnings(""unchecked"")
    public static <T> String serialize(T value, Object options) {{
        try {{ return MAPPER.writeValueAsString(value); }}
        catch (Exception e) {{ throw new RuntimeException(e); }}
    }}

    @SuppressWarnings(""unchecked"")
    public static <T> String serialize(T value) {{
        try {{ return MAPPER.writeValueAsString(value); }}
        catch (Exception e) {{ throw new RuntimeException(e); }}
    }}

    @SuppressWarnings(""unchecked"")
    public static <T> T deserialize(String json, Class<T> clazz) {{
        try {{ return MAPPER.readValue(json, clazz); }}
        catch (Exception e) {{ throw new RuntimeException(e); }}
    }}

    public static Object deserialize(String json) {{
        try {{ return MAPPER.readValue(json, Object.class); }}
        catch (Exception e) {{ throw new RuntimeException(e); }}
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = jsonSerializerCode,
            FileName = "JsonSerializer.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        return results;
    }

    /// <summary>
    /// Generates general-purpose Java utility stubs that replace .NET BCL types/methods.
    /// </summary>
    internal static List<ConversionResult> GenerateUtilityClasses(string basePackage)
    {
        var results = new List<ConversionResult>();

        // ── MathHelper ─ TryParse stubs for numeric types ───────────────────────────
        var mathHelperCode = $@"package {basePackage};

/** Numeric TryParse helpers (generated by CSharpToJava converter, replacing System numeric TryParse). */
public class MathHelper {{
    public static boolean tryParseDouble(String s, DoubleHolder result) {{
        try {{ result.value = Double.parseDouble(s); return true; }}
        catch (NumberFormatException e) {{ return false; }}
    }}
    public static boolean tryParseFloat(String s, FloatHolder result) {{
        try {{ result.value = Float.parseFloat(s); return true; }}
        catch (NumberFormatException e) {{ return false; }}
    }}
    public static boolean tryParseInt(String s, IntHolder result) {{
        try {{ result.value = Integer.parseInt(s); return true; }}
        catch (NumberFormatException e) {{ return false; }}
    }}
    public static boolean tryParseLong(String s, LongHolder result) {{
        try {{ result.value = Long.parseLong(s); return true; }}
        catch (NumberFormatException e) {{ return false; }}
    }}
    public static boolean tryParseBool(String s, BoolHolder result) {{
        if (""true"".equalsIgnoreCase(s))  {{ result.value = true;  return true; }}
        if (""false"".equalsIgnoreCase(s)) {{ result.value = false; return true; }}
        return false;
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = mathHelperCode,
            FileName = "MathHelper.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── StringHelper ─ static String utilities missing from java.lang.String ───
        var stringHelperCode = $@"package {basePackage};

import java.util.Locale;

/** String utilities (generated by CSharpToJava converter, replacing System.String static methods). */
public class StringHelper {{
    public static String concat(Object... values) {{
        if (values == null || values.length == 0) {{
            return """";
        }}

        StringBuilder builder = new StringBuilder();
        for (Object value : values) {{
            appendConcatValue(builder, value);
        }}
        return builder.toString();
    }}
    public static boolean isNullOrEmpty(String s) {{
        return s == null || s.isEmpty();
    }}
    public static boolean isNullOrWhiteSpace(String s) {{
        return s == null || s.trim().isEmpty();
    }}
    /** Mirrors C# String.Compare(s1, s2) */
    public static int compare(String s1, String s2) {{
        if (s1 == null && s2 == null) return 0;
        if (s1 == null) return -1;
        if (s2 == null) return  1;
        return s1.compareTo(s2);
    }}
    /** Mirrors C# String.Compare(s1, s2, ignoreCase) */
    public static int compare(String s1, String s2, boolean ignoreCase) {{
        if (s1 == null && s2 == null) return 0;
        if (s1 == null) return -1;
        if (s2 == null) return  1;
        return ignoreCase ? s1.compareToIgnoreCase(s2) : s1.compareTo(s2);
    }}
    /** Mirrors C# String.Compare(s1, s2, ignoreCase, culture) */
    public static int compare(String s1, String s2, boolean ignoreCase, Object culture) {{
        return compare(s1, s2, ignoreCase);
    }}
    /** Mirrors C# String.Compare(s1, s2, StringComparison) */
    public static int compare(String s1, String s2, int comparison) {{
        return compare(s1, s2, comparison == 1 || comparison == 3 || comparison == 5);
    }}
    /** Mirrors C# String.Equals(a, b) */
    public static boolean equals(String s1, String s2) {{
        if (s1 == null || s2 == null) {{
            return s1 == s2;
        }}
        return s1.equals(s2);
    }}
    /** Mirrors C# String.Equals(a, b, StringComparison) via ignoreCase semantics. */
    public static boolean equals(String s1, String s2, boolean ignoreCase) {{
        if (s1 == null || s2 == null) {{
            return s1 == s2;
        }}
        return ignoreCase ? s1.equalsIgnoreCase(s2) : s1.equals(s2);
    }}
    /** Mirrors C# String.Equals(a, b, bool ignoreCase, CultureInfo culture) */
    public static boolean equals(String s1, String s2, boolean ignoreCase, Object culture) {{
        return equals(s1, s2, ignoreCase);
    }}
    /** Mirrors C# String.Equals(a, b, StringComparison) */
    public static boolean equals(String s1, String s2, int comparison) {{
        return equals(s1, s2, comparison == 1 || comparison == 3 || comparison == 5);
    }}
    /** Mirrors C# String.StartsWith(value, StringComparison) */
    public static boolean startsWith(String s, String prefix, boolean ignoreCase) {{
        if (s == null || prefix == null) {{
            return s == prefix;
        }}
        if (prefix.length() > s.length()) {{
            return false;
        }}
        return ignoreCase
            ? s.regionMatches(true, 0, prefix, 0, prefix.length())
            : s.startsWith(prefix);
    }}
    /** Mirrors C# String.StartsWith(value, StringComparison) */
    public static boolean startsWith(String s, String prefix, int comparison) {{
        return startsWith(s, prefix, comparison == 1 || comparison == 3 || comparison == 5);
    }}
    /** Mirrors C# String.EndsWith(value, StringComparison) */
    public static boolean endsWith(String s, String suffix, boolean ignoreCase) {{
        if (s == null || suffix == null) {{
            return s == suffix;
        }}
        if (suffix.length() > s.length()) {{
            return false;
        }}
        if (ignoreCase) {{
            return s.regionMatches(true, s.length() - suffix.length(), suffix, 0, suffix.length());
        }}
        return s.endsWith(suffix);
    }}
    /** Mirrors C# String.EndsWith(value, StringComparison) */
    public static boolean endsWith(String s, String suffix, int comparison) {{
        return endsWith(s, suffix, comparison == 1 || comparison == 3 || comparison == 5);
    }}
    /** Mirrors C# String.Contains(value, StringComparison) */
    public static boolean contains(String s, String value, boolean ignoreCase) {{
        return indexOf(s, value, ignoreCase) >= 0;
    }}
    /** Mirrors C# String.Contains(value, StringComparison) */
    public static boolean contains(String s, String value, int comparison) {{
        return contains(s, value, comparison == 1 || comparison == 3 || comparison == 5);
    }}
    /** Mirrors C# String.IndexOf(value, StringComparison) */
    public static int indexOf(String s, String value, boolean ignoreCase) {{
        return ignoreCase
            ? s.toLowerCase(Locale.ROOT).indexOf(value.toLowerCase(Locale.ROOT))
            : s.indexOf(value);
    }}
    /** Mirrors C# String.IndexOf(value, startIndex, StringComparison) */
    public static int indexOf(String s, String value, int startIndex, boolean ignoreCase) {{
        return ignoreCase
            ? s.toLowerCase(Locale.ROOT).indexOf(value.toLowerCase(Locale.ROOT), startIndex)
            : s.indexOf(value, startIndex);
    }}
    /** Mirrors C# String.IndexOf(value, StringComparison) */
    public static int indexOf(String s, String value, int comparison) {{
        return indexOf(s, value, comparison == 1 || comparison == 3 || comparison == 5);
    }}
    /** Mirrors C# String.IndexOf(value, startIndex, StringComparison) */
    public static int indexOf(String s, String value, int startIndex, int comparison) {{
        return indexOf(s, value, startIndex, comparison == 1 || comparison == 3 || comparison == 5);
    }}
    /** Mirrors C# String.LastIndexOf(value, StringComparison) */
    public static int lastIndexOf(String s, String value, boolean ignoreCase) {{
        return ignoreCase
            ? s.toLowerCase(Locale.ROOT).lastIndexOf(value.toLowerCase(Locale.ROOT))
            : s.lastIndexOf(value);
    }}
    /** Mirrors C# String.LastIndexOf(value, startIndex, StringComparison) */
    public static int lastIndexOf(String s, String value, int startIndex, boolean ignoreCase) {{
        return ignoreCase
            ? s.toLowerCase(Locale.ROOT).lastIndexOf(value.toLowerCase(Locale.ROOT), startIndex)
            : s.lastIndexOf(value, startIndex);
    }}
    /** Mirrors C# String.LastIndexOf(value, StringComparison) */
    public static int lastIndexOf(String s, String value, int comparison) {{
        return lastIndexOf(s, value, comparison == 1 || comparison == 3 || comparison == 5);
    }}
    /** Mirrors C# String.LastIndexOf(value, startIndex, StringComparison) */
    public static int lastIndexOf(String s, String value, int startIndex, int comparison) {{
        return lastIndexOf(s, value, startIndex, comparison == 1 || comparison == 3 || comparison == 5);
    }}

    private static void appendConcatValue(StringBuilder builder, Object value) {{
        if (value == null) {{
            return;
        }}

        if (value instanceof Iterable<?> iterable) {{
            for (Object item : iterable) {{
                appendConcatValue(builder, item);
            }}
            return;
        }}

        if (value instanceof Object[] array) {{
            for (Object item : array) {{
                appendConcatValue(builder, item);
            }}
            return;
        }}

        builder.append(value);
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = stringHelperCode,
            FileName = "StringHelper.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── EnumHelper ─ Enum.TryParse / Enum.Parse stubs ────────────────────────────
        var enumHelperCode = $@"package {basePackage};

/** Enum parsing utilities (generated by CSharpToJava converter, replacing System.Enum methods). */
public class EnumHelper {{
    /** Mirrors Enum.TryParse&lt;T&gt;(name, ignoreCase, out T). Returns false (type-erasure limitation). */
    @SuppressWarnings(""unchecked"")
    public static <T> boolean tryParse(String name, boolean ignoreCase, ObjectHolder<T> result) {{
        return false; // Runtime: use T.valueOf(name) in calling code when enum class is known.
    }}
    /** Mirrors Enum.TryParse&lt;T&gt;(name, out T). */
    @SuppressWarnings(""unchecked"")
    public static <T> boolean tryParse(String name, ObjectHolder<T> result) {{
        return false;
    }}
    /** Mirrors Enum.Parse(type, name). */
    public static Object parse(Class<?> enumType, String name) {{
        try {{ return Enum.valueOf((Class<Enum>) enumType, name); }}
        catch (Exception e) {{ throw new IllegalArgumentException(""No enum constant: "" + name, e); }}
    }}
    /** Mirrors Enum.Parse(type, name, ignoreCase). */
    public static Object parse(Class<?> enumType, String name, boolean ignoreCase) {{
        return parse(enumType, name);
    }}
    /** Mirrors Enum.GetValues(typeof(T)). */
    @SuppressWarnings(""unchecked"")
    public static Object[] getValues(Class<?> enumType) {{
        return enumType.getEnumConstants();
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = enumHelperCode,
            FileName = "EnumHelper.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── FileHelper ─ Replaces System.IO.File static methods ──────────────────────
        var fileHelperCode = $@"package {basePackage};

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;

/** File I/O helpers (generated by CSharpToJava converter, replacing System.IO.File). */
public class FileHelper {{
    public static String readAllText(String path) {{
        try {{ return new String(Files.readAllBytes(Paths.get(path)), StandardCharsets.UTF_8); }}
        catch (IOException e) {{ throw new UncheckedIOException(e); }}
    }}
    public static void writeAllText(String path, String content) {{
        try {{ Files.write(Paths.get(path), content.getBytes(StandardCharsets.UTF_8)); }}
        catch (IOException e) {{ throw new UncheckedIOException(e); }}
    }}
    public static InputStream openRead(String path) {{
        try {{ return new FileInputStream(path); }}
        catch (FileNotFoundException e) {{ throw new UncheckedIOException(e); }}
    }}
    public static TextReader openText(String path) {{
        try {{ return new TextReader(new InputStreamReader(new FileInputStream(path), StandardCharsets.UTF_8)); }}
        catch (FileNotFoundException e) {{ throw new UncheckedIOException(e); }}
    }}
    /** Mirrors File.Open(path, FileMode) — returns an InputStream for reading. */
    public static InputStream open(String path, int fileMode) {{
        return openRead(path);
    }}
    /** Mirrors File.Create(path). */
    public static OutputStream create(String path) {{
        try {{ return new FileOutputStream(path); }}
        catch (FileNotFoundException e) {{ throw new UncheckedIOException(e); }}
    }}
    public static boolean exists(String path) {{ return new File(path).exists(); }}
    public static void delete(String path) {{ new File(path).delete(); }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = fileHelperCode,
            FileName = "FileHelper.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── FileMode ─ System.IO.FileMode enum constants ─────────────────────────────
        var fileModeCode = $@"package {basePackage};

/** Replacement for System.IO.FileMode (generated by CSharpToJava converter). */
public class FileMode {{
    public static final int CreateNew  = 1;
    public static final int Create     = 2;
    public static final int Open       = 3;
    public static final int OpenOrCreate = 4;
    public static final int Truncate   = 5;
    public static final int Append     = 6;

    public static int getCreateNew()    {{ return CreateNew; }}
    public static int getCreate()       {{ return Create; }}
    public static int getOpen()         {{ return Open; }}
    public static int getOpenOrCreate() {{ return OpenOrCreate; }}
    public static int getTruncate()     {{ return Truncate; }}
    public static int getAppend()       {{ return Append; }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = fileModeCode,
            FileName = "FileMode.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── CultureInfo ─ Stub for System.Globalization.CultureInfo ──────────────────
        var cultureInfoCode = $@"package {basePackage};

import java.util.Locale;

/** Stub for System.Globalization.CultureInfo (generated by CSharpToJava converter). */
public class CultureInfo {{
    private final Locale locale;

    public CultureInfo(String name) {{
        this.locale = Locale.forLanguageTag(name.replace('_', '-'));
    }}

    public static CultureInfo getCurrentCulture() {{
        return new CultureInfo(Locale.getDefault().toLanguageTag());
    }}
    public static void setCurrentCulture(Locale locale) {{
        // no-op: JVM locale is JVM-wide setting, not thread-local
    }}
    public static CultureInfo getInvariantCulture() {{
        return new CultureInfo(""en-US"");
    }}
    public Locale toLocale() {{ return locale; }}
    @Override public String toString() {{ return locale.toString(); }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = cultureInfoCode,
            FileName = "CultureInfo.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        var equalityComparerCode = $@"package {basePackage};

/** Replacement for System.Collections.Generic.IEqualityComparer&lt;T&gt; (generated by CSharpToJava converter). */
public interface IEqualityComparer<T> {{
    boolean equals(T x, T y);
    int hashCode(T obj);
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = equalityComparerCode,
            FileName = "IEqualityComparer.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── LinkedListNode<T> ─ Mirrors C# System.Collections.Generic.LinkedListNode<T> ──
        var linkedListNodeCode = $@"package {basePackage};

/**
 * Thin node wrapper that mirrors C# LinkedListNode&lt;T&gt; (generated by CSharpToJava converter).
 * Provides getValue(), getNext(), getPrevious(). Fields are package-private for LinkedListWithNodes.
 */
public class LinkedListNode<T> {{
    T value;
    LinkedListNode<T> next;
    LinkedListNode<T> prev;
    LinkedListWithNodes<T> list;

    public LinkedListNode(T value) {{ this.value = value; }}

    public T getValue() {{ return value; }}
    public void setValue(T value) {{ this.value = value; }}
    public LinkedListNode<T> getNext() {{ return next; }}
    public LinkedListNode<T> getPrevious() {{ return prev; }}
    public LinkedListWithNodes<T> getList() {{ return list; }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = linkedListNodeCode,
            FileName = "LinkedListNode.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── LinkedListWithNodes<T> ─ C#-style doubly-linked list with node-based API ──
        var linkedListWithNodesCode = $@"package {basePackage};

import java.util.Iterator;
import java.util.NoSuchElementException;

/**
 * Doubly-linked list mirroring C# System.Collections.Generic.LinkedList&lt;T&gt;.
 * Provides node-based access: getFirst()/getLast() return LinkedListNode&lt;T&gt;.
 * Generated by CSharpToJava converter.
 */
public class LinkedListWithNodes<T> implements Iterable<T> {{
    private LinkedListNode<T> head;
    private LinkedListNode<T> tail;
    private int count;

    public int size() {{ return count; }}
    public boolean isEmpty() {{ return count == 0; }}

    public LinkedListNode<T> getFirst() {{ return head; }}
    public LinkedListNode<T> getLast() {{ return tail; }}

    public LinkedListNode<T> addFirst(T value) {{
        LinkedListNode<T> node = new LinkedListNode<>(value);
        node.list = this;
        node.next = head;
        node.prev = null;
        if (head != null) head.prev = node;
        head = node;
        if (tail == null) tail = node;
        count++;
        return node;
    }}

    public void addFirst(LinkedListNode<T> node) {{
        if (node.list != null) node.list.remove(node);
        node.list = this;
        node.next = head;
        node.prev = null;
        if (head != null) head.prev = node;
        head = node;
        if (tail == null) tail = node;
        count++;
    }}

    public LinkedListNode<T> addLast(T value) {{
        LinkedListNode<T> node = new LinkedListNode<>(value);
        node.list = this;
        node.prev = tail;
        node.next = null;
        if (tail != null) tail.next = node;
        tail = node;
        if (head == null) head = node;
        count++;
        return node;
    }}

    public void addLast(LinkedListNode<T> node) {{
        if (node.list != null) node.list.remove(node);
        node.list = this;
        node.prev = tail;
        node.next = null;
        if (tail != null) tail.next = node;
        tail = node;
        if (head == null) head = node;
        count++;
    }}

    public boolean add(T value) {{ addLast(value); return true; }}

    public LinkedListNode<T> addAfter(LinkedListNode<T> node, T value) {{
        LinkedListNode<T> n = new LinkedListNode<>(value);
        n.list = this;
        n.prev = node;
        n.next = node.next;
        if (node.next != null) node.next.prev = n; else tail = n;
        node.next = n;
        count++;
        return n;
    }}

    public LinkedListNode<T> addBefore(LinkedListNode<T> node, T value) {{
        LinkedListNode<T> n = new LinkedListNode<>(value);
        n.list = this;
        n.next = node;
        n.prev = node.prev;
        if (node.prev != null) node.prev.next = n; else head = n;
        node.prev = n;
        count++;
        return n;
    }}

    public boolean remove(LinkedListNode<T> node) {{ return removeNode(node); }}

    public boolean remove(Object value) {{
        for (LinkedListNode<T> n = head; n != null; n = n.next) {{
            if ((value == null && n.value == null) || (value != null && value.equals(n.value))) {{
                removeNode(n);
                return true;
            }}
        }}
        return false;
    }}

    private boolean removeNode(LinkedListNode<T> node) {{
        if (node.prev == null && node.next == null && head != node) return false;
        if (node.prev != null) node.prev.next = node.next; else head = node.next;
        if (node.next != null) node.next.prev = node.prev; else tail = node.prev;
        node.prev = null;
        node.next = null;
        node.list = null;
        count--;
        return true;
    }}

    public boolean contains(Object value) {{
        for (LinkedListNode<T> n = head; n != null; n = n.next) {{
            if ((value == null && n.value == null) || (value != null && value.equals(n.value)))
                return true;
        }}
        return false;
    }}

    public void clear() {{ head = null; tail = null; count = 0; }}

    @Override
    public Iterator<T> iterator() {{
        return new Iterator<T>() {{
            LinkedListNode<T> current = head;
            @Override public boolean hasNext() {{ return current != null; }}
            @Override public T next() {{
                if (current == null) throw new NoSuchElementException();
                T val = current.value;
                current = current.next;
                return val;
            }}
        }};
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = linkedListWithNodesCode,
            FileName = "LinkedListWithNodes.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── InvalidDataException ─ missing from standard Java ────────────────────────
        var invalidDataExCode = $@"package {basePackage};

/** Replacement for System.IO.InvalidDataException (generated by CSharpToJava converter). */
public class InvalidDataException extends RuntimeException {{
    public InvalidDataException(String message) {{ super(message); }}
    public InvalidDataException(String message, Throwable cause) {{ super(message, cause); }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = invalidDataExCode,
            FileName = "InvalidDataException.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── TextReader ─ Replacement for System.IO.TextReader with Peek() support ──
        var textReaderCode = $@"package {basePackage};

import java.io.*;
import java.nio.charset.StandardCharsets;

/**
 * Replacement for System.IO.TextReader (generated by CSharpToJava converter).
 * Adds peek() support missing from java.io.Reader.
 */
public class TextReader implements AutoCloseable {{
    private final PushbackReader inner;

    public TextReader(Reader r) {{
        this.inner = (r instanceof PushbackReader) ? (PushbackReader) r
                   : new PushbackReader(new BufferedReader(r));
    }}

    /** Mirrors C# TextReader.Peek() — reads next char without consuming it. Returns -1 at end. */
    public int peek() {{
        try {{
            int c = inner.read();
            if (c != -1) inner.unread(c);
            return c;
        }} catch (IOException e) {{ return -1; }}
    }}

    /** Reads next character, returns -1 at end of stream. */
    public int read() {{
        try {{ return inner.read(); }} catch (IOException e) {{ return -1; }}
    }}

    /** Reads text until end of line. Returns null at end of stream. */
    public String readLine() {{
        try {{
            StringBuilder sb = new StringBuilder();
            int c;
            while ((c = inner.read()) != -1 && c != '\n') {{
                if (c != '\r') sb.append((char) c);
            }}
            return (sb.length() > 0 || c != -1) ? sb.toString() : null;
        }} catch (IOException e) {{ return null; }}
    }}

    /** Reads all remaining text. */
    public String readToEnd() {{
        try {{
            char[] buf = new char[4096];
            StringBuilder sb = new StringBuilder();
            int n;
            while ((n = inner.read(buf)) != -1) sb.append(buf, 0, n);
            return sb.toString();
        }} catch (IOException e) {{ return """"; }}
    }}

    @Override
    public void close() throws Exception {{ inner.close(); }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = textReaderCode,
            FileName = "TextReader.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── ThreadHelper ─ Stub for System.Threading.Thread culture methods ──────────
        var threadHelperCode = $@"package {basePackage};

import java.util.Locale;

/**
 * Stub for System.Threading.Thread (generated by CSharpToJava converter).
 * Provides getCurrentCulture()/setCurrentCulture() used in C# thread-locale patterns.
 */
public class ThreadHelper {{
    private static final ThreadHelper INSTANCE = new ThreadHelper();

    /** Mirrors Thread.CurrentThread (returns a ThreadHelper proxy). */
    public static ThreadHelper currentThread() {{ return INSTANCE; }}

    /** Mirrors Thread.CurrentThread.CurrentCulture getter. */
    public CultureInfo getCurrentCulture() {{ return CultureInfo.getCurrentCulture(); }}

    /** Mirrors Thread.CurrentThread.CurrentCulture setter with CultureInfo. */
    public void setCurrentCulture(CultureInfo culture) {{ /* locale-setting is global in JVM */ }}

    /** Mirrors Thread.CurrentThread.CurrentCulture setter with Locale. */
    public void setCurrentCulture(Locale locale) {{ Locale.setDefault(locale); }}

    /** Mirrors Thread.CurrentThread.CurrentCulture setter with Object (type-erased). */
    public void setCurrentCulture(Object culture) {{ /* no-op */ }}

    /** Thread name (stub). */
    public String getName() {{ return java.lang.Thread.currentThread().getName(); }}

    /** No-op join (stub). */
    public void join() throws InterruptedException {{ }}

    /** Start (stub — not a real Thread). */
    public void start() {{ }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = threadHelperCode,
            FileName = "ThreadHelper.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        // ── ArrayHelper ─ Parallel array sort (C# Array.Sort(keys[], items[])) ───────
        var arrayHelperCode = $@"package {basePackage};

import java.util.Arrays;

/**
 * Array utilities (generated by CSharpToJava converter).
 * Provides parallel-sort to replace C# Array.Sort(keys, items).
 */
public class ArrayHelper {{
    /** Mirrors C# Array.Sort(double[] keys, int[] items): sorts keys ascending, reorders items to match. */
    public static void sortParallel(double[] keys, int[] items) {{
        int n = keys.length;
        Integer[] indices = new Integer[n];
        for (int i = 0; i < n; i++) indices[i] = i;
        Arrays.sort(indices, (a, b) -> Double.compare(keys[a], keys[b]));
        double[] sk = new double[n]; int[] sv = new int[n];
        for (int i = 0; i < n; i++) {{ sk[i] = keys[indices[i]]; sv[i] = items[indices[i]]; }}
        System.arraycopy(sk, 0, keys, 0, n); System.arraycopy(sv, 0, items, 0, n);
    }}
    /** Mirrors C# Array.Sort(double[] keys, T[] items): sorts keys ascending, reorders items to match. */
    @SuppressWarnings(""unchecked"")
    public static <T> void sortParallel(double[] keys, T[] items) {{
        int n = keys.length;
        Integer[] indices = new Integer[n];
        for (int i = 0; i < n; i++) indices[i] = i;
        Arrays.sort(indices, (a, b) -> Double.compare(keys[a], keys[b]));
        double[] sk = new double[n]; T[] sv = (T[]) new Object[n];
        for (int i = 0; i < n; i++) {{ sk[i] = keys[indices[i]]; sv[i] = items[indices[i]]; }}
        System.arraycopy(sk, 0, keys, 0, n); System.arraycopy(sv, 0, items, 0, n);
    }}
}}
";
        results.Add(new ConversionResult
        {
            Success = true,
            GeneratedCode = arrayHelperCode,
            FileName = "ArrayHelper.java",
            Package = basePackage,
            Diagnostics = new List<Context.DiagnosticMessage>()
        });

        return results;
    }
}
