package io.github.ningpp.compat;

/** Replacement for System.Threading.AbandonedMutexException (generated by CSharpToJava converter). */
public class AbandonedMutexException extends SystemException {
    public AbandonedMutexException() { super(); }
    public AbandonedMutexException(String message) { super(message); }
    public AbandonedMutexException(String message, Throwable cause) { super(message, cause); }
}
