package io.github.ningpp.compat;

/** Replacement for System.AccessViolationException (generated by CSharpToJava converter). */
public class AccessViolationException extends SystemException {
    public AccessViolationException() { super(); }
    public AccessViolationException(String message) { super(message); }
    public AccessViolationException(String message, Throwable cause) { super(message, cause); }
}
