package io.github.ningpp.compat;

/** Replacement for System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException (generated by CSharpToJava converter). */
public class ActiveDirectoryObjectNotFoundException extends RuntimeException {
    public ActiveDirectoryObjectNotFoundException() { super(); }
    public ActiveDirectoryObjectNotFoundException(String message) { super(message); }
    public ActiveDirectoryObjectNotFoundException(String message, Throwable cause) { super(message, cause); }
}
