package io.github.ningpp.compat;

/** Replacement for System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException (generated by CSharpToJava converter). */
public class ActiveDirectoryOperationException extends RuntimeException {
    public ActiveDirectoryOperationException() { super(); }
    public ActiveDirectoryOperationException(String message) { super(message); }
    public ActiveDirectoryOperationException(String message, Throwable cause) { super(message, cause); }
}
