package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ActionPreferenceStopException (generated by CSharpToJava converter). */
public class ActionPreferenceStopException extends RuntimeException {
    private int hresult;
    public ActionPreferenceStopException() { super(); }
    public ActionPreferenceStopException(String message) { super(message); }
    public ActionPreferenceStopException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
