package io.github.ningpp.compat;

/** Replacement for System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectExistsException (generated by CSharpToJava converter). */
public class ActiveDirectoryObjectExistsException extends RuntimeException {
    public ActiveDirectoryObjectExistsException() { super(); }
    public ActiveDirectoryObjectExistsException(String message) { super(message); }
    public ActiveDirectoryObjectExistsException(String message, Throwable cause) { super(message, cause); }
}
