package io.github.ningpp.compat;

/** Replacement for System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException (generated by CSharpToJava converter). */
public class ActiveDirectoryOperationException extends RuntimeException {
    private int hresult;
    public ActiveDirectoryOperationException() { super(); }
    public ActiveDirectoryOperationException(String message) { super(message); }
    public ActiveDirectoryOperationException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
