package io.github.ningpp.compat;

/** Replacement for System.DirectoryServices.ActiveDirectory.ActiveDirectoryServerDownException (generated by CSharpToJava converter). */
public class ActiveDirectoryServerDownException extends RuntimeException {
    public ActiveDirectoryServerDownException() { super(); }
    public ActiveDirectoryServerDownException(String message) { super(message); }
    public ActiveDirectoryServerDownException(String message, Throwable cause) { super(message, cause); }
}
