package io.github.ningpp.compat;

/** Replacement for System.AggregateException (generated by CSharpToJava converter). */
public class AggregateException extends RuntimeException {
    public AggregateException() { super(); }
    public AggregateException(String message) { super(message); }
    public AggregateException(String message, Throwable cause) { super(message, cause); }
}
