package io.github.ningpp.compat;

/** Replacement for System.Reflection.AmbiguousMatchException (generated by CSharpToJava converter). */
public class AmbiguousMatchException extends SystemException {
    public AmbiguousMatchException() { super(); }
    public AmbiguousMatchException(String message) { super(message); }
    public AmbiguousMatchException(String message, Throwable cause) { super(message, cause); }
}
