package io.github.ningpp.compat;

/** Replacement for System.AppDomainUnloadedException (generated by CSharpToJava converter). */
public class AppDomainUnloadedException extends SystemException {
    public AppDomainUnloadedException() { super(); }
    public AppDomainUnloadedException(String message) { super(message); }
    public AppDomainUnloadedException(String message, Throwable cause) { super(message, cause); }
}
