package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ApplicationFailedException (generated by CSharpToJava converter). */
public class ApplicationFailedException extends RuntimeException {
    public ApplicationFailedException() { super(); }
    public ApplicationFailedException(String message) { super(message); }
    public ApplicationFailedException(String message, Throwable cause) { super(message, cause); }
}
