package io.github.ningpp.compat;

/** Replacement for System.ArithmeticException (generated by CSharpToJava converter). */
public class ArithmeticException extends SystemException {
    public ArithmeticException() { super(); }
    public ArithmeticException(String message) { super(message); }
    public ArithmeticException(String message, Throwable cause) { super(message, cause); }
}
