package io.github.ningpp.compat;

import java.util.ArrayList;
import java.util.Arrays;

/**
 * Array utilities (generated by CSharpToJava converter).
 * Provides parallel-sort to replace C# Array.Sort(keys, items).
 */
public class ArrayHelper {

    /**
     * Null-safe array to mutable List.
     * Returns an empty ArrayList for null input; each element (including null)
     * is preserved. Unlike {@code Arrays.asList}, the returned list is fully
     * mutable (supports add/remove/clear) and independent from the source array.
     */
    public static <T> ArrayList<T> toList(T[] array) {
        if (array == null) return new ArrayList<>();
        var list = new ArrayList<T>(array.length);
        for (T item : array) list.add(item);
        return list;
    }
    /** Mirrors C# Array.Sort(double[] keys, int[] items): sorts keys ascending, reorders items to match. */
    public static void sortParallel(double[] keys, int[] items) {
        int n = keys.length;
        Integer[] indices = new Integer[n];
        for (int i = 0; i < n; i++) indices[i] = i;
        Arrays.sort(indices, (a, b) -> Double.compare(keys[a], keys[b]));
        double[] sk = new double[n]; int[] sv = new int[n];
        for (int i = 0; i < n; i++) { sk[i] = keys[indices[i]]; sv[i] = items[indices[i]]; }
        System.arraycopy(sk, 0, keys, 0, n); System.arraycopy(sv, 0, items, 0, n);
    }
    /** Mirrors C# Array.Sort(double[] keys, T[] items): sorts keys ascending, reorders items to match. */
    @SuppressWarnings("unchecked")
    public static <T> void sortParallel(double[] keys, T[] items) {
        int n = keys.length;
        Integer[] indices = new Integer[n];
        for (int i = 0; i < n; i++) indices[i] = i;
        Arrays.sort(indices, (a, b) -> Double.compare(keys[a], keys[b]));
        double[] sk = new double[n]; T[] sv = (T[]) new Object[n];
        for (int i = 0; i < n; i++) { sk[i] = keys[indices[i]]; sv[i] = items[indices[i]]; }
        System.arraycopy(sk, 0, keys, 0, n); System.arraycopy(sv, 0, items, 0, n);
    }
}
