package io.github.ningpp.compat;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.IntFunction;
import java.util.function.UnaryOperator;

/**
 * Array utilities (generated by CSharpToJava converter).
 * Provides parallel-sort to replace C# Array.Sort(keys, items).
 */
public class ArrayHelper {

    /**
     * Null-safe array/varargs to mutable List.
     * Returns an empty ArrayList for null input; each element (including null)
     * is preserved. Unlike {@code Arrays.asList}, the returned list is fully
     * mutable (supports add/remove/clear) and independent from the source array.
     */
    @SafeVarargs
    public static <T> CSharpList<T> toList(T... items) {
        if (items == null) return new CSharpList<>();
        var list = new CSharpList<T>(items.length);
        for (T item : items) list.add(item);
        return list;
    }

    /**
     * Null-preserving, fixed-size list view backed by the source array.
     * Mirrors C# arrays exposed as IList<T>: indexed set writes through to the
     * array, while add/remove remain unsupported.
     */
    public static <T> CSharpGenericIList<T> asListView(T[] items) {
        if (items == null) return null;
        return new ArrayBackedListView<>(items);
    }

    /**
     * A fixed-size list view backed by a Java array.
     * Supports get(), set(), size(), and iteration; structural modifications
     * (add/remove/clear) throw UnsupportedOperationException, matching the
     * C# behavior of arrays exposed as IList&lt;T&gt;.
     */
    private static class ArrayBackedListView<T> extends java.util.AbstractList<T> implements CSharpGenericIList<T> {
        private final T[] array;

        ArrayBackedListView(T[] array) {
            this.array = array;
        }

        @Override
        public T get(int index) {
            return array[index];
        }

        @Override
        public T set(int index, T element) {
            T old = array[index];
            array[index] = element;
            return old;
        }

        @Override
        public int size() {
            return array.length;
        }

        @Override
        public CSharpGenericEnumerator<T> iterator() {
            return CSharpGenericEnumerator.from(super.iterator());
        }

        @Override
        public void copyTo(T[] dest, int destIndex) {
            for (int i = 0; i < array.length; i++) {
                dest[destIndex + i] = array[i];
            }
        }

        @Override
        public int getCount() {
            return array.length;
        }

        @Override
        public boolean getIsReadOnly() {
            return false;
        }

        @Override
        public void insert(int index, T item) {
            throw new UnsupportedOperationException();
        }

        @Override
        public void removeAt(int index) {
            throw new UnsupportedOperationException();
        }
    }

    public static <T> T[] copyArray(T[] items) {
        return items == null ? null : Arrays.copyOf(items, items.length);
    }

    @SuppressWarnings("unchecked")
    public static <T> T[] copyArray(Object[] items, IntFunction<T[]> factory) {
        if (items == null) return null;
        T[] copy = factory.apply(items.length);
        for (int i = 0; i < items.length; i++) copy[i] = (T) items[i];
        return copy;
    }

    public static <T> T[] copyStructArray(T[] items, IntFunction<T[]> factory, UnaryOperator<T> cloner) {
        if (items == null) return null;
        T[] copy = factory.apply(items.length);
        for (int i = 0; i < items.length; i++) {
            T item = items[i];
            copy[i] = item == null ? null : cloner.apply(item);
        }
        return copy;
    }

    public static int[] copyArray(int[] items) {
        return items == null ? null : Arrays.copyOf(items, items.length);
    }

    public static long[] copyArray(long[] items) {
        return items == null ? null : Arrays.copyOf(items, items.length);
    }

    public static double[] copyArray(double[] items) {
        return items == null ? null : Arrays.copyOf(items, items.length);
    }

    public static float[] copyArray(float[] items) {
        return items == null ? null : Arrays.copyOf(items, items.length);
    }

    public static boolean[] copyArray(boolean[] items) {
        return items == null ? null : Arrays.copyOf(items, items.length);
    }

    public static byte[] copyArray(byte[] items) {
        return items == null ? null : Arrays.copyOf(items, items.length);
    }

    public static short[] copyArray(short[] items) {
        return items == null ? null : Arrays.copyOf(items, items.length);
    }

    public static char[] copyArray(char[] items) {
        return items == null ? null : Arrays.copyOf(items, items.length);
    }

    public static int[] toIntArray(Integer[] items) {
        if (items == null) return null;
        int[] copy = new int[items.length];
        for (int i = 0; i < items.length; i++) copy[i] = items[i];
        return copy;
    }

    public static long[] toLongArray(Long[] items) {
        if (items == null) return null;
        long[] copy = new long[items.length];
        for (int i = 0; i < items.length; i++) copy[i] = items[i];
        return copy;
    }

    public static double[] toDoubleArray(Double[] items) {
        if (items == null) return null;
        double[] copy = new double[items.length];
        for (int i = 0; i < items.length; i++) copy[i] = items[i];
        return copy;
    }

    public static float[] toFloatArray(Float[] items) {
        if (items == null) return null;
        float[] copy = new float[items.length];
        for (int i = 0; i < items.length; i++) copy[i] = items[i];
        return copy;
    }

    public static boolean[] toBooleanArray(Boolean[] items) {
        if (items == null) return null;
        boolean[] copy = new boolean[items.length];
        for (int i = 0; i < items.length; i++) copy[i] = items[i];
        return copy;
    }

    public static byte[] toByteArray(Byte[] items) {
        if (items == null) return null;
        byte[] copy = new byte[items.length];
        for (int i = 0; i < items.length; i++) copy[i] = items[i];
        return copy;
    }

    public static short[] toShortArray(Short[] items) {
        if (items == null) return null;
        short[] copy = new short[items.length];
        for (int i = 0; i < items.length; i++) copy[i] = items[i];
        return copy;
    }

    public static char[] toCharArray(Character[] items) {
        if (items == null) return null;
        char[] copy = new char[items.length];
        for (int i = 0; i < items.length; i++) copy[i] = items[i];
        return copy;
    }
    /** Mirrors C# Array.Sort(double[] keys, int[] items): sorts keys ascending, reorders items to match. */
    public static void sortParallel(double[] keys, int[] items) {
        int n = keys.length;
        Integer[] indices = new Integer[n];
        for (int i = 0; i < n; i++) indices[i] = i;
        Arrays.sort(indices, (a, b) -> Double.compare(keys[a], keys[b]));
        double[] sk = new double[n]; int[] sv = new int[n];
        for (int i = 0; i < n; i++) { sk[i] = keys[indices[i]]; sv[i] = items[indices[i]]; }
        System.arraycopy(sk, 0, keys, 0, n); System.arraycopy(sv, 0, items, 0, n);
    }
    /** Mirrors C# Array.Sort(double[] keys, T[] items): sorts keys ascending, reorders items to match. */
    @SuppressWarnings("unchecked")
    public static <T> void sortParallel(double[] keys, T[] items) {
        int n = keys.length;
        Integer[] indices = new Integer[n];
        for (int i = 0; i < n; i++) indices[i] = i;
        Arrays.sort(indices, (a, b) -> Double.compare(keys[a], keys[b]));
        double[] sk = new double[n]; T[] sv = (T[]) new Object[n];
        for (int i = 0; i < n; i++) { sk[i] = keys[indices[i]]; sv[i] = items[indices[i]]; }
        System.arraycopy(sk, 0, keys, 0, n); System.arraycopy(sv, 0, items, 0, n);
    }
}
