package io.github.ningpp.compat;

/** Replacement for System.BadImageFormatException (generated by CSharpToJava converter). */
public class BadImageFormatException extends SystemException {
    public BadImageFormatException() { super(); }
    public BadImageFormatException(String message) { super(message); }
    public BadImageFormatException(String message, Throwable cause) { super(message, cause); }
}
