package io.github.ningpp.compat;

/** Replacement for System.Threading.BarrierPostPhaseException (generated by CSharpToJava converter). */
public class BarrierPostPhaseException extends RuntimeException {
    public BarrierPostPhaseException() { super(); }
    public BarrierPostPhaseException(String message) { super(message); }
    public BarrierPostPhaseException(String message, Throwable cause) { super(message, cause); }
}
