package io.github.ningpp.compat;

/** Replacement for System.Threading.BarrierPostPhaseException (generated by CSharpToJava converter). */
public class BarrierPostPhaseException extends RuntimeException {
    private int hresult;
    public BarrierPostPhaseException() { super(); }
    public BarrierPostPhaseException(String message) { super(message); }
    public BarrierPostPhaseException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
