package io.github.ningpp.compat;

/** Replacement for System.Diagnostics.BooleanSwitch (generated by CSharpToJava converter). */
public class BooleanSwitch {
    private final String displayName;
    private final String description;
    private boolean enabled;

    public BooleanSwitch(String displayName, String description) {
        this.displayName = displayName;
        this.description = description;
    }

    public boolean getEnabled() { return enabled; }
    public void setEnabled(boolean value) { this.enabled = value; }
    public String getDisplayName() { return displayName; }
    public String getDescription() { return description; }
}
