package io.github.ningpp.compat;

/** Holder for ref/out boolean parameters (generated by CSharpToJava converter). */
public final class BoolHolder {
    public boolean value;
    public BoolHolder() { this.value = false; }
    public BoolHolder(boolean value) { this.value = value; }
}
