package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.BreakException (generated by CSharpToJava converter). */
public class BreakException extends RuntimeException {
    public BreakException() { super(); }
    public BreakException(String message) { super(message); }
    public BreakException(String message, Throwable cause) { super(message, cause); }
}
