package io.github.ningpp.compat;

/** Holder for ref/out byte parameters (generated by CSharpToJava converter). */
public final class ByteHolder {
    public byte value;
    public ByteHolder() { this.value = (byte)0; }
    public ByteHolder(byte value) { this.value = value; }
}
