package io.github.ningpp.compat;

/** Replacement for System.CannotUnloadAppDomainException (generated by CSharpToJava converter). */
public class CannotUnloadAppDomainException extends SystemException {
    public CannotUnloadAppDomainException() { super(); }
    public CannotUnloadAppDomainException(String message) { super(message); }
    public CannotUnloadAppDomainException(String message, Throwable cause) { super(message, cause); }
}
