package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.CertificateNotFoundException (generated by CSharpToJava converter). */
public class CertificateNotFoundException extends CertificateProviderItemNotFoundException {
    public CertificateNotFoundException() { super(); }
    public CertificateNotFoundException(String message) { super(message); }
    public CertificateNotFoundException(String message, Throwable cause) { super(message, cause); }
}
