package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.CertificateProviderItemNotFoundException (generated by CSharpToJava converter). */
public class CertificateProviderItemNotFoundException extends SystemException {
    public CertificateProviderItemNotFoundException() { super(); }
    public CertificateProviderItemNotFoundException(String message) { super(message); }
    public CertificateProviderItemNotFoundException(String message, Throwable cause) { super(message, cause); }
}
