package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.CertificateStoreNotFoundException (generated by CSharpToJava converter). */
public class CertificateStoreNotFoundException extends CertificateProviderItemNotFoundException {
    public CertificateStoreNotFoundException() { super(); }
    public CertificateStoreNotFoundException(String message) { super(message); }
    public CertificateStoreNotFoundException(String message, Throwable cause) { super(message, cause); }
}
