package io.github.ningpp.compat;

/** Holder for ref/out char parameters (generated by CSharpToJava converter). */
public final class CharHolder {
    public char value;
    public CharHolder() { this.value = '\0'; }
    public CharHolder(char value) { this.value = value; }
}
