package io.github.ningpp.compat;

/** Replacement for System.ComponentModel.Design.CheckoutException (generated by CSharpToJava converter). */
public class CheckoutException extends ExternalException {
    public CheckoutException() { super(); }
    public CheckoutException(String message) { super(message); }
    public CheckoutException(String message, Throwable cause) { super(message, cause); }
}
