package io.github.ningpp.compat;

/** Replacement for Microsoft.Management.Infrastructure.CimException (generated by CSharpToJava converter). */
public class CimException extends RuntimeException {
    public CimException() { super(); }
    public CimException(String message) { super(message); }
    public CimException(String message, Throwable cause) { super(message, cause); }
}
