package io.github.ningpp.compat;

/** Replacement for Microsoft.Management.Infrastructure.CimException (generated by CSharpToJava converter). */
public class CimException extends RuntimeException {
    private int hresult;
    public CimException() { super(); }
    public CimException(String message) { super(message); }
    public CimException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
