package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Cmdletization.Cim.CimJobException (generated by CSharpToJava converter). */
public class CimJobException extends SystemException {
    public CimJobException() { super(); }
    public CimJobException(String message) { super(message); }
    public CimJobException(String message, Throwable cause) { super(message, cause); }
}
