package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.CmdletProviderInvocationException (generated by CSharpToJava converter). */
public class CmdletProviderInvocationException extends CmdletInvocationException {
    public CmdletProviderInvocationException() { super(); }
    public CmdletProviderInvocationException(String message) { super(message); }
    public CmdletProviderInvocationException(String message, Throwable cause) { super(message, cause); }
}
