package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.CmdletInvocationException (generated by CSharpToJava converter). */
public class CmdletInvocationException extends RuntimeException {
    public CmdletInvocationException() { super(); }
    public CmdletInvocationException(String message) { super(message); }
    public CmdletInvocationException(String message, Throwable cause) { super(message, cause); }
}
