package io.github.ningpp.compat;

/** Replacement for System.Runtime.InteropServices.COMException (generated by CSharpToJava converter). */
public class COMException extends ExternalException {
    public COMException() { super(); }
    public COMException(String message) { super(message); }
    public COMException(String message, Throwable cause) { super(message, cause); }
}
