package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.CommandNotFoundException (generated by CSharpToJava converter). */
public class CommandNotFoundException extends RuntimeException {
    private int hresult;
    public CommandNotFoundException() { super(); }
    public CommandNotFoundException(String message) { super(message); }
    public CommandNotFoundException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
