package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.CommandNotFoundException (generated by CSharpToJava converter). */
public class CommandNotFoundException extends RuntimeException {
    public CommandNotFoundException() { super(); }
    public CommandNotFoundException(String message) { super(message); }
    public CommandNotFoundException(String message, Throwable cause) { super(message, cause); }
}
