package io.github.ningpp.compat;

/** Replacement for System.Configuration.ConfigurationException (generated by CSharpToJava converter). */
public class ConfigurationException extends SystemException {
    public ConfigurationException() { super(); }
    public ConfigurationException(String message) { super(message); }
    public ConfigurationException(String message, Throwable cause) { super(message, cause); }
}
