package io.github.ningpp.compat;

/** Replacement for System.Configuration.ConfigurationErrorsException (generated by CSharpToJava converter). */
public class ConfigurationErrorsException extends ConfigurationException {
    public ConfigurationErrorsException() { super(); }
    public ConfigurationErrorsException(String message) { super(message); }
    public ConfigurationErrorsException(String message, Throwable cause) { super(message, cause); }
}
