package io.github.ningpp.compat;

/** Replacement for System.Data.ConstraintException (generated by CSharpToJava converter). */
public class ConstraintException extends DataException {
    public ConstraintException() { super(); }
    public ConstraintException(String message) { super(message); }
    public ConstraintException(String message, Throwable cause) { super(message, cause); }
}
