package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ContinueException (generated by CSharpToJava converter). */
public class ContinueException extends RuntimeException {
    private int hresult;
    public ContinueException() { super(); }
    public ContinueException(String message) { super(message); }
    public ContinueException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
