package io.github.ningpp.compat;

/** Replacement for System.ContextMarshalException (generated by CSharpToJava converter). */
public class ContextMarshalException extends SystemException {
    public ContextMarshalException() { super(); }
    public ContextMarshalException(String message) { super(message); }
    public ContextMarshalException(String message, Throwable cause) { super(message, cause); }
}
