package io.github.ningpp.compat;

/** Replacement for System.Net.CookieException (generated by CSharpToJava converter). */
public class CookieException extends IllegalArgumentException {
    public CookieException() { super(); }
    public CookieException(String message) { super(message); }
    public CookieException(String message, Throwable cause) { super(message, cause); }
}
