package io.github.ningpp.compat;

/** Replacement for System.Net.CookieException (generated by CSharpToJava converter). */
public class CookieException extends IllegalArgumentException {
    private int hresult;
    public CookieException() { super(); }
    public CookieException(String message) { super(message); }
    public CookieException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
