package io.github.ningpp.compat;

/** Replacement for System.Security.Cryptography.CryptographicUnexpectedOperationException (generated by CSharpToJava converter). */
public class CryptographicUnexpectedOperationException extends CryptographicException {
    public CryptographicUnexpectedOperationException() { super(); }
    public CryptographicUnexpectedOperationException(String message) { super(message); }
    public CryptographicUnexpectedOperationException(String message, Throwable cause) { super(message, cause); }
}
