package io.github.ningpp.compat;

/** Replacement for System.Security.Cryptography.CryptographicException (generated by CSharpToJava converter). */
public class CryptographicException extends SystemException {
    public CryptographicException() { super(); }
    public CryptographicException(String message) { super(message); }
    public CryptographicException(String message, Throwable cause) { super(message, cause); }
}
