package io.github.ningpp.compat;

import java.util.Locale;

/** Stub for System.Globalization.CultureInfo (generated by CSharpToJava converter). */
public class CultureInfo implements IFormatProvider {
    private final Locale locale;

    public CultureInfo(String name) {
        this.locale = Locale.forLanguageTag(name.replace('_', '-'));
    }

    public static CultureInfo getCurrentCulture() {
        return new CultureInfo(Locale.getDefault().toLanguageTag());
    }
    public static void setCurrentCulture(CultureInfo cultureInfo) {
        // no-op: JVM locale is JVM-wide setting, not thread-local
    }
    public static CultureInfo getCurrentUICulture() {
        return new CultureInfo(Locale.getDefault().toLanguageTag());
    }
    public static void setCurrentUICulture(CultureInfo cultureInfo) {
        // no-op: JVM locale is JVM-wide setting, not thread-local
    }
    public static CultureInfo getInvariantCulture() {
        return new CultureInfo("en-US");
    }
    public Locale toLocale() { return locale; }
    public Locale getLocale() { return locale; }

    public Object getFormat(Class<?> formatType) { return this; }

    public static CultureInfo fromLocale(Locale locale) {
        return new CultureInfo(locale.toLanguageTag());
    }

    @Override public String toString() { return locale.toString(); }
}
