package io.github.ningpp.compat;

/** Replacement for System.Globalization.CultureNotFoundException (generated by CSharpToJava converter). */
public class CultureNotFoundException extends IllegalArgumentException {
    private int hresult;
    public CultureNotFoundException() { super(); }
    public CultureNotFoundException(String message) { super(message); }
    public CultureNotFoundException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
