package io.github.ningpp.compat;

/** Replacement for System.Reflection.CustomAttributeFormatException (generated by CSharpToJava converter). */
public class CustomAttributeFormatException extends IllegalArgumentException {
    private int hresult;
    public CustomAttributeFormatException() { super(); }
    public CustomAttributeFormatException(String message) { super(message); }
    public CustomAttributeFormatException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
