package io.github.ningpp.compat;

/** Replacement for System.DataMisalignedException (generated by CSharpToJava converter). */
public class DataMisalignedException extends SystemException {
    public DataMisalignedException() { super(); }
    public DataMisalignedException(String message) { super(message); }
    public DataMisalignedException(String message, Throwable cause) { super(message, cause); }
}
