package io.github.ningpp.compat;

/** Replacement for System.Data.DataException (generated by CSharpToJava converter). */
public class DataException extends SystemException {
    public DataException() { super(); }
    public DataException(String message) { super(message); }
    public DataException(String message, Throwable cause) { super(message, cause); }
}
