package io.github.ningpp.compat;

/** Replacement for System.Data.DBConcurrencyException (generated by CSharpToJava converter). */
public class DBConcurrencyException extends SystemException {
    public DBConcurrencyException() { super(); }
    public DBConcurrencyException(String message) { super(message); }
    public DBConcurrencyException(String message, Throwable cause) { super(message, cause); }
}
