package io.github.ningpp.compat;

/** Replacement for System.Text.Decoder (generated by CSharpToJava converter). */
public abstract class Decoder {
    public abstract int getCharCount(byte[] bytes, int index, int count);
    public abstract int getChars(byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex);
    public abstract void convert(byte[] bytes, int byteIndex, int byteCount,
                                  char[] chars, int charIndex, int charCount,
                                  boolean flush, IntHolder bytesUsed, IntHolder charsUsed, BoolHolder completed);
}
