package io.github.ningpp.compat;

/** Replacement for System.Text.DecoderFallbackException (generated by CSharpToJava converter). */
public class DecoderFallbackException extends IllegalArgumentException {
    private int hresult;
    public DecoderFallbackException() { super(); }
    public DecoderFallbackException(String message) { super(message); }
    public DecoderFallbackException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
