package io.github.ningpp.compat;

/** Replacement for System.DirectoryServices.DirectoryServicesCOMException (generated by CSharpToJava converter). */
public class DirectoryServicesCOMException extends COMException {
    public DirectoryServicesCOMException() { super(); }
    public DirectoryServicesCOMException(String message) { super(message); }
    public DirectoryServicesCOMException(String message, Throwable cause) { super(message, cause); }
}
