package io.github.ningpp.compat;

/** Replacement for System.DllNotFoundException (generated by CSharpToJava converter). */
public class DllNotFoundException extends ClassNotFoundException {
    public DllNotFoundException() { super(); }
    public DllNotFoundException(String message) { super(message); }
    public DllNotFoundException(String message, Throwable cause) { super(message, cause); }
}
