package io.github.ningpp.compat;

import java.io.IOException;

/** Replacement for System.IO.DriveNotFoundException (generated by CSharpToJava converter). */
public class DriveNotFoundException extends IOException {
    public DriveNotFoundException() { super(); }
    public DriveNotFoundException(String message) { super(message); }
    public DriveNotFoundException(String message, Throwable cause) { super(message, cause); }
}
