package io.github.ningpp.compat;

/** Replacement for System.Data.DuplicateNameException (generated by CSharpToJava converter). */
public class DuplicateNameException extends DataException {
    public DuplicateNameException() { super(); }
    public DuplicateNameException(String message) { super(message); }
    public DuplicateNameException(String message, Throwable cause) { super(message, cause); }
}
