package io.github.ningpp.compat;

/** Replacement for System.DuplicateWaitObjectException (generated by CSharpToJava converter). */
public class DuplicateWaitObjectException extends IllegalArgumentException {
    private int hresult;
    public DuplicateWaitObjectException() { super(); }
    public DuplicateWaitObjectException(String message) { super(message); }
    public DuplicateWaitObjectException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
