package io.github.ningpp.compat;

/** Replacement for System.Text.Encoder (generated by CSharpToJava converter). */
public abstract class Encoder {
    public abstract int getByteCount(char[] chars, int index, int count, boolean flush);
    public abstract int getBytes(char[] chars, int charIndex, int charCount, byte[] bytes, int byteIndex, boolean flush);
    public abstract void convert(char[] chars, int charIndex, int charCount,
                                  byte[] bytes, int byteIndex, int byteCount,
                                  boolean flush, IntHolder charsUsed, IntHolder bytesUsed, BoolHolder completed);
}
