package io.github.ningpp.compat;

/** Replacement for System.Text.EncoderFallbackException (generated by CSharpToJava converter). */
public class EncoderFallbackException extends IllegalArgumentException {
    private int hresult;
    public EncoderFallbackException() { super(); }
    public EncoderFallbackException(String message) { super(message); }
    public EncoderFallbackException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
