package io.github.ningpp.compat;

/** Replacement for System.Text.EncoderExceptionFallback (generated by CSharpToJava converter). */
public class EncoderExceptionFallback extends EncoderFallback {
    @Override
    public EncoderFallbackBuffer createFallbackBuffer() {
        return new EncoderExceptionFallbackBuffer();
    }

    @Override
    public int getMaxCharCount() {
        return 0;
    }
}

class EncoderExceptionFallbackBuffer extends EncoderFallbackBuffer {
    @Override
    public boolean fallback(char charUnknown, int index) {
        throw new IllegalArgumentException("Unable to encode character \\u" +
            Integer.toHexString(charUnknown) + " at index " + index);
    }

    @Override
    public boolean fallback(char charUnknownHigh, char charUnknownLow, int index) {
        throw new IllegalArgumentException("Unable to encode surrogate pair at index " + index);
    }

    @Override
    public char getNextChar() { return '\0'; }

    @Override
    public boolean movePrevious() { return false; }

    @Override
    public int getRemaining() { return 0; }
}
