package io.github.ningpp.compat;

/** Replacement for System.Text.EncoderFallbackBuffer (generated by CSharpToJava converter). */
public abstract class EncoderFallbackBuffer {
    public abstract boolean fallback(char charUnknown, int index);
    public abstract boolean fallback(char charUnknownHigh, char charUnknownLow, int index);
    public abstract char getNextChar();
    public abstract boolean movePrevious();
    public abstract int getRemaining();
}
