package io.github.ningpp.compat;

/** Replacement for System.Text.EncoderFallback (generated by CSharpToJava converter). */
public abstract class EncoderFallback {
    public abstract EncoderFallbackBuffer createFallbackBuffer();
    public abstract int getMaxCharCount();
}
