package io.github.ningpp.compat;

/** Replacement for System.EntryPointNotFoundException (generated by CSharpToJava converter). */
public class EntryPointNotFoundException extends ClassNotFoundException {
    public EntryPointNotFoundException() { super(); }
    public EntryPointNotFoundException(String message) { super(message); }
    public EntryPointNotFoundException(String message, Throwable cause) { super(message, cause); }
}
