package io.github.ningpp.compat;

/** Enum parsing utilities (generated by CSharpToJava converter, replacing System.Enum methods). */
public class EnumHelper {
    /** Mirrors Enum.TryParse&lt;T&gt;(name, ignoreCase, out T). Returns false (type-erasure limitation). */
    @SuppressWarnings("unchecked")
    public static <T> boolean tryParse(String name, boolean ignoreCase, ObjectHolder<T> result) {
        return false; // Runtime: use T.valueOf(name) in calling code when enum class is known.
    }
    /** Mirrors Enum.TryParse&lt;T&gt;(name, out T). */
    @SuppressWarnings("unchecked")
    public static <T> boolean tryParse(String name, ObjectHolder<T> result) {
        return false;
    }
    /** Mirrors Enum.Parse(type, name). */
    public static Object parse(Class<?> enumType, String name) {
        try { return Enum.valueOf((Class<Enum>) enumType, name); }
        catch (Exception e) { throw new IllegalArgumentException("No enum constant: " + name, e); }
    }
    /** Mirrors Enum.Parse(type, name, ignoreCase). */
    public static Object parse(Class<?> enumType, String name, boolean ignoreCase) {
        return parse(enumType, name);
    }
    /** Mirrors Enum.GetValues(typeof(T)). */
    @SuppressWarnings("unchecked")
    public static Object[] getValues(Class<?> enumType) {
        return enumType.getEnumConstants();
    }
}
