package io.github.ningpp.compat;

import java.util.Objects;

/**
 * Replacement for System.Collections.Generic.EqualityComparer&lt;T&gt; (generated by CSharpToJava converter).
 * Provides a base class for implementations of the IEqualityComparer&lt;T&gt; generic interface.
 *
 * @param <T> The type of objects to compare.
 */
public abstract class EqualityComparer<T> implements IEqualityComparer<T> {

    /**
     * Returns a default equality comparer for the type specified by the generic argument.
     * This uses Object.equals() and Object.hashCode() as the default implementation.
     *
     * @param <T> The type of objects to compare.
     * @return The default instance of EqualityComparer&lt;T&gt;.
     */
    @SuppressWarnings("unchecked")
    public static <T> EqualityComparer<T> getDefault() {
        return (EqualityComparer<T>) DefaultHolder.DEFAULT;
    }

    /**
     * Determines whether the specified objects are equal.
     *
     * @param x The first object of type T to compare.
     * @param y The second object of type T to compare.
     * @return true if the specified objects are equal; otherwise, false.
     */
    @Override
    public abstract boolean equals(T x, T y);

    /**
     * Returns a hash code for the specified object.
     *
     * @param obj The object for which a hash code is to be returned.
     * @return A hash code for the specified object.
     */
    @Override
    public abstract int hashCode(T obj);

    /**
     * Default implementation that uses Objects.equals() and Objects.hashCode().
     */
    private static class DefaultHolder {
        static final EqualityComparer<Object> DEFAULT = new EqualityComparer<Object>() {
            @Override
            public boolean equals(Object x, Object y) {
                return Objects.equals(x, y);
            }

            @Override
            public int hashCode(Object obj) {
                return Objects.hashCode(obj);
            }
        };
    }
}
