package io.github.ningpp.compat;

/** Replacement for System.Data.EvaluateException (generated by CSharpToJava converter). */
public class EvaluateException extends InvalidExpressionException {
    public EvaluateException() { super(); }
    public EvaluateException(String message) { super(message); }
    public EvaluateException(String message, Throwable cause) { super(message, cause); }
}
