package io.github.ningpp.compat;

/** Replacement for System.Diagnostics.Eventing.Reader.EventLogInvalidDataException (generated by CSharpToJava converter). */
public class EventLogInvalidDataException extends EventLogException {
    public EventLogInvalidDataException() { super(); }
    public EventLogInvalidDataException(String message) { super(message); }
    public EventLogInvalidDataException(String message, Throwable cause) { super(message, cause); }
}
