package io.github.ningpp.compat;

/** Replacement for System.Diagnostics.Eventing.Reader.EventLogException (generated by CSharpToJava converter). */
public class EventLogException extends RuntimeException {
    private int hresult;
    public EventLogException() { super(); }
    public EventLogException(String message) { super(message); }
    public EventLogException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
