package io.github.ningpp.compat;

/** Replacement for System.Diagnostics.Tracing.EventSourceException (generated by CSharpToJava converter). */
public class EventSourceException extends RuntimeException {
    public EventSourceException() { super(); }
    public EventSourceException(String message) { super(message); }
    public EventSourceException(String message, Throwable cause) { super(message, cause); }
}
