package io.github.ningpp.compat;

/** Replacement for System.Diagnostics.Tracing.EventSourceException (generated by CSharpToJava converter). */
public class EventSourceException extends RuntimeException {
    private int hresult;
    public EventSourceException() { super(); }
    public EventSourceException(String message) { super(message); }
    public EventSourceException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
