package io.github.ningpp.compat;

/** Replacement for System.Diagnostics.Eventing.Reader.EventLogNotFoundException (generated by CSharpToJava converter). */
public class EventLogNotFoundException extends EventLogException {
    public EventLogNotFoundException() { super(); }
    public EventLogNotFoundException(String message) { super(message); }
    public EventLogNotFoundException(String message, Throwable cause) { super(message, cause); }
}
