package io.github.ningpp.compat;

/** Replacement for System.Diagnostics.Eventing.Reader.EventLogProviderDisabledException (generated by CSharpToJava converter). */
public class EventLogProviderDisabledException extends EventLogException {
    public EventLogProviderDisabledException() { super(); }
    public EventLogProviderDisabledException(String message) { super(message); }
    public EventLogProviderDisabledException(String message, Throwable cause) { super(message, cause); }
}
