package io.github.ningpp.compat;

/** Replacement for System.ExecutionEngineException (generated by CSharpToJava converter). */
public class ExecutionEngineException extends SystemException {
    public ExecutionEngineException() { super(); }
    public ExecutionEngineException(String message) { super(message); }
    public ExecutionEngineException(String message, Throwable cause) { super(message, cause); }
}
