package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ExitException (generated by CSharpToJava converter). */
public class ExitException extends RuntimeException {
    private int hresult;
    public ExitException() { super(); }
    public ExitException(String message) { super(message); }
    public ExitException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
