package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ExtendedTypeSystemException (generated by CSharpToJava converter). */
public class ExtendedTypeSystemException extends RuntimeException {
    public ExtendedTypeSystemException() { super(); }
    public ExtendedTypeSystemException(String message) { super(message); }
    public ExtendedTypeSystemException(String message, Throwable cause) { super(message, cause); }
}
