package io.github.ningpp.compat;

/** Replacement for System.FieldAccessException (generated by CSharpToJava converter). */
public class FieldAccessException extends IllegalAccessException {
    public FieldAccessException() { super(); }
    public FieldAccessException(String message) { super(message); }
    public FieldAccessException(String message, Throwable cause) { super(message, cause); }
}
