package io.github.ningpp.compat;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PushbackInputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

/** File I/O helpers (generated by CSharpToJava converter, replacing System.IO.File). */
public class FileHelper {
    public static String readAllText(String path) {
        try { return new String(Files.readAllBytes(Paths.get(path)), StandardCharsets.UTF_8); }
        catch (IOException e) { throw new UncheckedIOException(e); }
    }
    public static void writeAllText(String path, String content) {
        try { Files.write(Paths.get(path), content.getBytes(StandardCharsets.UTF_8)); }
        catch (IOException e) { throw new UncheckedIOException(e); }
    }
    public static InputStream openRead(String path) {
        try { return openReadStream(path); }
        catch (FileNotFoundException e) { throw new UncheckedIOException(e); }
    }
    public static TextReader openText(String path) {
        try {
            InputStream fs = openReadStream(path);
            PushbackInputStream pbs = new PushbackInputStream(fs, 3);
            byte[] bom = new byte[3];
            int read = pbs.read(bom);
            if (read == 3 && bom[0] == (byte)0xEF && bom[1] == (byte)0xBB && bom[2] == (byte)0xBF) {
                // BOM detected and skipped — stream is positioned after it
            } else {
                // No BOM — push back whatever bytes we read
                if (read > 0) pbs.unread(bom, 0, read);
            }
            return new TextReader(new InputStreamReader(pbs, StandardCharsets.UTF_8));
        } catch (FileNotFoundException e) { throw new UncheckedIOException(e); }
        catch (IOException e) { throw new UncheckedIOException(e); }
    }

    private static InputStream openReadStream(String path) throws FileNotFoundException {
        try {
            return new FileInputStream(path);
        } catch (FileNotFoundException fileNotFound) {
            InputStream resource = openClasspathResource(path);
            if (resource != null) return resource;
            throw fileNotFound;
        }
    }

    private static InputStream openClasspathResource(String path) {
        if (path == null) return null;
        String resourceName = path.replace('\\', '/');
        while (resourceName.startsWith("/")) {
            resourceName = resourceName.substring(1);
        }

        ClassLoader contextLoader = Thread.currentThread().getContextClassLoader();
        InputStream stream = contextLoader == null ? null : contextLoader.getResourceAsStream(resourceName);
        if (stream != null) return stream;
        return FileHelper.class.getClassLoader().getResourceAsStream(resourceName);
    }

    /** Mirrors File.Open(path, FileMode). */
    public static StreamWrapper open(String path, int fileMode) {
        return open(path, fileMode, FileAccess.ReadWrite);
    }

    /** Mirrors File.Open(path, FileMode, FileAccess). */
    public static StreamWrapper open(String path, int fileMode, int fileAccess) {
        try {
            if (fileMode == FileMode.CreateNew) {
                File file = new File(path);
                if (!file.createNewFile()) {
                    throw new UncheckedIOException(new IOException("File already exists: " + path));
                }
                return StreamWrapper.of(new FileOutputStream(file), path);
            }
            if (fileMode == FileMode.Create || fileMode == FileMode.Truncate) {
                return StreamWrapper.of(new FileOutputStream(path, false), path);
            }
            if (fileMode == FileMode.Append) {
                return StreamWrapper.of(new FileOutputStream(path, true), path);
            }
            if (fileAccess == FileAccess.Write) {
                return StreamWrapper.of(new FileOutputStream(path, fileMode == FileMode.OpenOrCreate), path);
            }
            if (fileMode == FileMode.OpenOrCreate) {
                File file = new File(path);
                if (file.exists()) {
                    return StreamWrapper.of(new FileInputStream(file), path);
                }
                return StreamWrapper.of(new FileOutputStream(file), path);
            }
            return StreamWrapper.of(new FileInputStream(path), path);
        } catch (IOException e) { throw new UncheckedIOException(e); }
    }
    /** Mirrors File.Open(path, FileMode, FileAccess, FileShare). */
    public static StreamWrapper open(String path, int fileMode, int fileAccess, int fileShare) {
        return open(path, fileMode, fileAccess);
    }

    /** Mirrors File.Open(path, FileMode, FileAccess, FileShare, bufferSize). */
    public static StreamWrapper open(String path, int fileMode, int fileAccess, int fileShare,
                                      int bufferSize) {
        return open(path, fileMode, fileAccess);
    }

    /** Mirrors File.Open(path, FileMode, FileAccess, FileShare, bufferSize, useAsync). */
    public static StreamWrapper open(String path, int fileMode, int fileAccess, int fileShare,
                                      int bufferSize, boolean useAsync) {
        return open(path, fileMode, fileAccess);
    }

    /** Mirrors File.Create(path). */
    public static OutputStream create(String path) {
        try { return new FileOutputStream(path); }
        catch (FileNotFoundException e) { throw new UncheckedIOException(e); }
    }
    public static boolean exists(String path) { return new File(path).exists(); }
    public static void delete(String path) { new File(path).delete(); }
}
