package io.github.ningpp.compat;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;

/** File I/O helpers (generated by CSharpToJava converter, replacing System.IO.File). */
public class FileHelper {
    public static String readAllText(String path) {
        try { return new String(Files.readAllBytes(Paths.get(path)), StandardCharsets.UTF_8); }
        catch (IOException e) { throw new UncheckedIOException(e); }
    }
    public static void writeAllText(String path, String content) {
        try { Files.write(Paths.get(path), content.getBytes(StandardCharsets.UTF_8)); }
        catch (IOException e) { throw new UncheckedIOException(e); }
    }
    public static InputStream openRead(String path) {
        try { return new FileInputStream(path); }
        catch (FileNotFoundException e) { throw new UncheckedIOException(e); }
    }
    public static TextReader openText(String path) {
        try { return new TextReader(new InputStreamReader(new FileInputStream(path), StandardCharsets.UTF_8)); }
        catch (FileNotFoundException e) { throw new UncheckedIOException(e); }
    }
    /** Mirrors File.Open(path, FileMode). */
    public static StreamWrapper open(String path, int fileMode) {
        return open(path, fileMode, FileAccess.ReadWrite);
    }

    /** Mirrors File.Open(path, FileMode, FileAccess). */
    public static StreamWrapper open(String path, int fileMode, int fileAccess) {
        try {
            if (fileMode == FileMode.CreateNew) {
                File file = new File(path);
                if (!file.createNewFile()) {
                    throw new UncheckedIOException(new IOException("File already exists: " + path));
                }
                return StreamWrapper.of(new FileOutputStream(file), path);
            }
            if (fileMode == FileMode.Create || fileMode == FileMode.Truncate) {
                return StreamWrapper.of(new FileOutputStream(path, false), path);
            }
            if (fileMode == FileMode.Append) {
                return StreamWrapper.of(new FileOutputStream(path, true), path);
            }
            if (fileAccess == FileAccess.Write) {
                return StreamWrapper.of(new FileOutputStream(path, fileMode == FileMode.OpenOrCreate), path);
            }
            if (fileMode == FileMode.OpenOrCreate) {
                File file = new File(path);
                if (file.exists()) {
                    return StreamWrapper.of(new FileInputStream(file), path);
                }
                return StreamWrapper.of(new FileOutputStream(file), path);
            }
            return StreamWrapper.of(new FileInputStream(path), path);
        } catch (IOException e) { throw new UncheckedIOException(e); }
    }
    /** Mirrors File.Create(path). */
    public static OutputStream create(String path) {
        try { return new FileOutputStream(path); }
        catch (FileNotFoundException e) { throw new UncheckedIOException(e); }
    }
    public static boolean exists(String path) { return new File(path).exists(); }
    public static void delete(String path) { new File(path).delete(); }
}
