package io.github.ningpp.compat;

/** Replacement for System.IO.FileMode (generated by CSharpToJava converter). */
public class FileMode {
    public static final int CreateNew  = 1;
    public static final int Create     = 2;
    public static final int Open       = 3;
    public static final int OpenOrCreate = 4;
    public static final int Truncate   = 5;
    public static final int Append     = 6;

    public static int getCreateNew()    { return CreateNew; }
    public static int getCreate()       { return Create; }
    public static int getOpen()         { return Open; }
    public static int getOpenOrCreate() { return OpenOrCreate; }
    public static int getTruncate()     { return Truncate; }
    public static int getAppend()       { return Append; }
}
