package io.github.ningpp.compat;

/** Replacement for System.IO.FileLoadException (generated by CSharpToJava converter). */
public class FileLoadException extends IOException {
    public FileLoadException() { super(); }
    public FileLoadException(String message) { super(message); }
    public FileLoadException(String message, Throwable cause) { super(message, cause); }
}
