package io.github.ningpp.compat;

/** Replacement for System.IO.FileShare (generated by CSharpToJava converter). */
public class FileShare {
    public static final int None        = 0;
    public static final int Read        = 1;
    public static final int Write       = 2;
    public static final int ReadWrite   = 3;
    public static final int Delete      = 4;
    public static final int Inheritable = 16;

    public static int getNone()        { return None; }
    public static int getRead()        { return Read; }
    public static int getWrite()       { return Write; }
    public static int getReadWrite()   { return ReadWrite; }
    public static int getDelete()      { return Delete; }
    public static int getInheritable() { return Inheritable; }
}
