package io.github.ningpp.compat;

/** Holder for ref/out float parameters (generated by CSharpToJava converter). */
public final class FloatHolder {
    public float value;
    public FloatHolder() { this.value = 0.0f; }
    public FloatHolder(float value) { this.value = value; }
}
