package io.github.ningpp.compat;

/** Replacement for System.DirectoryServices.ActiveDirectory.ForestTrustCollisionException (generated by CSharpToJava converter). */
public class ForestTrustCollisionException extends ActiveDirectoryOperationException {
    public ForestTrustCollisionException() { super(); }
    public ForestTrustCollisionException(String message) { super(message); }
    public ForestTrustCollisionException(String message, Throwable cause) { super(message, cause); }
}
