package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.FormatTableLoadException (generated by CSharpToJava converter). */
public class FormatTableLoadException extends RuntimeException {
    public FormatTableLoadException() { super(); }
    public FormatTableLoadException(String message) { super(message); }
    public FormatTableLoadException(String message, Throwable cause) { super(message, cause); }
}
