package io.github.ningpp.compat;

/** Replacement for System.FormatException (generated by CSharpToJava converter). */
public class FormatException extends IllegalArgumentException {
    public FormatException() { super(); }
    public FormatException(String message) { super(message); }
    public FormatException(String message, Throwable cause) { super(message, cause); }
}
