package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.FormatTableLoadException (generated by CSharpToJava converter). */
public class FormatTableLoadException extends RuntimeException {
    private int hresult;
    public FormatTableLoadException() { super(); }
    public FormatTableLoadException(String message) { super(message); }
    public FormatTableLoadException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
