package io.github.ningpp.compat;

/** Replacement for System.FormatException (generated by CSharpToJava converter). */
public class FormatException extends IllegalArgumentException {
    private int hresult;
    public FormatException() { super(); }
    public FormatException(String message) { super(message); }
    public FormatException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
