package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.GetValueException (generated by CSharpToJava converter). */
public class GetValueException extends ExtendedTypeSystemException {
    public GetValueException() { super(); }
    public GetValueException(String message) { super(message); }
    public GetValueException(String message, Throwable cause) { super(message, cause); }
}
