package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.HaltCommandException (generated by CSharpToJava converter). */
public class HaltCommandException extends SystemException {
    public HaltCommandException() { super(); }
    public HaltCommandException(String message) { super(message); }
    public HaltCommandException(String message, Throwable cause) { super(message, cause); }
}
