package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.HelpNotFoundException (generated by CSharpToJava converter). */
public class HelpNotFoundException extends SystemException {
    public HelpNotFoundException() { super(); }
    public HelpNotFoundException(String message) { super(message); }
    public HelpNotFoundException(String message, Throwable cause) { super(message, cause); }
}
