package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.HelpCategoryInvalidException (generated by CSharpToJava converter). */
public class HelpCategoryInvalidException extends IllegalArgumentException {
    private int hresult;
    public HelpCategoryInvalidException() { super(); }
    public HelpCategoryInvalidException(String message) { super(message); }
    public HelpCategoryInvalidException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
