package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.HelpCategoryInvalidException (generated by CSharpToJava converter). */
public class HelpCategoryInvalidException extends IllegalArgumentException {
    public HelpCategoryInvalidException() { super(); }
    public HelpCategoryInvalidException(String message) { super(message); }
    public HelpCategoryInvalidException(String message, Throwable cause) { super(message, cause); }
}
