package io.github.ningpp.compat;

/** Replacement for System.Security.HostProtectionException (generated by CSharpToJava converter). */
public class HostProtectionException extends SystemException {
    public HostProtectionException() { super(); }
    public HostProtectionException(String message) { super(message); }
    public HostProtectionException(String message, Throwable cause) { super(message, cause); }
}
