package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Host.HostException (generated by CSharpToJava converter). */
public class HostException extends RuntimeException {
    public HostException() { super(); }
    public HostException(String message) { super(message); }
    public HostException(String message, Throwable cause) { super(message, cause); }
}
