package io.github.ningpp.compat;

/** Replacement for System.Net.HttpListenerException (generated by CSharpToJava converter). */
public class HttpListenerException extends RuntimeException {
    public HttpListenerException() { super(); }
    public HttpListenerException(String message) { super(message); }
    public HttpListenerException(String message, Throwable cause) { super(message, cause); }
}
