package io.github.ningpp.compat;

/** Replacement for System.Net.HttpListenerException (generated by CSharpToJava converter). */
public class HttpListenerException extends RuntimeException {
    private int hresult;
    public HttpListenerException() { super(); }
    public HttpListenerException(String message) { super(message); }
    public HttpListenerException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
