package io.github.ningpp.compat;

/** Replacement for System.Security.Principal.IdentityNotMappedException (generated by CSharpToJava converter). */
public class IdentityNotMappedException extends SystemException {
    public IdentityNotMappedException() { super(); }
    public IdentityNotMappedException(String message) { super(message); }
    public IdentityNotMappedException(String message, Throwable cause) { super(message, cause); }
}
