package io.github.ningpp.compat;

/** Replacement for System.Collections.Generic.IEqualityComparer&lt;T&gt; (generated by CSharpToJava converter). */
public interface IEqualityComparer<T> {
    boolean equals(T x, T y);
    int hashCode(T obj);
}
