package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.IncompleteParseException (generated by CSharpToJava converter). */
public class IncompleteParseException extends ParseException {
    public IncompleteParseException() { super(); }
    public IncompleteParseException(String message) { super(message); }
    public IncompleteParseException(String message, Throwable cause) { super(message, cause); }
}
