package io.github.ningpp.compat;

/** Replacement for System.Data.InRowChangingEventException (generated by CSharpToJava converter). */
public class InRowChangingEventException extends DataException {
    public InRowChangingEventException() { super(); }
    public InRowChangingEventException(String message) { super(message); }
    public InRowChangingEventException(String message, Throwable cause) { super(message, cause); }
}
