package io.github.ningpp.compat;

/** Replacement for System.Management.Instrumentation.InstrumentationException (generated by CSharpToJava converter). */
public class InstrumentationException extends InstrumentationBaseException {
    public InstrumentationException() { super(); }
    public InstrumentationException(String message) { super(message); }
    public InstrumentationException(String message, Throwable cause) { super(message, cause); }
}
