package io.github.ningpp.compat;

/** Replacement for System.Configuration.Install.InstallException (generated by CSharpToJava converter). */
public class InstallException extends SystemException {
    public InstallException() { super(); }
    public InstallException(String message) { super(message); }
    public InstallException(String message, Throwable cause) { super(message, cause); }
}
