package io.github.ningpp.compat;

/** Replacement for System.Management.Instrumentation.InstrumentationBaseException (generated by CSharpToJava converter). */
public class InstrumentationBaseException extends RuntimeException {
    private int hresult;
    public InstrumentationBaseException() { super(); }
    public InstrumentationBaseException(String message) { super(message); }
    public InstrumentationBaseException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
