package io.github.ningpp.compat;

/** Replacement for System.Management.Instrumentation.InstanceNotFoundException (generated by CSharpToJava converter). */
public class InstanceNotFoundException extends InstrumentationException {
    public InstanceNotFoundException() { super(); }
    public InstanceNotFoundException(String message) { super(message); }
    public InstanceNotFoundException(String message, Throwable cause) { super(message, cause); }
}
