package io.github.ningpp.compat;

/** Replacement for System.InsufficientExecutionStackException (generated by CSharpToJava converter). */
public class InsufficientExecutionStackException extends SystemException {
    public InsufficientExecutionStackException() { super(); }
    public InsufficientExecutionStackException(String message) { super(message); }
    public InsufficientExecutionStackException(String message, Throwable cause) { super(message, cause); }
}
