package io.github.ningpp.compat;

/** Replacement for System.InsufficientMemoryException (generated by CSharpToJava converter). */
public class InsufficientMemoryException extends RuntimeException {
    private int hresult;
    public InsufficientMemoryException() { super(); }
    public InsufficientMemoryException(String message) { super(message); }
    public InsufficientMemoryException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
