package io.github.ningpp.compat;

/** Replacement for System.IO.InternalBufferOverflowException (generated by CSharpToJava converter). */
public class InternalBufferOverflowException extends SystemException {
    public InternalBufferOverflowException() { super(); }
    public InternalBufferOverflowException(String message) { super(message); }
    public InternalBufferOverflowException(String message, Throwable cause) { super(message, cause); }
}
