package io.github.ningpp.compat;

/** Replacement for System.Data.InvalidConstraintException (generated by CSharpToJava converter). */
public class InvalidConstraintException extends DataException {
    public InvalidConstraintException() { super(); }
    public InvalidConstraintException(String message) { super(message); }
    public InvalidConstraintException(String message, Throwable cause) { super(message, cause); }
}
