package io.github.ningpp.compat;

/** Replacement for System.Reflection.InvalidFilterCriteriaException (generated by CSharpToJava converter). */
public class InvalidFilterCriteriaException extends RuntimeException {
    public InvalidFilterCriteriaException() { super(); }
    public InvalidFilterCriteriaException(String message) { super(message); }
    public InvalidFilterCriteriaException(String message, Throwable cause) { super(message, cause); }
}
