package io.github.ningpp.compat;

/** Replacement for System.Runtime.InteropServices.InvalidComObjectException (generated by CSharpToJava converter). */
public class InvalidComObjectException extends SystemException {
    public InvalidComObjectException() { super(); }
    public InvalidComObjectException(String message) { super(message); }
    public InvalidComObjectException(String message, Throwable cause) { super(message, cause); }
}
