package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.InvalidRunspaceStateException (generated by CSharpToJava converter). */
public class InvalidRunspaceStateException extends SystemException {
    public InvalidRunspaceStateException() { super(); }
    public InvalidRunspaceStateException(String message) { super(message); }
    public InvalidRunspaceStateException(String message, Throwable cause) { super(message, cause); }
}
