package io.github.ningpp.compat;

/** Replacement for System.Reflection.InvalidFilterCriteriaException (generated by CSharpToJava converter). */
public class InvalidFilterCriteriaException extends RuntimeException {
    private int hresult;
    public InvalidFilterCriteriaException() { super(); }
    public InvalidFilterCriteriaException(String message) { super(message); }
    public InvalidFilterCriteriaException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
