package io.github.ningpp.compat;

/** Replacement for System.IO.InvalidDataException (generated by CSharpToJava converter). */
public class InvalidDataException extends RuntimeException {
    private int hresult;
    public InvalidDataException(String message) { super(message); }
    public InvalidDataException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
