package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.InvalidJobStateException (generated by CSharpToJava converter). */
public class InvalidJobStateException extends SystemException {
    public InvalidJobStateException() { super(); }
    public InvalidJobStateException(String message) { super(message); }
    public InvalidJobStateException(String message, Throwable cause) { super(message, cause); }
}
