package io.github.ningpp.compat;

/** Replacement for System.ComponentModel.InvalidAsynchronousStateException (generated by CSharpToJava converter). */
public class InvalidAsynchronousStateException extends IllegalArgumentException {
    public InvalidAsynchronousStateException() { super(); }
    public InvalidAsynchronousStateException(String message) { super(message); }
    public InvalidAsynchronousStateException(String message, Throwable cause) { super(message, cause); }
}
