package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.InvalidRunspacePoolStateException (generated by CSharpToJava converter). */
public class InvalidRunspacePoolStateException extends SystemException {
    public InvalidRunspacePoolStateException() { super(); }
    public InvalidRunspacePoolStateException(String message) { super(message); }
    public InvalidRunspacePoolStateException(String message, Throwable cause) { super(message, cause); }
}
