package io.github.ningpp.compat;

/** Replacement for System.InvalidProgramException (generated by CSharpToJava converter). */
public class InvalidProgramException extends SystemException {
    public InvalidProgramException() { super(); }
    public InvalidProgramException(String message) { super(message); }
    public InvalidProgramException(String message, Throwable cause) { super(message, cause); }
}
