package io.github.ningpp.compat;

/** Replacement for System.IO.InvalidDataException (generated by CSharpToJava converter). */
public class InvalidDataException extends RuntimeException {
    public InvalidDataException(String message) { super(message); }
    public InvalidDataException(String message, Throwable cause) { super(message, cause); }
}
