package io.github.ningpp.compat;

/** Replacement for System.ComponentModel.InvalidEnumArgumentException (generated by CSharpToJava converter). */
public class InvalidEnumArgumentException extends IllegalArgumentException {
    private int hresult;
    public InvalidEnumArgumentException() { super(); }
    public InvalidEnumArgumentException(String message) { super(message); }
    public InvalidEnumArgumentException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
