package io.github.ningpp.compat;

/** Replacement for System.ComponentModel.InvalidAsynchronousStateException (generated by CSharpToJava converter). */
public class InvalidAsynchronousStateException extends IllegalArgumentException {
    private int hresult;
    public InvalidAsynchronousStateException() { super(); }
    public InvalidAsynchronousStateException(String message) { super(message); }
    public InvalidAsynchronousStateException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
