package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.InvalidPipelineStateException (generated by CSharpToJava converter). */
public class InvalidPipelineStateException extends SystemException {
    public InvalidPipelineStateException() { super(); }
    public InvalidPipelineStateException(String message) { super(message); }
    public InvalidPipelineStateException(String message, Throwable cause) { super(message, cause); }
}
