package io.github.ningpp.compat;

/** Replacement for System.Data.InvalidExpressionException (generated by CSharpToJava converter). */
public class InvalidExpressionException extends DataException {
    public InvalidExpressionException() { super(); }
    public InvalidExpressionException(String message) { super(message); }
    public InvalidExpressionException(String message, Throwable cause) { super(message, cause); }
}
