package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.InvalidPowerShellStateException (generated by CSharpToJava converter). */
public class InvalidPowerShellStateException extends SystemException {
    public InvalidPowerShellStateException() { super(); }
    public InvalidPowerShellStateException(String message) { super(message); }
    public InvalidPowerShellStateException(String message, Throwable cause) { super(message, cause); }
}
