package io.github.ningpp.compat;

/** Replacement for Microsoft.SqlServer.Server.InvalidUdtException (generated by CSharpToJava converter). */
public class InvalidUdtException extends SystemException {
    public InvalidUdtException() { super(); }
    public InvalidUdtException(String message) { super(message); }
    public InvalidUdtException(String message, Throwable cause) { super(message, cause); }
}
