package io.github.ningpp.compat;

/** Replacement for System.InvalidTimeZoneException (generated by CSharpToJava converter). */
public class InvalidTimeZoneException extends RuntimeException {
    private int hresult;
    public InvalidTimeZoneException() { super(); }
    public InvalidTimeZoneException(String message) { super(message); }
    public InvalidTimeZoneException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
