package io.github.ningpp.compat;

/** Replacement for System.InvalidTimeZoneException (generated by CSharpToJava converter). */
public class InvalidTimeZoneException extends RuntimeException {
    public InvalidTimeZoneException() { super(); }
    public InvalidTimeZoneException(String message) { super(message); }
    public InvalidTimeZoneException(String message, Throwable cause) { super(message, cause); }
}
