package io.github.ningpp.compat;

/** Replacement for System.IO.IsolatedStorage.IsolatedStorageException (generated by CSharpToJava converter). */
public class IsolatedStorageException extends RuntimeException {
    private int hresult;
    public IsolatedStorageException() { super(); }
    public IsolatedStorageException(String message) { super(message); }
    public IsolatedStorageException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
