package io.github.ningpp.compat;

/** Replacement for System.IO.IsolatedStorage.IsolatedStorageException (generated by CSharpToJava converter). */
public class IsolatedStorageException extends RuntimeException {
    public IsolatedStorageException() { super(); }
    public IsolatedStorageException(String message) { super(message); }
    public IsolatedStorageException(String message, Throwable cause) { super(message, cause); }
}
