package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ItemNotFoundException (generated by CSharpToJava converter). */
public class ItemNotFoundException extends SessionStateException {
    public ItemNotFoundException() { super(); }
    public ItemNotFoundException(String message) { super(message); }
    public ItemNotFoundException(String message, Throwable cause) { super(message, cause); }
}
