package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.JobFailedException (generated by CSharpToJava converter). */
public class JobFailedException extends SystemException {
    public JobFailedException() { super(); }
    public JobFailedException(String message) { super(message); }
    public JobFailedException(String message, Throwable cause) { super(message, cause); }
}
