package io.github.ningpp.compat;

/** Replacement for System.Text.Json.JsonSerializerOptions (generated by CSharpToJava converter). */
public class JsonSerializerOptions {
    private boolean writeIndented = false;
    public boolean isWriteIndented()          { return writeIndented; }
    public void    setWriteIndented(boolean v) { writeIndented = v; }
}
