package io.github.ningpp.compat;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

/** Replacement for System.Text.Json.JsonSerializer (generated by CSharpToJava converter). */
public class JsonSerializer {
    private static final ObjectMapper MAPPER = new ObjectMapper()
        .configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);

    @SuppressWarnings("unchecked")
    public static <T> String serialize(T value, Object options) {
        try { return MAPPER.writeValueAsString(value); }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    @SuppressWarnings("unchecked")
    public static <T> String serialize(T value) {
        try { return MAPPER.writeValueAsString(value); }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String json, Class<T> clazz) {
        try { return MAPPER.readValue(json, clazz); }
        catch (Exception e) { throw new RuntimeException(e); }
    }

    public static Object deserialize(String json) {
        try { return MAPPER.readValue(json, Object.class); }
        catch (Exception e) { throw new RuntimeException(e); }
    }
}
