package io.github.ningpp.compat;

/** Replacement for System.Collections.Generic.KeyNotFoundException (generated by CSharpToJava converter). */
public class KeyNotFoundException extends SystemException {
    public KeyNotFoundException() { super(); }
    public KeyNotFoundException(String message) { super(message); }
    public KeyNotFoundException(String message, Throwable cause) { super(message, cause); }
}
