package io.github.ningpp.compat;

/** Replacement for System.ComponentModel.LicenseException (generated by CSharpToJava converter). */
public class LicenseException extends SystemException {
    public LicenseException() { super(); }
    public LicenseException(String message) { super(message); }
    public LicenseException(String message, Throwable cause) { super(message, cause); }
}
