package io.github.ningpp.compat;

/**
 * Thin node wrapper that mirrors C# LinkedListNode&lt;T&gt; (generated by CSharpToJava converter).
 * Provides getValue(), getNext(), getPrevious(). Fields are package-private for LinkedListWithNodes.
 */
public class LinkedListNode<T> {
    T value;
    LinkedListNode<T> next;
    LinkedListNode<T> prev;
    LinkedListWithNodes<T> list;

    public LinkedListNode(T value) { this.value = value; }

    public T getValue() { return value; }
    public void setValue(T value) { this.value = value; }
    public LinkedListNode<T> getNext() { return next; }
    public LinkedListNode<T> getPrevious() { return prev; }
    public LinkedListWithNodes<T> getList() { return list; }
}
