package io.github.ningpp.compat;

/** Replacement for System.Threading.LockRecursionException (generated by CSharpToJava converter). */
public class LockRecursionException extends RuntimeException {
    public LockRecursionException() { super(); }
    public LockRecursionException(String message) { super(message); }
    public LockRecursionException(String message, Throwable cause) { super(message, cause); }
}
