package io.github.ningpp.compat;

/** Replacement for System.Threading.LockRecursionException (generated by CSharpToJava converter). */
public class LockRecursionException extends RuntimeException {
    private int hresult;
    public LockRecursionException() { super(); }
    public LockRecursionException(String message) { super(message); }
    public LockRecursionException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
