package io.github.ningpp.compat;

/** Holder for ref/out long parameters (generated by CSharpToJava converter). */
public final class LongHolder {
    public long value;
    public LongHolder() { this.value = 0L; }
    public LongHolder(long value) { this.value = value; }
}
