package io.github.ningpp.compat;

/** Replacement for System.Runtime.InteropServices.MarshalDirectiveException (generated by CSharpToJava converter). */
public class MarshalDirectiveException extends SystemException {
    public MarshalDirectiveException() { super(); }
    public MarshalDirectiveException(String message) { super(message); }
    public MarshalDirectiveException(String message, Throwable cause) { super(message, cause); }
}
