package io.github.ningpp.compat;

/** Numeric TryParse helpers (generated by CSharpToJava converter, replacing System numeric TryParse). */
public class MathHelper {
    public static boolean tryParseDouble(String s, DoubleHolder result) {
        try { result.value = Double.parseDouble(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseFloat(String s, FloatHolder result) {
        try { result.value = Float.parseFloat(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseInt(String s, IntHolder result) {
        try { result.value = Integer.parseInt(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseLong(String s, LongHolder result) {
        try { result.value = Long.parseLong(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseBool(String s, BoolHolder result) {
        if ("true".equalsIgnoreCase(s))  { result.value = true;  return true; }
        if ("false".equalsIgnoreCase(s)) { result.value = false; return true; }
        return false;
    }
}
