package io.github.ningpp.compat;

import java.math.BigInteger;
import java.util.Locale;

/** Numeric TryParse helpers (generated by CSharpToJava converter, replacing System numeric TryParse). */
public class MathHelper {
    public static double parseDouble(String s) {
        return Double.parseDouble(s);
    }

    public static double parseDouble(String s, CultureInfo culture) {
        return parseDouble(s);
    }

    public static double parseDouble(String s, Locale locale) {
        return parseDouble(s);
    }

    public static double parseDouble(String s, int style, CultureInfo culture) {
        return parseDoubleWithStyle(s, style);
    }

    public static double parseDouble(String s, int style, Locale locale) {
        return parseDoubleWithStyle(s, style);
    }

    public static float parseFloat(String s) {
        return Float.parseFloat(s);
    }

    public static float parseFloat(String s, CultureInfo culture) {
        return parseFloat(s);
    }

    public static float parseFloat(String s, Locale locale) {
        return parseFloat(s);
    }

    public static float parseFloat(String s, int style, CultureInfo culture) {
        return (float) parseDoubleWithStyle(s, style);
    }

    public static float parseFloat(String s, int style, Locale locale) {
        return (float) parseDoubleWithStyle(s, style);
    }

    public static int parseInt(String s) {
        return Integer.parseInt(s);
    }

    public static int parseInt(String s, int style) {
        return parseIntWithStyle(s, style);
    }

    public static int parseInt(String s, CultureInfo culture) {
        return parseInt(s);
    }

    public static int parseInt(String s, Locale locale) {
        return parseInt(s);
    }

    public static int parseInt(String s, int style, CultureInfo culture) {
        return parseIntWithStyle(s, style);
    }

    public static int parseInt(String s, int style, Locale locale) {
        return parseIntWithStyle(s, style);
    }

    public static long parseLong(String s) {
        return Long.parseLong(s);
    }

    public static long parseLong(String s, int style) {
        return parseLongWithStyle(s, style);
    }

    public static long parseLong(String s, CultureInfo culture) {
        return parseLong(s);
    }

    public static long parseLong(String s, Locale locale) {
        return parseLong(s);
    }

    public static long parseLong(String s, int style, CultureInfo culture) {
        return parseLongWithStyle(s, style);
    }

    public static long parseLong(String s, int style, Locale locale) {
        return parseLongWithStyle(s, style);
    }

    public static boolean tryParseDouble(String s, DoubleHolder result) {
        try { result.value = Double.parseDouble(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseDouble(String s, int style, CultureInfo culture, DoubleHolder result) {
        try { result.value = parseDoubleWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseFloat(String s, FloatHolder result) {
        try { result.value = Float.parseFloat(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseInt(String s, IntHolder result) {
        try { result.value = Integer.parseInt(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseInt(String s, int style, CultureInfo culture, IntHolder result) {
        try { result.value = parseIntWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseLong(String s, LongHolder result) {
        try { result.value = Long.parseLong(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseLong(String s, int style, CultureInfo culture, LongHolder result) {
        try { result.value = parseLongWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseBool(String s, BoolHolder result) {
        if ("true".equalsIgnoreCase(s))  { result.value = true;  return true; }
        if ("false".equalsIgnoreCase(s)) { result.value = false; return true; }
        return false;
    }

    public static boolean tryParseFloat(String s, int style, CultureInfo culture, FloatHolder result) {
        try { result.value = (float) parseDoubleWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }

    public static boolean tryParseFloat(String s, int style, Locale locale, FloatHolder result) {
        try { result.value = (float) parseDoubleWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }

    public static boolean tryParseByte(String s, ByteHolder result) {
        try { result.value = Byte.parseByte(s.trim()); return true; }
        catch (NumberFormatException e) { return false; }
    }

    public static boolean tryParseByte(String s, int style, CultureInfo culture, ByteHolder result) {
        try { result.value = (byte) parseIntWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }

    public static boolean tryParseByte(String s, int style, Locale locale, ByteHolder result) {
        try { result.value = (byte) parseIntWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }

    public static boolean tryParseShort(String s, ShortHolder result) {
        try { result.value = Short.parseShort(s.trim()); return true; }
        catch (NumberFormatException e) { return false; }
    }

    public static boolean tryParseShort(String s, int style, CultureInfo culture, ShortHolder result) {
        try { result.value = (short) parseIntWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }

    public static boolean tryParseShort(String s, int style, Locale locale, ShortHolder result) {
        try { result.value = (short) parseIntWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }

    public static boolean tryParseChar(String s, CharHolder result) {
        if (s != null && s.length() == 1) { result.value = s.charAt(0); return true; }
        return false;
    }

    public static boolean tryParseUInt(String s, int style, CultureInfo culture, IntHolder result) {
        try { result.value = (int) Long.parseLong(normalizeIntegerLiteral(s, style), (style & NumberStyles.AllowHexSpecifier) != 0 ? 16 : 10); return true; }
        catch (NumberFormatException e) { return false; }
    }

    public static boolean tryParseUInt(String s, int style, Locale locale, IntHolder result) {
        return tryParseUInt(s, style, (CultureInfo)null, result);
    }

    private static double parseDoubleWithStyle(String s, int style) {
        if (s == null) {
            throw new NumberFormatException("null");
        }
        String value = s;
        if ((style & NumberStyles.AllowLeadingWhite) != 0) {
            value = stripLeading(value);
        }
        if ((style & NumberStyles.AllowTrailingWhite) != 0) {
            value = stripTrailing(value);
        }
        if ((style & NumberStyles.AllowParentheses) != 0 && value.length() >= 2
                && value.charAt(0) == '(' && value.charAt(value.length() - 1) == ')') {
            value = "-" + value.substring(1, value.length() - 1);
        }
        if ((style & NumberStyles.AllowThousands) != 0) {
            value = value.replace(",", "");
        }
        return Double.parseDouble(value);
    }

    private static int parseIntWithStyle(String s, int style) {
        if ((style & NumberStyles.AllowHexSpecifier) != 0) {
            return Integer.parseUnsignedInt(normalizeIntegerLiteral(s, style), 16);
        }
        return Integer.parseInt(normalizeIntegerLiteral(s, style));
    }

    private static long parseLongWithStyle(String s, int style) {
        if ((style & NumberStyles.AllowHexSpecifier) != 0) {
            return Long.parseUnsignedLong(normalizeIntegerLiteral(s, style), 16);
        }
        return Long.parseLong(normalizeIntegerLiteral(s, style));
    }

    private static String normalizeIntegerLiteral(String s, int style) {
        if (s == null) {
            throw new NumberFormatException("null");
        }
        String value = s;
        if ((style & NumberStyles.AllowLeadingWhite) != 0) {
            value = stripLeading(value);
        }
        if ((style & NumberStyles.AllowTrailingWhite) != 0) {
            value = stripTrailing(value);
        }
        if ((style & NumberStyles.AllowThousands) != 0) {
            value = value.replace(",", "");
        }
        return value;
    }

    private static String stripLeading(String value) {
        int i = 0;
        while (i < value.length() && Character.isWhitespace(value.charAt(i))) {
            i++;
        }
        return value.substring(i);
    }

    private static String stripTrailing(String value) {
        int i = value.length() - 1;
        while (i >= 0 && Character.isWhitespace(value.charAt(i))) {
            i--;
        }
        return value.substring(0, i + 1);
    }

    // ---- FormatNumeric (for C# value.ToString("X2") etc.) ----

    /**
     * Formats a numeric value using a C# format specifier string (e.g. "X2", "D4", "F2").
     * This is used to convert C# {@code value.ToString("format")} calls to Java.
     *
     * @param format the C# format specifier (e.g. "X2", "x4", "D8", "F2")
     * @param value  the numeric value to format
     * @return the formatted string
     */
    public static String formatNumeric(String format, Object value) {
        return formatValue(format, value);
    }

    // ---- TryFormat helpers ----

    private static boolean writeFormattedToSpan(String formatted, Span<Character> dest, IntHolder charsWritten) {
        if (formatted.length() > dest.length()) {
            return false;
        }
        for (int i = 0; i < formatted.length(); i++) {
            dest.set(i, formatted.charAt(i));
        }
        charsWritten.value = formatted.length();
        return true;
    }

    private static String formatValue(String format, Object value) {
        if (format == null || format.isEmpty()) {
            return String.valueOf(value);
        }
        String javaFormat = translateFormat(format, value);
        return String.format(Locale.ROOT, javaFormat, value);
    }

    private static String translateFormat(String format, Object value) {
        char specChar = format.charAt(0);
        char spec = Character.toUpperCase(specChar);
        String arg = format.substring(1);
        switch (spec) {
            case 'X': {
                int width = arg.isEmpty() ? 0 : Integer.parseInt(arg);
                // Preserve case: C# "X" → uppercase hex, C# "x" → lowercase hex
                String caseChar = Character.isUpperCase(specChar) ? "X" : "x";
                String f = "%" + (width > 0 ? "0" + width : "") + caseChar;
                return f;
            }
            case 'F': {
                int precision = arg.isEmpty() ? 2 : Integer.parseInt(arg);
                return "%" + "." + precision + "f";
            }
            case 'D': {
                int width = arg.isEmpty() ? 0 : Integer.parseInt(arg);
                return "%" + (width > 0 ? "0" + width + "d" : "d");
            }
            case 'N': {
                int precision = arg.isEmpty() ? 2 : Integer.parseInt(arg);
                return "%" + "." + precision + "f";
            }
            case 'E': {
                int precision = arg.isEmpty() ? 6 : Integer.parseInt(arg);
                // Preserve case: C# "E" → uppercase, C# "e" → lowercase
                String eChar = Character.isUpperCase(specChar) ? "E" : "e";
                return "%" + "." + precision + eChar;
            }
            case 'G': {
                int precision = arg.isEmpty() ? 0 : Integer.parseInt(arg);
                if (value instanceof Float || value instanceof Double) {
                    return precision > 0 ? "%" + "." + precision + "g" : "%g";
                }
                return precision > 0 ? "%" + "." + precision + "f" : "%f";
            }
            default:
                return "%" + format;
        }
    }

    public static boolean tryFormatByte(int value, Span<Character> dest, IntHolder charsWritten) {
        return tryFormatByte(value, dest, charsWritten, null);
    }

    public static boolean tryFormatByte(int value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, value & 0xFF), dest, charsWritten);
    }

    public static boolean tryFormatSByte(byte value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, (int) value), dest, charsWritten);
    }

    public static boolean tryFormatShort(short value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, (int) value), dest, charsWritten);
    }

    public static boolean tryFormatUShort(short value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, value & 0xFFFF), dest, charsWritten);
    }

    public static boolean tryFormatInt(int value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, value), dest, charsWritten);
    }

    public static boolean tryFormatUInt(long value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, Long.toUnsignedString(value)), dest, charsWritten);
    }

    public static boolean tryFormatLong(long value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, value), dest, charsWritten);
    }

    public static boolean tryFormatULong(long value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, toUnsignedString(value)), dest, charsWritten);
    }

    public static boolean tryFormatFloat(float value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, value), dest, charsWritten);
    }

    public static boolean tryFormatDouble(double value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, value), dest, charsWritten);
    }

    public static boolean tryFormatDecimal(Decimal value, Span<Character> dest, IntHolder charsWritten, String format) {
        String s;
        if (format == null || format.isEmpty()) {
            s = value.toString();
        } else {
            String javaFormat = translateFormat(format, value.doubleValue());
            s = String.format(Locale.ROOT, javaFormat, value.doubleValue());
        }
        return writeFormattedToSpan(s, dest, charsWritten);
    }

    public static boolean tryFormatObject(Object value, Span<Character> dest, IntHolder charsWritten, String format) {
        return writeFormattedToSpan(formatValue(format, value), dest, charsWritten);
    }

    private static String toUnsignedString(long value) {
        if (value >= 0) {
            return Long.toString(value);
        }
        BigInteger upper = BigInteger.valueOf((value >>> 32) & 0xFFFFFFFFL);
        BigInteger lower = BigInteger.valueOf(value & 0xFFFFFFFFL);
        return upper.shiftLeft(32).add(lower).toString();
    }
}
