package io.github.ningpp.compat;

import java.util.Locale;

/** Numeric TryParse helpers (generated by CSharpToJava converter, replacing System numeric TryParse). */
public class MathHelper {
    public static double parseDouble(String s) {
        return Double.parseDouble(s);
    }

    public static double parseDouble(String s, CultureInfo culture) {
        return parseDouble(s);
    }

    public static double parseDouble(String s, Locale locale) {
        return parseDouble(s);
    }

    public static double parseDouble(String s, int style, CultureInfo culture) {
        return parseDoubleWithStyle(s, style);
    }

    public static double parseDouble(String s, int style, Locale locale) {
        return parseDoubleWithStyle(s, style);
    }

    public static float parseFloat(String s) {
        return Float.parseFloat(s);
    }

    public static float parseFloat(String s, CultureInfo culture) {
        return parseFloat(s);
    }

    public static float parseFloat(String s, Locale locale) {
        return parseFloat(s);
    }

    public static float parseFloat(String s, int style, CultureInfo culture) {
        return (float) parseDoubleWithStyle(s, style);
    }

    public static float parseFloat(String s, int style, Locale locale) {
        return (float) parseDoubleWithStyle(s, style);
    }

    public static int parseInt(String s) {
        return Integer.parseInt(s);
    }

    public static int parseInt(String s, CultureInfo culture) {
        return parseInt(s);
    }

    public static int parseInt(String s, Locale locale) {
        return parseInt(s);
    }

    public static int parseInt(String s, int style, CultureInfo culture) {
        return parseIntWithStyle(s, style);
    }

    public static int parseInt(String s, int style, Locale locale) {
        return parseIntWithStyle(s, style);
    }

    public static long parseLong(String s) {
        return Long.parseLong(s);
    }

    public static long parseLong(String s, CultureInfo culture) {
        return parseLong(s);
    }

    public static long parseLong(String s, Locale locale) {
        return parseLong(s);
    }

    public static long parseLong(String s, int style, CultureInfo culture) {
        return parseLongWithStyle(s, style);
    }

    public static long parseLong(String s, int style, Locale locale) {
        return parseLongWithStyle(s, style);
    }

    public static boolean tryParseDouble(String s, DoubleHolder result) {
        try { result.value = Double.parseDouble(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseDouble(String s, int style, CultureInfo culture, DoubleHolder result) {
        try { result.value = parseDoubleWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseFloat(String s, FloatHolder result) {
        try { result.value = Float.parseFloat(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseInt(String s, IntHolder result) {
        try { result.value = Integer.parseInt(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseInt(String s, int style, CultureInfo culture, IntHolder result) {
        try { result.value = parseIntWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseLong(String s, LongHolder result) {
        try { result.value = Long.parseLong(s); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseLong(String s, int style, CultureInfo culture, LongHolder result) {
        try { result.value = parseLongWithStyle(s, style); return true; }
        catch (NumberFormatException e) { return false; }
    }
    public static boolean tryParseBool(String s, BoolHolder result) {
        if ("true".equalsIgnoreCase(s))  { result.value = true;  return true; }
        if ("false".equalsIgnoreCase(s)) { result.value = false; return true; }
        return false;
    }

    private static double parseDoubleWithStyle(String s, int style) {
        if (s == null) {
            throw new NumberFormatException("null");
        }
        String value = s;
        if ((style & NumberStyles.AllowLeadingWhite) != 0) {
            value = stripLeading(value);
        }
        if ((style & NumberStyles.AllowTrailingWhite) != 0) {
            value = stripTrailing(value);
        }
        if ((style & NumberStyles.AllowParentheses) != 0 && value.length() >= 2
                && value.charAt(0) == '(' && value.charAt(value.length() - 1) == ')') {
            value = "-" + value.substring(1, value.length() - 1);
        }
        if ((style & NumberStyles.AllowThousands) != 0) {
            value = value.replace(",", "");
        }
        return Double.parseDouble(value);
    }

    private static int parseIntWithStyle(String s, int style) {
        if ((style & NumberStyles.AllowHexSpecifier) != 0) {
            return Integer.parseUnsignedInt(normalizeIntegerLiteral(s, style), 16);
        }
        return Integer.parseInt(normalizeIntegerLiteral(s, style));
    }

    private static long parseLongWithStyle(String s, int style) {
        if ((style & NumberStyles.AllowHexSpecifier) != 0) {
            return Long.parseUnsignedLong(normalizeIntegerLiteral(s, style), 16);
        }
        return Long.parseLong(normalizeIntegerLiteral(s, style));
    }

    private static String normalizeIntegerLiteral(String s, int style) {
        if (s == null) {
            throw new NumberFormatException("null");
        }
        String value = s;
        if ((style & NumberStyles.AllowLeadingWhite) != 0) {
            value = stripLeading(value);
        }
        if ((style & NumberStyles.AllowTrailingWhite) != 0) {
            value = stripTrailing(value);
        }
        if ((style & NumberStyles.AllowThousands) != 0) {
            value = value.replace(",", "");
        }
        return value;
    }

    private static String stripLeading(String value) {
        int i = 0;
        while (i < value.length() && Character.isWhitespace(value.charAt(i))) {
            i++;
        }
        return value.substring(i);
    }

    private static String stripTrailing(String value) {
        int i = value.length() - 1;
        while (i >= 0 && Character.isWhitespace(value.charAt(i))) {
            i--;
        }
        return value.substring(0, i + 1);
    }
}
