package io.github.ningpp.compat;

import java.util.Arrays;

/** Replacement for System.MemoryExtensions (generated by CSharpToJava converter). */
public class MemoryExtensions {
    public static ReadOnlySpan<Integer> asSpan(String s) {
        if (s == null) return new ReadOnlySpan<>(new Integer[0]);
        Integer[] arr = new Integer[s.length()];
        for (int i = 0; i < s.length(); i++) {
            arr[i] = (int) s.charAt(i);
        }
        return new ReadOnlySpan<>(arr);
    }

    public static ReadOnlySpan<Integer> asSpan(String s, int start, int length) {
        if (s == null) return new ReadOnlySpan<>(new Integer[0]);
        Integer[] arr = new Integer[length];
        for (int i = 0; i < length; i++) {
            arr[i] = (int) s.charAt(start + i);
        }
        return new ReadOnlySpan<>(arr);
    }
}
