package io.github.ningpp.compat;

/** Replacement for System.Runtime.InteropServices.MemoryMarshal (generated by CSharpToJava converter). */
public class MemoryMarshal {
    public static ReadOnlySpan<Byte> asBytes(ReadOnlySpan<Integer> span) {
        int len = span.length();
        Byte[] bytes = new Byte[len * 4];
        for (int i = 0; i < len; i++) {
            int cp = span.get(i);
            bytes[i * 4]     = (byte)(cp >>> 24);
            bytes[i * 4 + 1] = (byte)(cp >>> 16);
            bytes[i * 4 + 2] = (byte)(cp >>> 8);
            bytes[i * 4 + 3] = (byte)(cp);
        }
        return new ReadOnlySpan<>(bytes);
    }
}
