package io.github.ningpp.compat;

import java.util.Arrays;

/** Replacement for System.MemoryExtensions (generated by CSharpToJava converter). */
public class MemoryExtensions {
    public static ReadOnlySpan<Integer> asSpan(String s) {
        if (s == null) return new ReadOnlySpan<>(new Integer[0]);
        Integer[] arr = new Integer[s.length()];
        for (int i = 0; i < s.length(); i++) {
            arr[i] = (int) s.charAt(i);
        }
        return new ReadOnlySpan<>(arr);
    }

    public static ReadOnlySpan<Integer> asSpan(String s, int start, int length) {
        if (s == null) return new ReadOnlySpan<>(new Integer[0]);
        Integer[] arr = new Integer[length];
        for (int i = 0; i < length; i++) {
            arr[i] = (int) s.charAt(start + i);
        }
        return new ReadOnlySpan<>(arr);
    }

    /** C# Span<byte> → Java ReadOnlySpan<Byte> */
    public static ReadOnlySpan<Byte> asSpan(byte[] data) {
        if (data == null) return new ReadOnlySpan<>(new Byte[0]);
        Byte[] arr = new Byte[data.length];
        for (int i = 0; i < data.length; i++) {
            arr[i] = data[i];
        }
        return new ReadOnlySpan<>(arr);
    }

    /** C# ReadOnlySpan<byte> slice → Java ReadOnlySpan<Byte> */
    public static ReadOnlySpan<Byte> asSpan(byte[] data, int start, int length) {
        if (data == null) return new ReadOnlySpan<>(new Byte[0]);
        Byte[] arr = new Byte[length];
        for (int i = 0; i < length; i++) {
            arr[i] = data[start + i];
        }
        return new ReadOnlySpan<>(arr);
    }
}
