package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.MetadataException (generated by CSharpToJava converter). */
public class MetadataException extends RuntimeException {
    private int hresult;
    public MetadataException() { super(); }
    public MetadataException(String message) { super(message); }
    public MetadataException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
