package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.MetadataException (generated by CSharpToJava converter). */
public class MetadataException extends RuntimeException {
    public MetadataException() { super(); }
    public MetadataException(String message) { super(message); }
    public MetadataException(String message, Throwable cause) { super(message, cause); }
}
