package io.github.ningpp.compat;

/** Replacement for System.MethodAccessException (generated by CSharpToJava converter). */
public class MethodAccessException extends IllegalAccessException {
    public MethodAccessException() { super(); }
    public MethodAccessException(String message) { super(message); }
}
