package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.MethodInvocationException (generated by CSharpToJava converter). */
public class MethodInvocationException extends MethodException {
    public MethodInvocationException() { super(); }
    public MethodInvocationException(String message) { super(message); }
    public MethodInvocationException(String message, Throwable cause) { super(message, cause); }
}
