package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.MethodException (generated by CSharpToJava converter). */
public class MethodException extends ExtendedTypeSystemException {
    public MethodException() { super(); }
    public MethodException(String message) { super(message); }
    public MethodException(String message, Throwable cause) { super(message, cause); }
}
