package io.github.ningpp.compat;

/** Replacement for System.Resources.MissingManifestResourceException (generated by CSharpToJava converter). */
public class MissingManifestResourceException extends SystemException {
    public MissingManifestResourceException() { super(); }
    public MissingManifestResourceException(String message) { super(message); }
    public MissingManifestResourceException(String message, Throwable cause) { super(message, cause); }
}
