package io.github.ningpp.compat;

/** Replacement for System.Resources.MissingSatelliteAssemblyException (generated by CSharpToJava converter). */
public class MissingSatelliteAssemblyException extends SystemException {
    public MissingSatelliteAssemblyException() { super(); }
    public MissingSatelliteAssemblyException(String message) { super(message); }
    public MissingSatelliteAssemblyException(String message, Throwable cause) { super(message, cause); }
}
