package io.github.ningpp.compat;

/** Replacement for System.MissingMemberException (generated by CSharpToJava converter). */
public class MissingMemberException extends IllegalAccessException {
    public MissingMemberException() { super(); }
    public MissingMemberException(String message) { super(message); }
    public MissingMemberException(String message, Throwable cause) { super(message, cause); }
}
