package io.github.ningpp.compat;

/** Replacement for System.MissingMethodException (generated by CSharpToJava converter). */
public class MissingMethodException extends SystemException {
    public MissingMethodException() { super(); }
    public MissingMethodException(String message) { super(message); }
    public MissingMethodException(String message, Throwable cause) { super(message, cause); }
}
