package io.github.ningpp.compat;

/** Replacement for System.Data.MissingPrimaryKeyException (generated by CSharpToJava converter). */
public class MissingPrimaryKeyException extends DataException {
    public MissingPrimaryKeyException() { super(); }
    public MissingPrimaryKeyException(String message) { super(message); }
    public MissingPrimaryKeyException(String message, Throwable cause) { super(message, cause); }
}
