package io.github.ningpp.compat;

/** Replacement for System.MulticastNotSupportedException (generated by CSharpToJava converter). */
public class MulticastNotSupportedException extends SystemException {
    public MulticastNotSupportedException() { super(); }
    public MulticastNotSupportedException(String message) { super(message); }
    public MulticastNotSupportedException(String message, Throwable cause) { super(message, cause); }
}
