package io.github.ningpp.compat;

/** Replacement for System.Net.NetworkInformation.NetworkInformationException (generated by CSharpToJava converter). */
public class NetworkInformationException extends RuntimeException {
    private int hresult;
    public NetworkInformationException() { super(); }
    public NetworkInformationException(String message) { super(message); }
    public NetworkInformationException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
