package io.github.ningpp.compat;

/** Replacement for System.Net.NetworkInformation.NetworkInformationException (generated by CSharpToJava converter). */
public class NetworkInformationException extends RuntimeException {
    public NetworkInformationException() { super(); }
    public NetworkInformationException(String message) { super(message); }
    public NetworkInformationException(String message, Throwable cause) { super(message, cause); }
}
