package io.github.ningpp.compat;

/** Replacement for System.Data.NoNullAllowedException (generated by CSharpToJava converter). */
public class NoNullAllowedException extends DataException {
    public NoNullAllowedException() { super(); }
    public NoNullAllowedException(String message) { super(message); }
    public NoNullAllowedException(String message, Throwable cause) { super(message, cause); }
}
