package io.github.ningpp.compat;

/** Replacement for System.NotFiniteNumberException (generated by CSharpToJava converter). */
public class NotFiniteNumberException extends ArithmeticException {
    public NotFiniteNumberException() { super(); }
    public NotFiniteNumberException(String message) { super(message); }
}
