package io.github.ningpp.compat;

/** Replacement for System.ObjectDisposedException (generated by CSharpToJava converter). */
public class ObjectDisposedException extends IllegalStateException {
    private int hresult;
    public ObjectDisposedException() { super(); }
    public ObjectDisposedException(String message) { super(message); }
    public ObjectDisposedException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
