package io.github.ningpp.compat;

/** Holder for ref/out object parameters (generated by CSharpToJava converter). */
public final class ObjectHolder<T> {
    public T value;
    public ObjectHolder() { this.value = null; }
    public ObjectHolder(T value) { this.value = value; }
}
