package io.github.ningpp.compat;

/** Replacement for System.Data.Odbc.OdbcException (generated by CSharpToJava converter). */
public class OdbcException extends RuntimeException {
    public OdbcException() { super(); }
    public OdbcException(String message) { super(message); }
    public OdbcException(String message, Throwable cause) { super(message, cause); }
}
