package io.github.ningpp.compat;

/** Replacement for System.Data.Odbc.OdbcException (generated by CSharpToJava converter). */
public class OdbcException extends RuntimeException {
    private int hresult;
    public OdbcException() { super(); }
    public OdbcException(String message) { super(message); }
    public OdbcException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
