package io.github.ningpp.compat;

/** Replacement for System.Data.OleDb.OleDbException (generated by CSharpToJava converter). */
public class OleDbException extends RuntimeException {
    public OleDbException() { super(); }
    public OleDbException(String message) { super(message); }
    public OleDbException(String message, Throwable cause) { super(message, cause); }
}
