package io.github.ningpp.compat;

/** Replacement for System.Data.OleDb.OleDbException (generated by CSharpToJava converter). */
public class OleDbException extends RuntimeException {
    private int hresult;
    public OleDbException() { super(); }
    public OleDbException(String message) { super(message); }
    public OleDbException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
