package io.github.ningpp.compat;

/** Replacement for System.Data.OperationAbortedException (generated by CSharpToJava converter). */
public class OperationAbortedException extends SystemException {
    public OperationAbortedException() { super(); }
    public OperationAbortedException(String message) { super(message); }
    public OperationAbortedException(String message, Throwable cause) { super(message, cause); }
}
