package io.github.ningpp.compat;

/** Replacement for System.OutOfMemoryException (generated by CSharpToJava converter). */
public class OutOfMemoryException extends SystemException {
    public OutOfMemoryException() { super(); }
    public OutOfMemoryException(String message) { super(message); }
    public OutOfMemoryException(String message, Throwable cause) { super(message, cause); }
}
