package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ParameterBindingException (generated by CSharpToJava converter). */
public class ParameterBindingException extends RuntimeException {
    public ParameterBindingException() { super(); }
    public ParameterBindingException(String message) { super(message); }
    public ParameterBindingException(String message, Throwable cause) { super(message, cause); }
}
