package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ParameterBindingException (generated by CSharpToJava converter). */
public class ParameterBindingException extends RuntimeException {
    private int hresult;
    public ParameterBindingException() { super(); }
    public ParameterBindingException(String message) { super(message); }
    public ParameterBindingException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
