package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ParentContainsErrorRecordException (generated by CSharpToJava converter). */
public class ParentContainsErrorRecordException extends SystemException {
    public ParentContainsErrorRecordException() { super(); }
    public ParentContainsErrorRecordException(String message) { super(message); }
    public ParentContainsErrorRecordException(String message, Throwable cause) { super(message, cause); }
}
