package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ParsingMetadataException (generated by CSharpToJava converter). */
public class ParsingMetadataException extends MetadataException {
    public ParsingMetadataException() { super(); }
    public ParsingMetadataException(String message) { super(message); }
    public ParsingMetadataException(String message, Throwable cause) { super(message, cause); }
}
