package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ParseException (generated by CSharpToJava converter). */
public class ParseException extends RuntimeException {
    public ParseException() { super(); }
    public ParseException(String message) { super(message); }
    public ParseException(String message, Throwable cause) { super(message, cause); }
}
