package io.github.ningpp.compat;

import java.nio.file.*;

/** Replacement for System.IO.Path static methods (generated by CSharpToJava converter). */
public class PathHelper {
    /** Mirrors Path.IsPathRooted */
    public static boolean isPathRooted(String path) {
        return path != null && Paths.get(path).isAbsolute();
    }
    /** Mirrors Path.GetFullPath */
    public static String getFullPath(String path) {
        return Paths.get(path).toAbsolutePath().normalize().toString();
    }
    /** Mirrors Path.GetDirectoryName — returns parent directory path, or null if no parent */
    public static String getDirectoryName(String path) {
        Path p = Paths.get(path).getParent();
        return p != null ? p.toString() : null;
    }
    /** Mirrors Path.GetFileName */
    public static String getFileName(String path) {
        Path p = Paths.get(path).getFileName();
        return p != null ? p.toString() : null;
    }
    /** Mirrors Path.GetFileNameWithoutExtension */
    public static String getFileNameWithoutExtension(String path) {
        String name = getFileName(path);
        if (name == null) return null;
        int dot = name.lastIndexOf('.');
        return dot > 0 ? name.substring(0, dot) : name;
    }
}
