package io.github.ningpp.compat;

import java.io.IOException;

/** Replacement for System.IO.PathTooLongException (generated by CSharpToJava converter). */
public class PathTooLongException extends IOException {
  public PathTooLongException() { super(); }
  public PathTooLongException(String message) { super(message); }
  public PathTooLongException(String message, Throwable cause) { super(message, cause); }
}
