package io.github.ningpp.compat;

import java.nio.file.*;

/** Replacement for System.IO.Path static methods (generated by CSharpToJava converter). */
public class PathHelper {
    /** Mirrors Path.IsPathRooted */
    public static boolean isPathRooted(String path) {
        return path != null && Paths.get(path).isAbsolute();
    }
    /** Mirrors Path.GetFullPath */
    public static String getFullPath(String path) {
        return Paths.get(path).toAbsolutePath().normalize().toString();
    }
    /** Mirrors Path.GetDirectoryName — returns parent directory path, or null if no parent */
    public static String getDirectoryName(String path) {
        Path p = Paths.get(path).getParent();
        return p != null ? p.toString() : null;
    }
    /** Mirrors Path.GetFileName */
    public static String getFileName(String path) {
        Path p = Paths.get(path).getFileName();
        return p != null ? p.toString() : null;
    }
    /** Mirrors Path.GetFileNameWithoutExtension */
    public static String getFileNameWithoutExtension(String path) {
        String name = getFileName(path);
        if (name == null) return null;
        int dot = name.lastIndexOf('.');
        return dot > 0 ? name.substring(0, dot) : name;
    }
    /** Mirrors Path.Combine(string, string) */
    public static String combine(String path1, String path2) {
        if (path1 == null || path1.isEmpty()) return path2;
        if (path2 == null || path2.isEmpty()) return path1;
        if (Paths.get(path2).isAbsolute()) return path2;
        return Paths.get(path1, path2).toString();
    }
    /** Mirrors Path.GetExtension */
    public static String getExtension(String path) {
        String name = getFileName(path);
        if (name == null) return null;
        int dot = name.lastIndexOf('.');
        return dot >= 0 ? name.substring(dot) : "";
    }
}
