package io.github.ningpp.compat;

/** Replacement for System.Net.NetworkInformation.PingException (generated by CSharpToJava converter). */
public class PingException extends IllegalStateException {
    public PingException() { super(); }
    public PingException(String message) { super(message); }
    public PingException(String message, Throwable cause) { super(message, cause); }
}
