package io.github.ningpp.compat;

/** Replacement for System.Net.NetworkInformation.PingException (generated by CSharpToJava converter). */
public class PingException extends IllegalStateException {
    private int hresult;
    public PingException() { super(); }
    public PingException(String message) { super(message); }
    public PingException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
