package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PipelineClosedException (generated by CSharpToJava converter). */
public class PipelineClosedException extends RuntimeException {
    public PipelineClosedException() { super(); }
    public PipelineClosedException(String message) { super(message); }
    public PipelineClosedException(String message, Throwable cause) { super(message, cause); }
}
