package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PipelineStoppedException (generated by CSharpToJava converter). */
public class PipelineStoppedException extends RuntimeException {
    private int hresult;
    public PipelineStoppedException() { super(); }
    public PipelineStoppedException(String message) { super(message); }
    public PipelineStoppedException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
