package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PipelineClosedException (generated by CSharpToJava converter). */
public class PipelineClosedException extends RuntimeException {
    private int hresult;
    public PipelineClosedException() { super(); }
    public PipelineClosedException(String message) { super(message); }
    public PipelineClosedException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
