package io.github.ningpp.compat;

/** Replacement for System.PlatformNotSupportedException (generated by CSharpToJava converter). */
public class PlatformNotSupportedException extends UnsupportedOperationException {
    private int hresult;
    public PlatformNotSupportedException() { super(); }
    public PlatformNotSupportedException(String message) { super(message); }
    public PlatformNotSupportedException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
