package io.github.ningpp.compat;

/** Replacement for System.PlatformNotSupportedException (generated by CSharpToJava converter). */
public class PlatformNotSupportedException extends UnsupportedOperationException {
    public PlatformNotSupportedException() { super(); }
    public PlatformNotSupportedException(String message) { super(message); }
    public PlatformNotSupportedException(String message, Throwable cause) { super(message, cause); }
}
