package io.github.ningpp.compat;

/** Replacement for System.Security.Policy.PolicyException (generated by CSharpToJava converter). */
public class PolicyException extends SystemException {
    public PolicyException() { super(); }
    public PolicyException(String message) { super(message); }
    public PolicyException(String message, Throwable cause) { super(message, cause); }
}
