package io.github.ningpp.compat;

/** Replacement for System.Security.AccessControl.PrivilegeNotHeldException (generated by CSharpToJava converter). */
public class PrivilegeNotHeldException extends RuntimeException {
    public PrivilegeNotHeldException() { super(); }
    public PrivilegeNotHeldException(String message) { super(message); }
    public PrivilegeNotHeldException(String message, Throwable cause) { super(message, cause); }
}
