package io.github.ningpp.compat;

/** Replacement for System.Security.AccessControl.PrivilegeNotHeldException (generated by CSharpToJava converter). */
public class PrivilegeNotHeldException extends RuntimeException {
    private int hresult;
    public PrivilegeNotHeldException() { super(); }
    public PrivilegeNotHeldException(String message) { super(message); }
    public PrivilegeNotHeldException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
