package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.ProcessCommandException (generated by CSharpToJava converter). */
public class ProcessCommandException extends SystemException {
    public ProcessCommandException() { super(); }
    public ProcessCommandException(String message) { super(message); }
    public ProcessCommandException(String message, Throwable cause) { super(message, cause); }
}
