package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.StringManipulation.FlashExtractWrapper.FlashExtract.ProgramNotFoundException (generated by CSharpToJava converter). */
public class ProgramNotFoundException extends RuntimeException {
    public ProgramNotFoundException() { super(); }
    public ProgramNotFoundException(String message) { super(message); }
    public ProgramNotFoundException(String message, Throwable cause) { super(message, cause); }
}
