package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PropertyNotFoundException (generated by CSharpToJava converter). */
public class PropertyNotFoundException extends ExtendedTypeSystemException {
    public PropertyNotFoundException() { super(); }
    public PropertyNotFoundException(String message) { super(message); }
    public PropertyNotFoundException(String message, Throwable cause) { super(message, cause); }
}
