package io.github.ningpp.compat;

/** Replacement for System.Net.ProtocolViolationException (generated by CSharpToJava converter). */
public class ProtocolViolationException extends IllegalStateException {
    private int hresult;
    public ProtocolViolationException() { super(); }
    public ProtocolViolationException(String message) { super(message); }
    public ProtocolViolationException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
