package io.github.ningpp.compat;

/** Replacement for System.Net.ProtocolViolationException (generated by CSharpToJava converter). */
public class ProtocolViolationException extends IllegalStateException {
    public ProtocolViolationException() { super(); }
    public ProtocolViolationException(String message) { super(message); }
    public ProtocolViolationException(String message, Throwable cause) { super(message, cause); }
}
