package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ProviderInvocationException (generated by CSharpToJava converter). */
public class ProviderInvocationException extends RuntimeException {
    public ProviderInvocationException() { super(); }
    public ProviderInvocationException(String message) { super(message); }
    public ProviderInvocationException(String message, Throwable cause) { super(message, cause); }
}
