package io.github.ningpp.compat;

/** Replacement for System.Configuration.Provider.ProviderException (generated by CSharpToJava converter). */
public class ProviderException extends RuntimeException {
    public ProviderException() { super(); }
    public ProviderException(String message) { super(message); }
    public ProviderException(String message, Throwable cause) { super(message, cause); }
}
