package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ProviderNameAmbiguousException (generated by CSharpToJava converter). */
public class ProviderNameAmbiguousException extends ProviderNotFoundException {
    public ProviderNameAmbiguousException() { super(); }
    public ProviderNameAmbiguousException(String message) { super(message); }
    public ProviderNameAmbiguousException(String message, Throwable cause) { super(message, cause); }
}
