package io.github.ningpp.compat;

/** Replacement for System.Configuration.Provider.ProviderException (generated by CSharpToJava converter). */
public class ProviderException extends RuntimeException {
    private int hresult;
    public ProviderException() { super(); }
    public ProviderException(String message) { super(message); }
    public ProviderException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
