package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSArgumentOutOfRangeException (generated by CSharpToJava converter). */
public class PSArgumentOutOfRangeException extends IndexOutOfBoundsException {
    public PSArgumentOutOfRangeException() { super(); }
    public PSArgumentOutOfRangeException(String message) { super(message); }
    public PSArgumentOutOfRangeException(String message, Throwable cause) { super(message, cause); }
}
