package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSArgumentNullException (generated by CSharpToJava converter). */
public class PSArgumentNullException extends NullPointerException {
    private int hresult;
    public PSArgumentNullException() { super(); }
    public PSArgumentNullException(String message) { super(message); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
