package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSArgumentNullException (generated by CSharpToJava converter). */
public class PSArgumentNullException extends NullPointerException {
    public PSArgumentNullException() { super(); }
    public PSArgumentNullException(String message) { super(message); }
}
