package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSArgumentException (generated by CSharpToJava converter). */
public class PSArgumentException extends IllegalArgumentException {
    private int hresult;
    public PSArgumentException() { super(); }
    public PSArgumentException(String message) { super(message); }
    public PSArgumentException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
