package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.PSConsoleLoadException (generated by CSharpToJava converter). */
public class PSConsoleLoadException extends SystemException {
    public PSConsoleLoadException() { super(); }
    public PSConsoleLoadException(String message) { super(message); }
    public PSConsoleLoadException(String message, Throwable cause) { super(message, cause); }
}
