package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Remoting.PSDirectException (generated by CSharpToJava converter). */
public class PSDirectException extends RuntimeException {
    private int hresult;
    public PSDirectException() { super(); }
    public PSDirectException(String message) { super(message); }
    public PSDirectException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
