package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSInvalidCastException (generated by CSharpToJava converter). */
public class PSInvalidCastException extends ClassCastException {
    private int hresult;
    public PSInvalidCastException() { super(); }
    public PSInvalidCastException(String message) { super(message); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
