package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSInvalidOperationException (generated by CSharpToJava converter). */
public class PSInvalidOperationException extends IllegalStateException {
    private int hresult;
    public PSInvalidOperationException() { super(); }
    public PSInvalidOperationException(String message) { super(message); }
    public PSInvalidOperationException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
