package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSInvalidCastException (generated by CSharpToJava converter). */
public class PSInvalidCastException extends ClassCastException {
    public PSInvalidCastException() { super(); }
    public PSInvalidCastException(String message) { super(message); }
}
