package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSNotImplementedException (generated by CSharpToJava converter). */
public class PSNotImplementedException extends UnsupportedOperationException {
    public PSNotImplementedException() { super(); }
    public PSNotImplementedException(String message) { super(message); }
    public PSNotImplementedException(String message, Throwable cause) { super(message, cause); }
}
