package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSNotImplementedException (generated by CSharpToJava converter). */
public class PSNotImplementedException extends UnsupportedOperationException {
    private int hresult;
    public PSNotImplementedException() { super(); }
    public PSNotImplementedException(String message) { super(message); }
    public PSNotImplementedException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
