package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSNotSupportedException (generated by CSharpToJava converter). */
public class PSNotSupportedException extends UnsupportedOperationException {
    private int hresult;
    public PSNotSupportedException() { super(); }
    public PSNotSupportedException(String message) { super(message); }
    public PSNotSupportedException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
