package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSNotSupportedException (generated by CSharpToJava converter). */
public class PSNotSupportedException extends UnsupportedOperationException {
    public PSNotSupportedException() { super(); }
    public PSNotSupportedException(String message) { super(message); }
    public PSNotSupportedException(String message, Throwable cause) { super(message, cause); }
}
