package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSObjectDisposedException (generated by CSharpToJava converter). */
public class PSObjectDisposedException extends ObjectDisposedException {
    public PSObjectDisposedException() { super(); }
    public PSObjectDisposedException(String message) { super(message); }
    public PSObjectDisposedException(String message, Throwable cause) { super(message, cause); }
}
