package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Remoting.PSRemotingDataStructureException (generated by CSharpToJava converter). */
public class PSRemotingDataStructureException extends RuntimeException {
    private int hresult;
    public PSRemotingDataStructureException() { super(); }
    public PSRemotingDataStructureException(String message) { super(message); }
    public PSRemotingDataStructureException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
