package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Remoting.PSRemotingTransportRedirectException (generated by CSharpToJava converter). */
public class PSRemotingTransportRedirectException extends PSRemotingTransportException {
    public PSRemotingTransportRedirectException() { super(); }
    public PSRemotingTransportRedirectException(String message) { super(message); }
    public PSRemotingTransportRedirectException(String message, Throwable cause) { super(message, cause); }
}
