package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Remoting.PSRemotingDataStructureException (generated by CSharpToJava converter). */
public class PSRemotingDataStructureException extends RuntimeException {
    public PSRemotingDataStructureException() { super(); }
    public PSRemotingDataStructureException(String message) { super(message); }
    public PSRemotingDataStructureException(String message, Throwable cause) { super(message, cause); }
}
