package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Remoting.PSRemotingTransportException (generated by CSharpToJava converter). */
public class PSRemotingTransportException extends RuntimeException {
    public PSRemotingTransportException() { super(); }
    public PSRemotingTransportException(String message) { super(message); }
    public PSRemotingTransportException(String message, Throwable cause) { super(message, cause); }
}
