package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.PSSecurityException (generated by CSharpToJava converter). */
public class PSSecurityException extends RuntimeException {
    private int hresult;
    public PSSecurityException() { super(); }
    public PSSecurityException(String message) { super(message); }
    public PSSecurityException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
