package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.PSSnapInException (generated by CSharpToJava converter). */
public class PSSnapInException extends RuntimeException {
    private int hresult;
    public PSSnapInException() { super(); }
    public PSSnapInException(String message) { super(message); }
    public PSSnapInException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
