package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.PSSnapInException (generated by CSharpToJava converter). */
public class PSSnapInException extends RuntimeException {
    public PSSnapInException() { super(); }
    public PSSnapInException(String message) { super(message); }
    public PSSnapInException(String message, Throwable cause) { super(message, cause); }
}
