package io.github.ningpp.compat;

import java.util.Arrays;

/**
 * Lightweight read-only array-slice container (generated by CSharpToJava converter).
 * Does not simulate C# ref-struct lifetime semantics.
 */
public final class ReadOnlySpan<T> {
    private final T[] array;
    private final int offset;
    private final int length;

    public ReadOnlySpan(T[] array) {
        this.array = array;
        this.offset = 0;
        this.length = array.length;
    }

    public ReadOnlySpan(T[] array, int offset, int length) {
        if (offset < 0 || length < 0 || offset + length > array.length) {
            throw new IndexOutOfBoundsException(
                "offset=" + offset + ", length=" + length + ", arrayLength=" + array.length);
        }
        this.array = array;
        this.offset = offset;
        this.length = length;
    }

    public ReadOnlySpan(Span<T> span) {
        this.array = span.getArray();
        this.offset = span.getOffset();
        this.length = span.length();
    }

    public int length() {
        return length;
    }

    public T get(int index) {
        if (index < 0 || index >= length) {
            throw new IndexOutOfBoundsException("index=" + index + ", length=" + length);
        }
        return array[offset + index];
    }

    public ReadOnlySpan<T> slice(int start) {
        return slice(start, length - start);
    }

    public ReadOnlySpan<T> slice(int start, int len) {
        if (start < 0 || len < 0 || start + len > length) {
            throw new IndexOutOfBoundsException(
                "start=" + start + ", len=" + len + ", length=" + length);
        }
        return new ReadOnlySpan<>(array, offset + start, len);
    }

    public T[] toArray() {
        return Arrays.copyOfRange(array, offset, offset + length);
    }

    @Override
    public String toString() {
        if (array instanceof Character[]) {
            StringBuilder sb = new StringBuilder(length);
            for (int i = 0; i < length; i++) {
                sb.append((Character) array[offset + i]);
            }
            return sb.toString();
        }
        return super.toString();
    }
}
