package io.github.ningpp.compat;

/** Replacement for System.Xml.ReadState (generated by CSharpToJava converter). */
public class ReadState {
    public static final int Initial     = 0;
    public static final int Interactive = 1;
    public static final int Error       = 2;
    public static final int EndOfFile   = 3;
    public static final int Closed      = 4;

    public static int getInitial()     { return Initial; }
    public static int getInteractive() { return Interactive; }
    public static int getError()       { return Error; }
    public static int getEndOfFile()   { return EndOfFile; }
    public static int getClosed()      { return Closed; }
}
