package io.github.ningpp.compat;

/** Replacement for System.Data.ReadOnlyException (generated by CSharpToJava converter). */
public class ReadOnlyException extends DataException {
    public ReadOnlyException() { super(); }
    public ReadOnlyException(String message) { super(message); }
    public ReadOnlyException(String message, Throwable cause) { super(message, cause); }
}
