package io.github.ningpp.compat;

import java.util.Arrays;

/**
 * Lightweight read-only array-slice container (generated by CSharpToJava converter).
 * Does not simulate C# ref-struct lifetime semantics.
 */
public final class ReadOnlySpan<T> {
    private final Object array;
    private final int offset;
    private final int length;

    public ReadOnlySpan(T[] array) {
        this.array = array;
        this.offset = 0;
        this.length = array.length;
    }

    /** Copy constructor — allows wrapping an existing ReadOnlySpan without type inference issues */
    public ReadOnlySpan(ReadOnlySpan<T> other) {
        this.array = other.array;
        this.offset = other.offset;
        this.length = other.length;
    }

    public ReadOnlySpan(T[] array, int offset, int length) {
        if (offset < 0 || length < 0 || offset + length > array.length) {
            throw new IndexOutOfBoundsException(
                "offset=" + offset + ", length=" + length + ", arrayLength=" + array.length);
        }
        this.array = array;
        this.offset = offset;
        this.length = length;
    }

    public ReadOnlySpan(Span<T> span) {
        this.array = span.getArray();
        this.offset = span.getOffset();
        this.length = span.length();
    }

    public int length() {
        return length;
    }

    /** Alias for length() — matches C# Span.Length property getter translation */
    public int getLength() {
        return length;
    }

    public T get(int index) {
        if (index < 0 || index >= length) {
            throw new IndexOutOfBoundsException("index=" + index + ", length=" + length);
        }
        if (array instanceof byte[] bytes) {
            @SuppressWarnings("unchecked")
            T value = (T) java.lang.Integer.valueOf(bytes[offset + index] & 0xFF);
            return value;
        }
        @SuppressWarnings("unchecked")
        T value = ((T[]) array)[offset + index];
        return value;
    }

    public ReadOnlySpan<T> slice(int start) {
        return slice(start, length - start);
    }

    public ReadOnlySpan<T> slice(int start, int len) {
        if (start < 0 || len < 0 || start + len > length) {
            throw new IndexOutOfBoundsException(
                "start=" + start + ", len=" + len + ", length=" + length);
        }
        if (array instanceof byte[] bytes) {
            return new ReadOnlySpan<>((T[]) toIntegerArray(bytes, offset + start, len));
        }
        return new ReadOnlySpan<>((T[]) array, offset + start, len);
    }

    public T[] toArray() {
        if (array instanceof byte[] bytes) {
            return (T[]) toIntegerArray(bytes, offset, length);
        }
        return Arrays.copyOfRange((T[]) array, offset, offset + length);
    }

    public void copyTo(Span<T> destination) {
        int copyLength = Math.min(length, destination.length());
        for (int i = 0; i < copyLength; i++) {
            destination.set(i, get(i));
        }
    }

    @Override
    public String toString() {
        if (array instanceof Character[] chars) {
            StringBuilder sb = new StringBuilder(length);
            for (int i = 0; i < length; i++) {
                sb.append(chars[offset + i]);
            }
            return sb.toString();
        }
        return super.toString();
    }

    private static Integer[] toIntegerArray(byte[] bytes, int offset, int length) {
        Integer[] copy = new Integer[length];
        for (int i = 0; i < length; i++) {
            copy[i] = bytes[offset + i] & 0xFF;
        }
        return copy;
    }
}
