package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.RedirectedException (generated by CSharpToJava converter). */
public class RedirectedException extends RuntimeException {
    public RedirectedException() { super(); }
    public RedirectedException(String message) { super(message); }
    public RedirectedException(String message, Throwable cause) { super(message, cause); }
}
