package io.github.ningpp.compat;

/** Replacement for System.Reflection.ReflectionTypeLoadException (generated by CSharpToJava converter). */
public class ReflectionTypeLoadException extends SystemException {
    public ReflectionTypeLoadException() { super(); }
    public ReflectionTypeLoadException(String message) { super(message); }
    public ReflectionTypeLoadException(String message, Throwable cause) { super(message, cause); }
}
