package io.github.ningpp.compat;

/** Replacement for System.Runtime.Remoting.RemotingTimeoutException (generated by CSharpToJava converter). */
public class RemotingTimeoutException extends RemotingException {
    public RemotingTimeoutException() { super(); }
    public RemotingTimeoutException(String message) { super(message); }
    public RemotingTimeoutException(String message, Throwable cause) { super(message, cause); }
}
