package io.github.ningpp.compat;

/** Replacement for System.Runtime.Remoting.RemotingException (generated by CSharpToJava converter). */
public class RemotingException extends SystemException {
    public RemotingException() { super(); }
    public RemotingException(String message) { super(message); }
    public RemotingException(String message, Throwable cause) { super(message, cause); }
}
