package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.RestartComputerTimeoutException (generated by CSharpToJava converter). */
public class RestartComputerTimeoutException extends RuntimeException {
    private int hresult;
    public RestartComputerTimeoutException() { super(); }
    public RestartComputerTimeoutException(String message) { super(message); }
    public RestartComputerTimeoutException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
