package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.RestartComputerTimeoutException (generated by CSharpToJava converter). */
public class RestartComputerTimeoutException extends RuntimeException {
    public RestartComputerTimeoutException() { super(); }
    public RestartComputerTimeoutException(String message) { super(message); }
    public RestartComputerTimeoutException(String message, Throwable cause) { super(message, cause); }
}
