package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.StringManipulation.FlashExtractWrapper.FlashExtract.ResultNotFoundException (generated by CSharpToJava converter). */
public class ResultNotFoundException extends RuntimeException {
    private int hresult;
    public ResultNotFoundException() { super(); }
    public ResultNotFoundException(String message) { super(message); }
    public ResultNotFoundException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
