package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.StringManipulation.FlashExtractWrapper.FlashExtract.ResultNotFoundException (generated by CSharpToJava converter). */
public class ResultNotFoundException extends RuntimeException {
    public ResultNotFoundException() { super(); }
    public ResultNotFoundException(String message) { super(message); }
    public ResultNotFoundException(String message, Throwable cause) { super(message, cause); }
}
