package io.github.ningpp.compat;

/** Replacement for System.Data.RowNotInTableException (generated by CSharpToJava converter). */
public class RowNotInTableException extends DataException {
    public RowNotInTableException() { super(); }
    public RowNotInTableException(String message) { super(message); }
    public RowNotInTableException(String message, Throwable cause) { super(message, cause); }
}
