package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.RunspaceConfigurationAttributeException (generated by CSharpToJava converter). */
public class RunspaceConfigurationAttributeException extends SystemException {
    public RunspaceConfigurationAttributeException() { super(); }
    public RunspaceConfigurationAttributeException(String message) { super(message); }
    public RunspaceConfigurationAttributeException(String message, Throwable cause) { super(message, cause); }
}
