package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.RunspaceConfigurationTypeException (generated by CSharpToJava converter). */
public class RunspaceConfigurationTypeException extends SystemException {
    public RunspaceConfigurationTypeException() { super(); }
    public RunspaceConfigurationTypeException(String message) { super(message); }
    public RunspaceConfigurationTypeException(String message, Throwable cause) { super(message, cause); }
}
