package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.RuntimeException (generated by CSharpToJava converter). */
public class RuntimeException extends SystemException {
    public RuntimeException() { super(); }
    public RuntimeException(String message) { super(message); }
    public RuntimeException(String message, Throwable cause) { super(message, cause); }
}
