package io.github.ningpp.compat;

/** Replacement for System.Runtime.CompilerServices.RuntimeWrappedException (generated by CSharpToJava converter). */
public class RuntimeWrappedException extends RuntimeException {
    public RuntimeWrappedException() { super(); }
    public RuntimeWrappedException(String message) { super(message); }
    public RuntimeWrappedException(String message, Throwable cause) { super(message, cause); }
}
