package io.github.ningpp.compat;

/** Replacement for System.Runtime.CompilerServices.RuntimeWrappedException (generated by CSharpToJava converter). */
public class RuntimeWrappedException extends RuntimeException {
    private int hresult;
    public RuntimeWrappedException() { super(); }
    public RuntimeWrappedException(String message) { super(message); }
    public RuntimeWrappedException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
