package io.github.ningpp.compat;

/** Replacement for System.Runtime.InteropServices.SafeArrayRankMismatchException (generated by CSharpToJava converter). */
public class SafeArrayRankMismatchException extends SystemException {
    public SafeArrayRankMismatchException() { super(); }
    public SafeArrayRankMismatchException(String message) { super(message); }
    public SafeArrayRankMismatchException(String message, Throwable cause) { super(message, cause); }
}
