package io.github.ningpp.compat;

/** Replacement for System.Runtime.InteropServices.SafeArrayTypeMismatchException (generated by CSharpToJava converter). */
public class SafeArrayTypeMismatchException extends SystemException {
    public SafeArrayTypeMismatchException() { super(); }
    public SafeArrayTypeMismatchException(String message) { super(message); }
    public SafeArrayTypeMismatchException(String message, Throwable cause) { super(message, cause); }
}
