package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ScriptRequiresException (generated by CSharpToJava converter). */
public class ScriptRequiresException extends RuntimeException {
    public ScriptRequiresException() { super(); }
    public ScriptRequiresException(String message) { super(message); }
    public ScriptRequiresException(String message, Throwable cause) { super(message, cause); }
}
