package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ScriptBlockToPowerShellNotSupportedException (generated by CSharpToJava converter). */
public class ScriptBlockToPowerShellNotSupportedException extends RuntimeException {
    public ScriptBlockToPowerShellNotSupportedException() { super(); }
    public ScriptBlockToPowerShellNotSupportedException(String message) { super(message); }
    public ScriptBlockToPowerShellNotSupportedException(String message, Throwable cause) { super(message, cause); }
}
