package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ScriptRequiresException (generated by CSharpToJava converter). */
public class ScriptRequiresException extends RuntimeException {
    private int hresult;
    public ScriptRequiresException() { super(); }
    public ScriptRequiresException(String message) { super(message); }
    public ScriptRequiresException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
