package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ScriptCallDepthException (generated by CSharpToJava converter). */
public class ScriptCallDepthException extends SystemException {
    public ScriptCallDepthException() { super(); }
    public ScriptCallDepthException(String message) { super(message); }
    public ScriptCallDepthException(String message, Throwable cause) { super(message, cause); }
}
