package io.github.ningpp.compat;

/** Replacement for System.Runtime.InteropServices.SEHException (generated by CSharpToJava converter). */
public class SEHException extends ExternalException {
    public SEHException() { super(); }
    public SEHException(String message) { super(message); }
    public SEHException(String message, Throwable cause) { super(message, cause); }
}
