package io.github.ningpp.compat;

/** Replacement for System.Threading.SemaphoreFullException (generated by CSharpToJava converter). */
public class SemaphoreFullException extends SystemException {
    public SemaphoreFullException() { super(); }
    public SemaphoreFullException(String message) { super(message); }
    public SemaphoreFullException(String message, Throwable cause) { super(message, cause); }
}
