package io.github.ningpp.compat;

/** Replacement for System.Runtime.Serialization.SerializationException (generated by CSharpToJava converter). */
public class SerializationException extends SystemException {
    public SerializationException() { super(); }
    public SerializationException(String message) { super(message); }
    public SerializationException(String message, Throwable cause) { super(message, cause); }
}
