package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.ServiceCommandException (generated by CSharpToJava converter). */
public class ServiceCommandException extends SystemException {
    public ServiceCommandException() { super(); }
    public ServiceCommandException(String message) { super(message); }
    public ServiceCommandException(String message, Throwable cause) { super(message, cause); }
}
