package io.github.ningpp.compat;

/** Replacement for System.Runtime.Remoting.ServerException (generated by CSharpToJava converter). */
public class ServerException extends SystemException {
    public ServerException() { super(); }
    public ServerException(String message) { super(message); }
    public ServerException(String message, Throwable cause) { super(message, cause); }
}
