package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.SessionStateException (generated by CSharpToJava converter). */
public class SessionStateException extends RuntimeException {
    public SessionStateException() { super(); }
    public SessionStateException(String message) { super(message); }
    public SessionStateException(String message, Throwable cause) { super(message, cause); }
}
