package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.SessionStateOverflowException (generated by CSharpToJava converter). */
public class SessionStateOverflowException extends SessionStateException {
    public SessionStateOverflowException() { super(); }
    public SessionStateOverflowException(String message) { super(message); }
    public SessionStateOverflowException(String message, Throwable cause) { super(message, cause); }
}
