package io.github.ningpp.compat;

/** Replacement for System.Configuration.SettingsPropertyIsReadOnlyException (generated by CSharpToJava converter). */
public class SettingsPropertyIsReadOnlyException extends RuntimeException {
    public SettingsPropertyIsReadOnlyException() { super(); }
    public SettingsPropertyIsReadOnlyException(String message) { super(message); }
    public SettingsPropertyIsReadOnlyException(String message, Throwable cause) { super(message, cause); }
}
