package io.github.ningpp.compat;

/** Replacement for System.Configuration.SettingsPropertyWrongTypeException (generated by CSharpToJava converter). */
public class SettingsPropertyWrongTypeException extends RuntimeException {
    public SettingsPropertyWrongTypeException() { super(); }
    public SettingsPropertyWrongTypeException(String message) { super(message); }
    public SettingsPropertyWrongTypeException(String message, Throwable cause) { super(message, cause); }
}
