package io.github.ningpp.compat;

/** Replacement for System.Configuration.SettingsPropertyNotFoundException (generated by CSharpToJava converter). */
public class SettingsPropertyNotFoundException extends RuntimeException {
    public SettingsPropertyNotFoundException() { super(); }
    public SettingsPropertyNotFoundException(String message) { super(message); }
    public SettingsPropertyNotFoundException(String message, Throwable cause) { super(message, cause); }
}
