package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.SetValueException (generated by CSharpToJava converter). */
public class SetValueException extends ExtendedTypeSystemException {
    public SetValueException() { super(); }
    public SetValueException(String message) { super(message); }
    public SetValueException(String message, Throwable cause) { super(message, cause); }
}
