package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.SetValueInvocationException (generated by CSharpToJava converter). */
public class SetValueInvocationException extends SetValueException {
    public SetValueInvocationException() { super(); }
    public SetValueInvocationException(String message) { super(message); }
    public SetValueInvocationException(String message, Throwable cause) { super(message, cause); }
}
