package io.github.ningpp.compat;

/** Holder for ref/out short parameters (generated by CSharpToJava converter). */
public final class ShortHolder {
    public short value;
    public ShortHolder() { this.value = (short)0; }
    public ShortHolder(short value) { this.value = value; }
}
