package io.github.ningpp.compat;

/** Replacement for System.Net.Mail.SmtpFailedRecipientException (generated by CSharpToJava converter). */
public class SmtpFailedRecipientException extends SmtpException {
    public SmtpFailedRecipientException() { super(); }
    public SmtpFailedRecipientException(String message) { super(message); }
    public SmtpFailedRecipientException(String message, Throwable cause) { super(message, cause); }
}
