package io.github.ningpp.compat;

/** Replacement for System.Net.Mail.SmtpException (generated by CSharpToJava converter). */
public class SmtpException extends RuntimeException {
    private int hresult;
    public SmtpException() { super(); }
    public SmtpException(String message) { super(message); }
    public SmtpException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
