package io.github.ningpp.compat;

/** Replacement for System.Net.Mail.SmtpFailedRecipientsException (generated by CSharpToJava converter). */
public class SmtpFailedRecipientsException extends SmtpFailedRecipientException {
    public SmtpFailedRecipientsException() { super(); }
    public SmtpFailedRecipientsException(String message) { super(message); }
    public SmtpFailedRecipientsException(String message, Throwable cause) { super(message, cause); }
}
