package io.github.ningpp.compat;

/** Replacement for System.Net.Mail.SmtpException (generated by CSharpToJava converter). */
public class SmtpException extends RuntimeException {
    public SmtpException() { super(); }
    public SmtpException(String message) { super(message); }
    public SmtpException(String message, Throwable cause) { super(message, cause); }
}
