package io.github.ningpp.compat;

/** Replacement for System.Net.Sockets.SocketException (generated by CSharpToJava converter). */
public class SocketException extends RuntimeException {
    public SocketException() { super(); }
    public SocketException(String message) { super(message); }
    public SocketException(String message, Throwable cause) { super(message, cause); }
}
