package io.github.ningpp.compat;

/** Replacement for System.Net.Sockets.SocketException (generated by CSharpToJava converter). */
public class SocketException extends RuntimeException {
    private int hresult;
    public SocketException() { super(); }
    public SocketException(String message) { super(message); }
    public SocketException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
