package io.github.ningpp.compat;

import java.util.*;

/**
 * C# SortedList&lt;TKey, TValue&gt; compat.
 * Wraps TreeMap for sorted key-value storage with index-based access.
 * Generated by CSharpToJava converter.
 */
public class SortedList<K extends Comparable<K>, V> {
    private final TreeMap<K, V> map;

    public SortedList() {
        this.map = new TreeMap<>();
    }

    public SortedList(Comparator<K> comparer) {
        this.map = new TreeMap<>(comparer);
    }

    public SortedList(Map<K, V> map) {
        this.map = new TreeMap<>(map);
    }

    // ---- Core (delegate to TreeMap) ----

    public int size() {
        return map.size();
    }

    public boolean isEmpty() {
        return map.isEmpty();
    }

    public boolean containsKey(K key) {
        return map.containsKey(key);
    }

    public boolean containsValue(V value) {
        return map.containsValue(value);
    }

    public V get(K key) {
        return map.get(key);
    }

    public V put(K key, V value) {
        return map.put(key, value);
    }

    public V remove(K key) {
        return map.remove(key);
    }

    public void clear() {
        map.clear();
    }

    public void putAll(Map<K, V> m) {
        map.putAll(m);
    }

    public Comparator<? super K> comparator() {
        return map.comparator();
    }

    public Set<Map.Entry<K, V>> entrySet() {
        return map.entrySet();
    }

    public Set<K> keySet() {
        return map.keySet();
    }

    public void forEach(java.util.function.BiConsumer<K, V> action) {
        map.forEach(action);
    }

    // ---- Index-based access ----

    public List<K> keys() {
        return new ArrayList<>(map.keySet());
    }

    public List<V> values() {
        return new ArrayList<>(map.values());
    }

    public K getKeyAtIndex(int index) {
        return keys().get(index);
    }

    public V getValueAtIndex(int index) {
        return values().get(index);
    }

    public int indexOfKey(K key) {
        int i = 0;
        for (K k : map.keySet()) {
            if (Objects.equals(k, key)) return i;
            i++;
        }
        return -1;
    }

    public int indexOfValue(V value) {
        int i = 0;
        for (V v : map.values()) {
            if (Objects.equals(v, value)) return i;
            i++;
        }
        return -1;
    }

    // ---- Extended ----

    public boolean tryGetValue(K key, ObjectHolder<V> holder) {
        V val = map.get(key);
        if (val != null || map.containsKey(key)) {
            holder.value = val;
            return true;
        }
        return false;
    }

    public void removeAt(int index) {
        K key = getKeyAtIndex(index);
        map.remove(key);
    }

    public int capacity() {
        return size();
    }

    public void ensureCapacity(int capacity) {
        // No-op: TreeMap has no capacity concept
    }
}
