package io.github.ningpp.compat;

import java.util.Arrays;

/**
 * Lightweight array-slice container (generated by CSharpToJava converter).
 * Does not simulate C# ref-struct lifetime semantics.
 */
public final class Span<T> {
    private final T[] array;
    private final int offset;
    private final int length;

    public Span(T[] array) {
        this.array = array;
        this.offset = 0;
        this.length = array.length;
    }

    public Span(T[] array, int offset, int length) {
        if (offset < 0 || length < 0 || offset + length > array.length) {
            throw new IndexOutOfBoundsException(
                "offset=" + offset + ", length=" + length + ", arrayLength=" + array.length);
        }
        this.array = array;
        this.offset = offset;
        this.length = length;
    }

    public int length() {
        return length;
    }

    public T get(int index) {
        if (index < 0 || index >= length) {
            throw new IndexOutOfBoundsException("index=" + index + ", length=" + length);
        }
        return array[offset + index];
    }

    public void set(int index, T value) {
        if (index < 0 || index >= length) {
            throw new IndexOutOfBoundsException("index=" + index + ", length=" + length);
        }
        array[offset + index] = value;
    }

    public Span<T> slice(int start) {
        return slice(start, length - start);
    }

    public Span<T> slice(int start, int len) {
        if (start < 0 || len < 0 || start + len > length) {
            throw new IndexOutOfBoundsException(
                "start=" + start + ", len=" + len + ", length=" + length);
        }
        return new Span<>(array, offset + start, len);
    }

    T[] getArray() {
        return array;
    }

    int getOffset() {
        return offset;
    }

    public void clear() {
        Arrays.fill(array, offset, offset + length, null);
    }

    public T[] toArray() {
        return Arrays.copyOfRange(array, offset, offset + length);
    }
}
