package io.github.ningpp.compat;

import java.util.Arrays;

/**
 * Lightweight array-slice container (generated by CSharpToJava converter).
 * Does not simulate C# ref-struct lifetime semantics.
 */
public final class Span<T> {
    private final Object array;
    private final int offset;
    private final int length;

    public Span(T[] array) {
        this.array = array;
        this.offset = 0;
        this.length = array.length;
    }

    public Span(byte[] array) {
        this.array = array;
        this.offset = 0;
        this.length = array.length;
    }

    public Span(T[] array, int offset, int length) {
        if (offset < 0 || length < 0 || offset + length > array.length) {
            throw new IndexOutOfBoundsException(
                "offset=" + offset + ", length=" + length + ", arrayLength=" + array.length);
        }
        this.array = array;
        this.offset = offset;
        this.length = length;
    }

    public Span(byte[] array, int offset, int length) {
        if (offset < 0 || length < 0 || offset + length > array.length) {
            throw new IndexOutOfBoundsException(
                "offset=" + offset + ", length=" + length + ", arrayLength=" + array.length);
        }
        this.array = array;
        this.offset = offset;
        this.length = length;
    }

    public int length() {
        return length;
    }

    public T get(int index) {
        if (index < 0 || index >= length) {
            throw new IndexOutOfBoundsException("index=" + index + ", length=" + length);
        }
        if (array instanceof byte[] bytes) {
            @SuppressWarnings("unchecked")
            T value = (T) java.lang.Integer.valueOf(bytes[offset + index] & 0xFF);
            return value;
        }
        @SuppressWarnings("unchecked")
        T value = ((T[]) array)[offset + index];
        return value;
    }

    public void set(int index, T value) {
        if (index < 0 || index >= length) {
            throw new IndexOutOfBoundsException("index=" + index + ", length=" + length);
        }
        if (array instanceof byte[] bytes) {
            bytes[offset + index] = (byte)(((Number) value).intValue() & 0xFF);
            return;
        }
        ((T[]) array)[offset + index] = value;
    }

    public Span<T> slice(int start) {
        return slice(start, length - start);
    }

    public Span<T> slice(int start, int len) {
        if (start < 0 || len < 0 || start + len > length) {
            throw new IndexOutOfBoundsException(
                "start=" + start + ", len=" + len + ", length=" + length);
        }
        if (array instanceof byte[] bytes) {
            return new Span<>(bytes, offset + start, len);
        }
        return new Span<>((T[]) array, offset + start, len);
    }

    Object getArray() {
        return array;
    }

    int getOffset() {
        return offset;
    }

    public void clear() {
        Object fillValue = getDefaultValue();
        if (array instanceof byte[] bytes) {
            Arrays.fill(bytes, offset, offset + length, (byte)0);
            return;
        }
        Arrays.fill((T[]) array, offset, offset + length, (T) fillValue);
    }

    @SuppressWarnings("unchecked")
    private Object getDefaultValue() {
        // C# Span<T>.Clear() fills with default(T): 0 for numeric types, false for boolean, null for references
        if (array instanceof byte[]) return Integer.valueOf(0);
        if (array instanceof Short[]) return Short.valueOf((short)0);
        if (array instanceof Integer[]) return java.lang.Integer.valueOf(0);
        if (array instanceof Long[]) return Long.valueOf(0L);
        if (array instanceof Byte[]) return Byte.valueOf((byte)0);
        if (array instanceof Float[]) return Float.valueOf(0.0f);
        if (array instanceof Double[]) return Double.valueOf(0.0d);
        if (array instanceof Character[]) return Character.valueOf('\0');
        if (array instanceof Boolean[]) return Boolean.FALSE;
        return null;
    }

    public T[] toArray() {
        if (array instanceof byte[] bytes) {
            @SuppressWarnings("unchecked")
            T[] copy = (T[]) new Integer[length];
            for (int i = 0; i < length; i++) {
                copy[i] = (T) java.lang.Integer.valueOf(bytes[offset + i] & 0xFF);
            }
            return copy;
        }
        return Arrays.copyOfRange((T[]) array, offset, offset + length);
    }

    @Override
    public String toString() {
        if (array instanceof Character[] chars) {
            StringBuilder sb = new StringBuilder(length);
            for (int i = 0; i < length; i++) {
                sb.append(chars[offset + i]);
            }
            return sb.toString();
        }
        return super.toString();
    }
}
