package io.github.ningpp.compat;

/** Replacement for System.Data.SqlTypes.SqlAlreadyFilledException (generated by CSharpToJava converter). */
public class SqlAlreadyFilledException extends SqlTypeException {
    public SqlAlreadyFilledException() { super(); }
    public SqlAlreadyFilledException(String message) { super(message); }
    public SqlAlreadyFilledException(String message, Throwable cause) { super(message, cause); }
}
