package io.github.ningpp.compat;

/** Replacement for System.Data.SqlClient.SqlException (generated by CSharpToJava converter). */
public class SqlException extends RuntimeException {
    private int hresult;
    public SqlException() { super(); }
    public SqlException(String message) { super(message); }
    public SqlException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
