package io.github.ningpp.compat;

/** Replacement for System.Data.SqlClient.SqlException (generated by CSharpToJava converter). */
public class SqlException extends RuntimeException {
    public SqlException() { super(); }
    public SqlException(String message) { super(message); }
    public SqlException(String message, Throwable cause) { super(message, cause); }
}
