package io.github.ningpp.compat;

/** Replacement for System.Data.SqlTypes.SqlNotFilledException (generated by CSharpToJava converter). */
public class SqlNotFilledException extends SqlTypeException {
    public SqlNotFilledException() { super(); }
    public SqlNotFilledException(String message) { super(message); }
    public SqlNotFilledException(String message, Throwable cause) { super(message, cause); }
}
