package io.github.ningpp.compat;

/** Replacement for System.Data.SqlTypes.SqlNullValueException (generated by CSharpToJava converter). */
public class SqlNullValueException extends SqlTypeException {
    public SqlNullValueException() { super(); }
    public SqlNullValueException(String message) { super(message); }
    public SqlNullValueException(String message, Throwable cause) { super(message, cause); }
}
