package io.github.ningpp.compat;

/** Replacement for System.Data.SqlTypes.SqlTypeException (generated by CSharpToJava converter). */
public class SqlTypeException extends SystemException {
    public SqlTypeException() { super(); }
    public SqlTypeException(String message) { super(message); }
    public SqlTypeException(String message, Throwable cause) { super(message, cause); }
}
