package io.github.ningpp.compat;

/** Replacement for System.Data.SqlTypes.SqlTruncateException (generated by CSharpToJava converter). */
public class SqlTruncateException extends SqlTypeException {
    public SqlTruncateException() { super(); }
    public SqlTruncateException(String message) { super(message); }
    public SqlTruncateException(String message, Throwable cause) { super(message, cause); }
}
