package io.github.ningpp.compat;

/** Stopwatch helper class (generated by CSharpToJava converter, replacing System.Diagnostics.Stopwatch). */
public final class StopwatchHelper {
    private long startNanos;
    private long elapsedNanos;
    private boolean running;

    public StopwatchHelper() {}

    public static StopwatchHelper startNew() {
        StopwatchHelper sw = new StopwatchHelper();
        sw.start();
        return sw;
    }

    public void start() {
        if (!running) {
            startNanos = System.nanoTime();
            running = true;
        }
    }

    public void stop() {
        if (running) {
            elapsedNanos += System.nanoTime() - startNanos;
            running = false;
        }
    }

    public void reset() {
        elapsedNanos = 0;
        running = false;
    }

    public void restart() {
        reset();
        start();
    }

    public CSharpTimeSpan getElapsed() {
        long elapsed = elapsedNanos;
        if (running) elapsed += System.nanoTime() - startNanos;
        return CSharpTimeSpan.fromTicks(elapsed / 100L);
    }

    public long getElapsedMilliseconds() {
        long elapsed = elapsedNanos;
        if (running) elapsed += System.nanoTime() - startNanos;
        return elapsed / 1_000_000L;
    }

    public boolean isRunning() { return running; }
}
