package io.github.ningpp.compat;

import java.util.Locale;

/** String utilities (generated by CSharpToJava converter, replacing System.String static methods). */
public class StringHelper {
    public static String concat(Object... values) {
        if (values == null || values.length == 0) {
            return "";
        }

        StringBuilder builder = new StringBuilder();
        for (Object value : values) {
            appendConcatValue(builder, value);
        }
        return builder.toString();
    }
    public static boolean isNullOrEmpty(String s) {
        return s == null || s.isEmpty();
    }
    public static boolean isNullOrWhiteSpace(String s) {
        return s == null || s.trim().isEmpty();
    }
    /** Mirrors C# String.Compare(s1, s2) */
    public static int compare(String s1, String s2) {
        if (s1 == null && s2 == null) return 0;
        if (s1 == null) return -1;
        if (s2 == null) return  1;
        return s1.compareTo(s2);
    }
    /** Mirrors C# String.Compare(s1, s2, ignoreCase) */
    public static int compare(String s1, String s2, boolean ignoreCase) {
        if (s1 == null && s2 == null) return 0;
        if (s1 == null) return -1;
        if (s2 == null) return  1;
        return ignoreCase ? s1.compareToIgnoreCase(s2) : s1.compareTo(s2);
    }
    /** Mirrors C# String.Compare(s1, s2, ignoreCase, culture) */
    public static int compare(String s1, String s2, boolean ignoreCase, Object culture) {
        return compare(s1, s2, ignoreCase);
    }
    /** Mirrors C# String.Compare(s1, s2, StringComparison) */
    public static int compare(String s1, String s2, int comparison) {
        return compare(s1, s2, comparison == 1 || comparison == 3 || comparison == 5);
    }
    /** Mirrors C# String.Compare(s1, s2, StringComparison) - accepts mapped enum */
    public static int compare(String s1, String s2, StringComparison comparison) {
        return compare(s1, s2, comparison == StringComparison.CurrentCultureIgnoreCase
            || comparison == StringComparison.InvariantCultureIgnoreCase
            || comparison == StringComparison.OrdinalIgnoreCase);
    }
    /** Mirrors C# String.CompareOrdinal(strA, strB) */
    public static int compareOrdinal(String strA, String strB) {
        if (strA == null && strB == null) return 0;
        if (strA == null) return -1;
        if (strB == null) return  1;
        return strA.compareTo(strB);
    }
    /** Mirrors C# String.CompareOrdinal(strA, indexA, strB, indexB, length) */
    public static int compareOrdinal(String strA, int indexA, String strB, int indexB, int length) {
        if (strA == null || strB == null) {
            if (strA == null && strB == null) return 0;
            return strA == null ? -1 : 1;
        }
        String subA = strA.substring(indexA, Math.min(indexA + length, strA.length()));
        String subB = strB.substring(indexB, Math.min(indexB + length, strB.length()));
        return subA.compareTo(subB);
    }
    /** Mirrors C# String.Equals(a, b) */
    public static boolean equals(String s1, String s2) {
        if (s1 == null || s2 == null) {
            return s1 == s2;
        }
        return s1.equals(s2);
    }
    /** Mirrors C# String.Equals(a, b, StringComparison) via ignoreCase semantics. */
    public static boolean equals(String s1, String s2, boolean ignoreCase) {
        if (s1 == null || s2 == null) {
            return s1 == s2;
        }
        return ignoreCase ? s1.equalsIgnoreCase(s2) : s1.equals(s2);
    }
    /** Mirrors C# String.Equals(a, b, bool ignoreCase, CultureInfo culture) */
    public static boolean equals(String s1, String s2, boolean ignoreCase, Object culture) {
        return equals(s1, s2, ignoreCase);
    }
    /** Mirrors C# String.Equals(a, b, StringComparison) */
    public static boolean equals(String s1, String s2, int comparison) {
        return equals(s1, s2, comparison == 1 || comparison == 3 || comparison == 5);
    }
    /** Mirrors C# String.StartsWith(value, StringComparison) */
    public static boolean startsWith(String s, String prefix, boolean ignoreCase) {
        if (s == null || prefix == null) {
            return s == prefix;
        }
        if (prefix.length() > s.length()) {
            return false;
        }
        return ignoreCase
            ? s.regionMatches(true, 0, prefix, 0, prefix.length())
            : s.startsWith(prefix);
    }
    /** Mirrors C# String.StartsWith(value, StringComparison) */
    public static boolean startsWith(String s, String prefix, int comparison) {
        return startsWith(s, prefix, comparison == 1 || comparison == 3 || comparison == 5);
    }
    /** Mirrors C# String.EndsWith(value, StringComparison) */
    public static boolean endsWith(String s, String suffix, boolean ignoreCase) {
        if (s == null || suffix == null) {
            return s == suffix;
        }
        if (suffix.length() > s.length()) {
            return false;
        }
        if (ignoreCase) {
            return s.regionMatches(true, s.length() - suffix.length(), suffix, 0, suffix.length());
        }
        return s.endsWith(suffix);
    }
    /** Mirrors C# String.EndsWith(value, StringComparison) */
    public static boolean endsWith(String s, String suffix, int comparison) {
        return endsWith(s, suffix, comparison == 1 || comparison == 3 || comparison == 5);
    }
    /** Mirrors C# String.Contains(value, StringComparison) */
    public static boolean contains(String s, String value, boolean ignoreCase) {
        return indexOf(s, value, ignoreCase) >= 0;
    }
    /** Mirrors C# String.Contains(value, StringComparison) */
    public static boolean contains(String s, String value, int comparison) {
        return contains(s, value, comparison == 1 || comparison == 3 || comparison == 5);
    }
    /** Mirrors C# String.IndexOf(value, StringComparison) */
    public static int indexOf(String s, String value, boolean ignoreCase) {
        return ignoreCase
            ? s.toLowerCase(Locale.ROOT).indexOf(value.toLowerCase(Locale.ROOT))
            : s.indexOf(value);
    }
    /** Mirrors C# String.IndexOf(value, startIndex, StringComparison) */
    public static int indexOf(String s, String value, int startIndex, boolean ignoreCase) {
        return ignoreCase
            ? s.toLowerCase(Locale.ROOT).indexOf(value.toLowerCase(Locale.ROOT), startIndex)
            : s.indexOf(value, startIndex);
    }
    /** Mirrors C# String.IndexOf(value, StringComparison) */
    public static int indexOf(String s, String value, int comparison) {
        return indexOf(s, value, comparison == 1 || comparison == 3 || comparison == 5);
    }
    /** Mirrors C# String.IndexOf(value, startIndex, StringComparison) */
    public static int indexOf(String s, String value, int startIndex, int comparison) {
        return indexOf(s, value, startIndex, comparison == 1 || comparison == 3 || comparison == 5);
    }
    /** Mirrors C# String.LastIndexOf(value, StringComparison) */
    public static int lastIndexOf(String s, String value, boolean ignoreCase) {
        return ignoreCase
            ? s.toLowerCase(Locale.ROOT).lastIndexOf(value.toLowerCase(Locale.ROOT))
            : s.lastIndexOf(value);
    }
    /** Mirrors C# String.LastIndexOf(value, startIndex, StringComparison) */
    public static int lastIndexOf(String s, String value, int startIndex, boolean ignoreCase) {
        return ignoreCase
            ? s.toLowerCase(Locale.ROOT).lastIndexOf(value.toLowerCase(Locale.ROOT), startIndex)
            : s.lastIndexOf(value, startIndex);
    }
    /** Mirrors C# String.LastIndexOf(value, StringComparison) */
    public static int lastIndexOf(String s, String value, int comparison) {
        return lastIndexOf(s, value, comparison == 1 || comparison == 3 || comparison == 5);
    }
    /** Mirrors C# String.LastIndexOf(value, startIndex, StringComparison) */
    public static int lastIndexOf(String s, String value, int startIndex, int comparison) {
        return lastIndexOf(s, value, startIndex, comparison == 1 || comparison == 3 || comparison == 5);
    }

    // ==================== Insert ====================
    /** Mirrors C# String.Insert(startIndex, value) */
    public static String insert(String s, int startIndex, String value) {
        // C# behavior: throws ArgumentNullException if value is null
        if (value == null) {
            throw new NullPointerException("Value cannot be null");
        }
        // C# behavior: throws ArgumentOutOfRangeException if startIndex < 0 or > s.length()
        if (startIndex < 0 || startIndex > s.length()) {
            throw new IndexOutOfBoundsException("startIndex must be between 0 and " + s.length());
        }
        // C# behavior: if startIndex == s.length(), append to end
        return s.substring(0, startIndex) + value + s.substring(startIndex);
    }

    // ==================== Remove ====================
    /** Mirrors C# String.Remove(startIndex) */
    public static String remove(String s, int startIndex) {
        if (s == null) throw new NullPointerException("String cannot be null");
        if (startIndex < 0 || startIndex > s.length()) throw new StringIndexOutOfBoundsException("startIndex");
        return s.substring(0, startIndex);
    }

    /** Mirrors C# String.Remove(startIndex, count) */
    public static String remove(String s, int startIndex, int count) {
        if (s == null) throw new NullPointerException("String cannot be null");
        if (startIndex < 0 || startIndex > s.length()) throw new StringIndexOutOfBoundsException("startIndex");
        if (count < 0) throw new StringIndexOutOfBoundsException("count");
        if (startIndex + count > s.length()) throw new StringIndexOutOfBoundsException("startIndex + count");
        return s.substring(0, startIndex) + s.substring(startIndex + count);
    }

    // ==================== PadLeft ====================
    /** Mirrors C# String.PadLeft(totalWidth) */
    public static String padLeft(String s, int totalWidth) {
        return padLeft(s, totalWidth, ' ');
    }

    /** Mirrors C# String.PadLeft(totalWidth, paddingChar) */
    public static String padLeft(String s, int totalWidth, char paddingChar) {
        if (s == null) throw new NullPointerException("String cannot be null");
        if (totalWidth <= s.length()) return s;
        int padding = totalWidth - s.length();
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < padding; i++) {
            builder.append(paddingChar);
        }
        builder.append(s);
        return builder.toString();
    }

    // ==================== PadRight ====================
    /** Mirrors C# String.PadRight(totalWidth) */
    public static String padRight(String s, int totalWidth) {
        return padRight(s, totalWidth, ' ');
    }

    /** Mirrors C# String.PadRight(totalWidth, paddingChar) */
    public static String padRight(String s, int totalWidth, char paddingChar) {
        if (s == null) throw new NullPointerException("String cannot be null");
        if (totalWidth <= s.length()) return s;
        int padding = totalWidth - s.length();
        StringBuilder builder = new StringBuilder(s);
        for (int i = 0; i < padding; i++) {
            builder.append(paddingChar);
        }
        return builder.toString();
    }

    // ==================== TrimStart ====================
    /** Mirrors C# String.TrimStart() */
    public static String trimStart(String s) {
        if (s == null) return null;
        int start = 0;
        while (start < s.length() && Character.isWhitespace(s.charAt(start))) {
            start++;
        }
        return s.substring(start);
    }

    /** Mirrors C# String.TrimStart(trimChar) */
    public static String trimStart(String s, char trimChar) {
        if (s == null) return null;
        int start = 0;
        while (start < s.length() && s.charAt(start) == trimChar) {
            start++;
        }
        return s.substring(start);
    }

    // ==================== TrimEnd ====================
    /** Mirrors C# String.TrimEnd() */
    public static String trimEnd(String s) {
        if (s == null) return null;
        int end = s.length() - 1;
        while (end >= 0 && Character.isWhitespace(s.charAt(end))) {
            end--;
        }
        return s.substring(0, end + 1);
    }

    /** Mirrors C# String.TrimEnd(trimChar) */
    public static String trimEnd(String s, char trimChar) {
        if (s == null) return null;
        int end = s.length() - 1;
        while (end >= 0 && s.charAt(end) == trimChar) {
            end--;
        }
        return s.substring(0, end + 1);
    }

    /** Mirrors C# String.Trim(trimChars) - trims characters in the array from both ends */
    public static String trim(String s, char[] trimChars) {
        if (s == null) return null;
        int start = 0, end = s.length() - 1;
        while (start <= end && contains(trimChars, s.charAt(start))) {
            start++;
        }
        while (end >= start && contains(trimChars, s.charAt(end))) {
            end--;
        }
        return s.substring(start, end + 1);
    }

    private static boolean contains(char[] chars, char c) {
        if (chars == null) return Character.isWhitespace(c);
        for (char ch : chars) {
            if (ch == c) return true;
        }
        return false;
    }

    // ==================== IndexOf (char overloads) ====================
    /** Mirrors C# String.IndexOf(value) for char */
    public static int indexOf(String s, char value) {
        if (s == null) return -1;
        return s.indexOf(value);
    }

    /** Mirrors C# String.IndexOf(value, startIndex) for char */
    public static int indexOf(String s, char value, int startIndex) {
        if (s == null) return -1;
        if (startIndex < 0 || startIndex > s.length()) throw new StringIndexOutOfBoundsException("startIndex");
        return s.indexOf(value, startIndex);
    }

    /** Mirrors C# String.IndexOf(value, startIndex, count) for char */
    public static int indexOf(String s, char value, int startIndex, int count) {
        if (s == null) return -1;
        if (startIndex < 0 || startIndex > s.length()) throw new StringIndexOutOfBoundsException("startIndex");
        if (count < 0) throw new StringIndexOutOfBoundsException("count");
        int endIndex = startIndex + count;
        if (endIndex > s.length()) throw new StringIndexOutOfBoundsException("startIndex + count");
        String sub = s.substring(startIndex, endIndex);
        return sub.indexOf(value) + (sub.indexOf(value) >= 0 ? startIndex : 0);
    }

    // ==================== LastIndexOf (char overloads) ====================
    /** Mirrors C# String.LastIndexOf(value) for char */
    public static int lastIndexOf(String s, char value) {
        if (s == null) return -1;
        return s.lastIndexOf(value);
    }

    /** Mirrors C# String.LastIndexOf(value, startIndex) for char */
    public static int lastIndexOf(String s, char value, int startIndex) {
        if (s == null) return -1;
        if (startIndex < 0 || startIndex >= s.length()) throw new StringIndexOutOfBoundsException("startIndex");
        return s.lastIndexOf(value, startIndex);
    }

    /** Mirrors C# String.LastIndexOf(value, startIndex, count) for char */
    public static int lastIndexOf(String s, char value, int startIndex, int count) {
        if (s == null) return -1;
        if (startIndex < 0 || startIndex >= s.length()) throw new StringIndexOutOfBoundsException("startIndex");
        if (count < 0) throw new StringIndexOutOfBoundsException("count");
        int endIndex = startIndex - count + 1;
        if (endIndex < 0) endIndex = 0;
        String sub = s.substring(endIndex, startIndex + 1);
        int result = sub.lastIndexOf(value);
        return result >= 0 ? result + endIndex : -1;
    }

    // ==================== Copy ====================
    /** Mirrors C# String.Copy(str) */
    public static String copy(String str) {
        if (str == null) throw new NullPointerException("String cannot be null");
        return new String(str); // Create a new String instance
    }

    // ==================== IndexOfAny / LastIndexOfAny ====================
    /** Mirrors C# String.IndexOfAny(anyOf) */
    public static int indexOfAny(String s, char[] anyOf) {
        if (s == null || anyOf == null) return -1;
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            for (char ch : anyOf) {
                if (c == ch) return i;
            }
        }
        return -1;
    }

    /** Mirrors C# String.IndexOfAny(anyOf, startIndex) */
    public static int indexOfAny(String s, char[] anyOf, int startIndex) {
        if (s == null || anyOf == null) return -1;
        if (startIndex < 0 || startIndex >= s.length()) throw new StringIndexOutOfBoundsException("startIndex");
        for (int i = startIndex; i < s.length(); i++) {
            char c = s.charAt(i);
            for (char ch : anyOf) {
                if (c == ch) return i;
            }
        }
        return -1;
    }

    /** Mirrors C# String.IndexOfAny(anyOf, startIndex, count) */
    public static int indexOfAny(String s, char[] anyOf, int startIndex, int count) {
        if (s == null || anyOf == null) return -1;
        if (startIndex < 0 || startIndex >= s.length()) throw new StringIndexOutOfBoundsException("startIndex");
        if (count < 0) throw new StringIndexOutOfBoundsException("count");
        int endIndex = Math.min(startIndex + count, s.length());
        for (int i = startIndex; i < endIndex; i++) {
            char c = s.charAt(i);
            for (char ch : anyOf) {
                if (c == ch) return i;
            }
        }
        return -1;
    }

    /** Mirrors C# String.LastIndexOfAny(anyOf) */
    public static int lastIndexOfAny(String s, char[] anyOf) {
        if (s == null || anyOf == null) return -1;
        for (int i = s.length() - 1; i >= 0; i--) {
            char c = s.charAt(i);
            for (char ch : anyOf) {
                if (c == ch) return i;
            }
        }
        return -1;
    }

    /** Mirrors C# String.LastIndexOfAny(anyOf, startIndex) */
    public static int lastIndexOfAny(String s, char[] anyOf, int startIndex) {
        if (s == null || anyOf == null) return -1;
        if (startIndex < 0 || startIndex >= s.length()) throw new StringIndexOutOfBoundsException("startIndex");
        for (int i = startIndex; i >= 0; i--) {
            char c = s.charAt(i);
            for (char ch : anyOf) {
                if (c == ch) return i;
            }
        }
        return -1;
    }

    /** Mirrors C# String.LastIndexOfAny(anyOf, startIndex, count) */
    public static int lastIndexOfAny(String s, char[] anyOf, int startIndex, int count) {
        if (s == null || anyOf == null) return -1;
        if (startIndex < 0 || startIndex >= s.length()) throw new StringIndexOutOfBoundsException("startIndex");
        if (count < 0) throw new StringIndexOutOfBoundsException("count");
        int endIndex = Math.max(startIndex - count + 1, 0);
        for (int i = startIndex; i >= endIndex; i--) {
            char c = s.charAt(i);
            for (char ch : anyOf) {
                if (c == ch) return i;
            }
        }
        return -1;
    }

    // ==================== Replace (char overload) ====================
    /** Mirrors C# String.Replace(oldChar, newChar) */
    public static String replace(String s, char oldChar, char newChar) {
        if (s == null) return null;
        return s.replace(oldChar, newChar);
    }

    // ==================== Clone ====================
    /** Mirrors C# String.Clone() */
    public static Object clone(String s) {
        return s; // String is immutable, return itself
    }

    // ==================== CompareTo ====================
    /** Mirrors C# String.CompareTo(obj) */
    public static int compareTo(String s, Object obj) {
        if (s == null) throw new NullPointerException("String cannot be null");
        if (obj == null) throw new NullPointerException("Object cannot be null");
        if (!(obj instanceof String)) throw new ClassCastException("Object must be of type String");
        return s.compareTo((String) obj);
    }

    // ==================== Intern / IsInterned ====================
    /** Mirrors C# String.Intern(str) */
    public static String intern(String str) {
        if (str == null) throw new NullPointerException("String cannot be null");
        return str.intern();
    }

    /** Mirrors C# String.IsInterned(str) */
    public static String isInterned(String str) {
        if (str == null) return null;
        String interned = str.intern();
        return interned == str ? interned : null; // Simplified check
    }

    // ==================== Normalize / IsNormalized ====================
    /** Mirrors C# String.Normalize() */
    public static String normalize(String s) {
        if (s == null) return null;
        return java.text.Normalizer.normalize(s, java.text.Normalizer.Form.NFC);
    }

    /** Mirrors C# String.Normalize(form) */
    public static String normalize(String s, int form) {
        if (s == null) return null;
        java.text.Normalizer.Form javaForm = convertToNormalizerForm(form);
        return java.text.Normalizer.normalize(s, javaForm);
    }

    /** Mirrors C# String.Normalize(Normalizer.Form) - accepts mapped enum directly */
    public static String normalize(String s, java.text.Normalizer.Form form) {
        if (s == null) return null;
        return java.text.Normalizer.normalize(s, form);
    }

    /** Mirrors C# String.IsNormalized() */
    public static boolean isNormalized(String s) {
        if (s == null) return false;
        return java.text.Normalizer.isNormalized(s, java.text.Normalizer.Form.NFC);
    }

    /** Mirrors C# String.IsNormalized(form) */
    public static boolean isNormalized(String s, int form) {
        if (s == null) return false;
        java.text.Normalizer.Form javaForm = convertToNormalizerForm(form);
        return java.text.Normalizer.isNormalized(s, javaForm);
    }

    /** Mirrors C# String.IsNormalized(Normalizer.Form) - accepts mapped enum directly */
    public static boolean isNormalized(String s, java.text.Normalizer.Form form) {
        if (s == null) return false;
        return java.text.Normalizer.isNormalized(s, form);
    }

    private static java.text.Normalizer.Form convertToNormalizerForm(int form) {
        // C# NormalizationForm: FormC=1, FormD=2, FormKC=5, FormKD=6
        switch (form) {
            case 1: return java.text.Normalizer.Form.NFC;
            case 2: return java.text.Normalizer.Form.NFD;
            case 5: return java.text.Normalizer.Form.NFKC;
            case 6: return java.text.Normalizer.Form.NFKD;
            default: return java.text.Normalizer.Form.NFC;
        }
    }

    // ==================== ReplaceLineEndings ====================
    /** Mirrors C# String.ReplaceLineEndings() */
    public static String replaceLineEndings(String s) {
        return replaceLineEndings(s, "\n");
    }

    /** Mirrors C# String.ReplaceLineEndings(replacementText) */
    public static String replaceLineEndings(String s, String replacementText) {
        if (s == null) return null;
        if (replacementText == null) throw new NullPointerException("replacementText cannot be null");
        return s.replaceAll("\\r\\n|\\r|\\n", replacementText);
    }

    // ==================== TryCopyTo ====================
    /** Mirrors C# String.TryCopyTo(destination) */
    public static boolean tryCopyTo(String s, char[] destination, int destinationIndex) {
        if (s == null) return false;
        if (destination == null) return false;
        if (destinationIndex < 0) return false;
        if (destinationIndex + s.length() > destination.length) return false;
        s.getChars(0, s.length(), destination, destinationIndex);
        return true;
    }

    // ==================== CopyTo ====================
    /**
     * Mirrors C# String.CopyTo(int sourceIndex, char[] destination, int destinationIndex, int count).
     * Copies a specified number of characters from a specified position in the string to a specified position in a Unicode character array.
     * @throws NullPointerException if destination is null
     * @throws IndexOutOfBoundsException if sourceIndex, destinationIndex, or count is negative,
     *         or if sourceIndex + count exceeds the string length,
     *         or if destinationIndex + count exceeds the destination length
     */
    public static void copyTo(String s, int sourceIndex, char[] destination, int destinationIndex, int count) {
        if (s == null) throw new NullPointerException("Source string cannot be null");
        if (destination == null) throw new NullPointerException("Destination array cannot be null");
        if (sourceIndex < 0) throw new IndexOutOfBoundsException("sourceIndex cannot be negative");
        if (destinationIndex < 0) throw new IndexOutOfBoundsException("destinationIndex cannot be negative");
        if (count < 0) throw new IndexOutOfBoundsException("count cannot be negative");
        if (sourceIndex + count > s.length()) throw new IndexOutOfBoundsException("sourceIndex + count exceeds string length");
        if (destinationIndex + count > destination.length) throw new IndexOutOfBoundsException("destinationIndex + count exceeds destination array length");
        s.getChars(sourceIndex, sourceIndex + count, destination, destinationIndex);
    }

    // ==================== Create ====================
    /**
     * Mirrors C# string.Create&lt;TState&gt;(int length, TState state, SpanAction&lt;char, TState&gt; action).
     * Creates a new string of the given length, then calls the action to fill a Span&lt;Character&gt; buffer.
     * Uses Character (boxed) instead of generic TState to avoid Java primitive type inference issues.
     */
    public static String createString(int length, Character state, java.util.function.BiConsumer<Span<Character>, Character> action) {
        Character[] buf = new Character[length];
        Span<Character> span = new Span<>(buf);
        action.accept(span, state);
        char[] chars = new char[length];
        for (int i = 0; i < length; i++) {
            chars[i] = buf[i];
        }
        return new String(chars);
    }

    // ==================== C#-style Format ====================
    /**
     * Formats a string using C#-style {N} placeholders, converting them to Java %s
     * format specifiers at runtime before delegating to String.format.
     * <p>
     * C# uses {0}, {1}, {0:G} style placeholders; Java uses %s, %d style.
     * This method handles the conversion so that resource strings containing
     * {0}-style placeholders work correctly with Java's String.format().
     *
     * @param format the format string with C#-style {N} placeholders
     * @param args   the arguments referenced by the placeholders
     * @return the formatted string
     */
    public static String formatCs(String format, Object... args) {
        return formatCs(Locale.ROOT, format, args);
    }

    /**
     * Formats a string using C#-style {N} placeholders, converting them to Java %s format.
     *
     * @param l      the locale to use for formatting
     * @param format the format string with C#-style {N} placeholders
     * @param args   the arguments referenced by the placeholders
     * @return the formatted string
     */
    public static String formatCs(Locale l, String format, Object... args) {
        if (format == null) {
            return null;
        }
        // Escape existing '%' to '%%' so they are treated as literal percent signs
        String escaped = format.replace("%", "%%");
        // Replace {N} and {N:specifier} placeholders with Java positional format.
        // C# format specifiers: x/X = hex, d = decimal, default = general
        // where N = C# index + 1. This preserves C# semantics where the same argument
        // can be referenced multiple times (e.g. "{0}/{0}" becomes "%1$s/%1$s").
        java.util.regex.Matcher matcher = java.util.regex.Pattern.compile("\\{(\\d+)(?::([^}]*?))?\\}").matcher(escaped);
        StringBuffer sb = new StringBuffer();
        while (matcher.find()) {
            int index = java.lang.Integer.parseInt(matcher.group(1)) + 1; // Java positions are 1-based
            String specifier = matcher.group(2); // may be null if no specifier
            String javaFormat;
            if (specifier != null) {
                // Parse C# format specifier
                String spec = specifier.trim().toLowerCase();
                if (spec.startsWith("x")) {
                    // Hexadecimal format: {0:x} -> %1$x, {0:X} -> %1$X
                    boolean upper = specifier.trim().startsWith("X");
                    javaFormat = "%" + index + "$" + (upper ? "X" : "x");
                } else if (spec.startsWith("d")) {
                    // Decimal format: {0:d} -> %1$d
                    javaFormat = "%" + index + "$d";
                } else if (spec.startsWith("f")) {
                    // Fixed-point format: {0:f} -> %1$f
                    javaFormat = "%" + index + "$f";
                } else if (spec.startsWith("e")) {
                    // Scientific format: {0:e} -> %1$e, {0:E} -> %1$E
                    boolean upper = specifier.trim().startsWith("E");
                    javaFormat = "%" + index + "$" + (upper ? "E" : "e");
                } else {
                    // Unknown specifier, fall back to string format
                    javaFormat = "%" + index + "$s";
                }
            } else {
                javaFormat = "%" + index + "$s";
            }
            matcher.appendReplacement(sb, java.util.regex.Matcher.quoteReplacement(javaFormat));
        }
        matcher.appendTail(sb);
        String converted = sb.toString();
        if (args == null || args.length == 0) {
            return String.format(l, converted);
        }
        // Convert Short args to unsigned int values to preserve C# ushort semantics.
        // In C#, ushort is unsigned (0-65535), but Java Short is signed (-32768 to 32767).
        // Without this conversion, (short)-1 would format as "ffffffff" instead of "ffff".
        for (int i = 0; i < args.length; i++) {
            if (args[i] instanceof Short s) {
                args[i] = s.intValue() & 0xFFFF;
            }
        }
        return String.format(l, converted, args);
    }

    private static void appendConcatValue(StringBuilder builder, Object value) {
        if (value == null) {
            return;
        }

        if (value instanceof Iterable<?> iterable) {
            for (Object item : iterable) {
                appendConcatValue(builder, item);
            }
            return;
        }

        if (value instanceof Object[] array) {
            for (Object item : array) {
                appendConcatValue(builder, item);
            }
            return;
        }

        builder.append(value);
    }
}
