package io.github.ningpp.compat;

/** Replacement for System.Data.StrongTypingException (generated by CSharpToJava converter). */
public class StrongTypingException extends DataException {
    public StrongTypingException() { super(); }
    public StrongTypingException(String message) { super(message); }
    public StrongTypingException(String message, Throwable cause) { super(message, cause); }
}
