package io.github.ningpp.compat;

/** Replacement for System.Threading.SynchronizationLockException (generated by CSharpToJava converter). */
public class SynchronizationLockException extends SystemException {
    public SynchronizationLockException() { super(); }
    public SynchronizationLockException(String message) { super(message); }
    public SynchronizationLockException(String message, Throwable cause) { super(message, cause); }
}
