package io.github.ningpp.compat;

/** Replacement for System.DirectoryServices.ActiveDirectory.SyncFromAllServersOperationException (generated by CSharpToJava converter). */
public class SyncFromAllServersOperationException extends ActiveDirectoryOperationException {
    public SyncFromAllServersOperationException() { super(); }
    public SyncFromAllServersOperationException(String message) { super(message); }
    public SyncFromAllServersOperationException(String message, Throwable cause) { super(message, cause); }
}
