package io.github.ningpp.compat;

/** Replacement for System.Data.SyntaxErrorException (generated by CSharpToJava converter). */
public class SyntaxErrorException extends InvalidExpressionException {
    public SyntaxErrorException() { super(); }
    public SyntaxErrorException(String message) { super(message); }
    public SyntaxErrorException(String message, Throwable cause) { super(message, cause); }
}
