package io.github.ningpp.compat;

/** Replacement for System.SystemException (generated by CSharpToJava converter). */
public class SystemException extends RuntimeException {
    public SystemException() { super(); }
    public SystemException(String message) { super(message); }
    public SystemException(String message, Throwable cause) { super(message, cause); }
}
