package io.github.ningpp.compat;

/** Replacement for System.SystemException (generated by CSharpToJava converter). */
public class SystemException extends RuntimeException {
    private int hresult;

    public SystemException() { super(); }
    public SystemException(String message) { super(message); }
    public SystemException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
