package io.github.ningpp.compat;

/** Replacement for System.Reflection.TargetInvocationException (generated by CSharpToJava converter). */
public class TargetInvocationException extends RuntimeException {
    public TargetInvocationException() { super(); }
    public TargetInvocationException(String message) { super(message); }
    public TargetInvocationException(String message, Throwable cause) { super(message, cause); }
}
