package io.github.ningpp.compat;

/** Replacement for System.Reflection.TargetException (generated by CSharpToJava converter). */
public class TargetException extends RuntimeException {
    private int hresult;
    public TargetException() { super(); }
    public TargetException(String message) { super(message); }
    public TargetException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
