package io.github.ningpp.compat;

/** Replacement for System.Reflection.TargetParameterCountException (generated by CSharpToJava converter). */
public class TargetParameterCountException extends RuntimeException {
    public TargetParameterCountException() { super(); }
    public TargetParameterCountException(String message) { super(message); }
    public TargetParameterCountException(String message, Throwable cause) { super(message, cause); }
}
