package io.github.ningpp.compat;

/** Replacement for System.Reflection.TargetParameterCountException (generated by CSharpToJava converter). */
public class TargetParameterCountException extends RuntimeException {
    private int hresult;
    public TargetParameterCountException() { super(); }
    public TargetParameterCountException(String message) { super(message); }
    public TargetParameterCountException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
