package io.github.ningpp.compat;

/** Replacement for System.Reflection.TargetException (generated by CSharpToJava converter). */
public class TargetException extends RuntimeException {
    public TargetException() { super(); }
    public TargetException(String message) { super(message); }
    public TargetException(String message, Throwable cause) { super(message, cause); }
}
