package io.github.ningpp.compat;

/** Replacement for System.Reflection.TargetInvocationException (generated by CSharpToJava converter). */
public class TargetInvocationException extends RuntimeException {
    private int hresult;
    public TargetInvocationException() { super(); }
    public TargetInvocationException(String message) { super(message); }
    public TargetInvocationException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
