package io.github.ningpp.compat;

/** Replacement for System.Threading.Tasks.TaskSchedulerException (generated by CSharpToJava converter). */
public class TaskSchedulerException extends RuntimeException {
    private int hresult;
    public TaskSchedulerException() { super(); }
    public TaskSchedulerException(String message) { super(message); }
    public TaskSchedulerException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
