package io.github.ningpp.compat;

/** Replacement for System.Threading.Tasks.TaskSchedulerException (generated by CSharpToJava converter). */
public class TaskSchedulerException extends RuntimeException {
    public TaskSchedulerException() { super(); }
    public TaskSchedulerException(String message) { super(message); }
    public TaskSchedulerException(String message, Throwable cause) { super(message, cause); }
}
