package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.StringManipulation.FlashExtractWrapper.TemplateParsing.TemplateParsingException (generated by CSharpToJava converter). */
public class TemplateParsingException extends RuntimeException {
    private int hresult;
    public TemplateParsingException() { super(); }
    public TemplateParsingException(String message) { super(message); }
    public TemplateParsingException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
