package io.github.ningpp.compat;

/** Replacement for Microsoft.PowerShell.Commands.StringManipulation.FlashExtractWrapper.TemplateParsing.TemplateParsingException (generated by CSharpToJava converter). */
public class TemplateParsingException extends RuntimeException {
    public TemplateParsingException() { super(); }
    public TemplateParsingException(String message) { super(message); }
    public TemplateParsingException(String message, Throwable cause) { super(message, cause); }
}
