package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.TerminateException (generated by CSharpToJava converter). */
public class TerminateException extends RuntimeException {
    private int hresult;
    public TerminateException() { super(); }
    public TerminateException(String message) { super(message); }
    public TerminateException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
