package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.TerminateException (generated by CSharpToJava converter). */
public class TerminateException extends RuntimeException {
    public TerminateException() { super(); }
    public TerminateException(String message) { super(message); }
    public TerminateException(String message, Throwable cause) { super(message, cause); }
}
