package io.github.ningpp.compat;

import java.util.Locale;

/**
 * Stub for System.Threading.Thread (generated by CSharpToJava converter).
 * Provides getCurrentCulture()/setCurrentCulture() used in C# thread-locale patterns.
 */
public class ThreadHelper {
    private static final ThreadHelper INSTANCE = new ThreadHelper();

    /** Mirrors Thread.CurrentThread (returns a ThreadHelper proxy). */
    public static ThreadHelper currentThread() { return INSTANCE; }

    /** Mirrors Thread.CurrentThread.CurrentCulture getter. */
    public CultureInfo getCurrentCulture() { return CultureInfo.getCurrentCulture(); }

    /** Mirrors Thread.CurrentThread.CurrentCulture setter with CultureInfo. */
    public void setCurrentCulture(CultureInfo culture) { /* locale-setting is global in JVM */ }

    /** Mirrors Thread.CurrentThread.CurrentCulture setter with Locale. */
    public void setCurrentCulture(Locale locale) { Locale.setDefault(locale); }

    /** Mirrors Thread.CurrentThread.CurrentCulture setter with Object (type-erased). */
    public void setCurrentCulture(Object culture) { /* no-op */ }

    /** Thread name (stub). */
    public String getName() { return java.lang.Thread.currentThread().getName(); }

    /** No-op join (stub). */
    public void join() throws InterruptedException { }

    /** Start (stub — not a real Thread). */
    public void start() { }

    /** Mirrors C# Thread.MemoryBarrier() using VarHandle.fullFence */
    public static void memoryBarrier() {
        java.lang.invoke.VarHandle.fullFence();
    }
}
