package io.github.ningpp.compat;

/** Replacement for System.Threading.ThreadStartException (generated by CSharpToJava converter). */
public class ThreadStartException extends SystemException {
    public ThreadStartException() { super(); }
    public ThreadStartException(String message) { super(message); }
    public ThreadStartException(String message, Throwable cause) { super(message, cause); }
}
