package io.github.ningpp.compat;

/** Replacement for System.Threading.ThreadInterruptedException (generated by CSharpToJava converter). */
public class ThreadInterruptedException extends SystemException {
    public ThreadInterruptedException() { super(); }
    public ThreadInterruptedException(String message) { super(message); }
    public ThreadInterruptedException(String message, Throwable cause) { super(message, cause); }
}
