package io.github.ningpp.compat;

/** Replacement for System.Threading.ThreadAbortException (generated by CSharpToJava converter). */
public class ThreadAbortException extends SystemException {
    public ThreadAbortException() { super(); }
    public ThreadAbortException(String message) { super(message); }
    public ThreadAbortException(String message, Throwable cause) { super(message, cause); }
}
