package io.github.ningpp.compat;

/** Replacement for System.TimeZoneNotFoundException (generated by CSharpToJava converter). */
public class TimeZoneNotFoundException extends RuntimeException {
    private int hresult;
    public TimeZoneNotFoundException() { super(); }
    public TimeZoneNotFoundException(String message) { super(message); }
    public TimeZoneNotFoundException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
