package io.github.ningpp.compat;

/** Replacement for System.TimeZoneNotFoundException (generated by CSharpToJava converter). */
public class TimeZoneNotFoundException extends RuntimeException {
    public TimeZoneNotFoundException() { super(); }
    public TimeZoneNotFoundException(String message) { super(message); }
    public TimeZoneNotFoundException(String message, Throwable cause) { super(message, cause); }
}
