package io.github.ningpp.compat;

/** Replacement for System.Diagnostics.TraceSwitch (generated by CSharpToJava converter). */
public class TraceSwitch {
    private final String displayName;
    private final String description;
    private int level;

    public TraceSwitch(String displayName, String description) {
        this.displayName = displayName;
        this.description = description;
    }

    public int getLevel() { return level; }
    public void setLevel(int value) { this.level = value; }
    public String getDisplayName() { return displayName; }
    public String getDescription() { return description; }

    public boolean getTraceError() { return level >= 1; }
    public boolean getTraceWarning() { return level >= 2; }
    public boolean getTraceInfo() { return level >= 3; }
    public boolean getTraceVerbose() { return level >= 4; }
}
