package io.github.ningpp.compat;

/** Replacement for System.Transactions.TransactionPromotionException (generated by CSharpToJava converter). */
public class TransactionPromotionException extends TransactionException {
    public TransactionPromotionException() { super(); }
    public TransactionPromotionException(String message) { super(message); }
    public TransactionPromotionException(String message, Throwable cause) { super(message, cause); }
}
