package io.github.ningpp.compat;

/** Replacement for System.Transactions.TransactionManagerCommunicationException (generated by CSharpToJava converter). */
public class TransactionManagerCommunicationException extends TransactionException {
    public TransactionManagerCommunicationException() { super(); }
    public TransactionManagerCommunicationException(String message) { super(message); }
    public TransactionManagerCommunicationException(String message, Throwable cause) { super(message, cause); }
}
