package io.github.ningpp.compat;

/** Replacement for System.Transactions.TransactionException (generated by CSharpToJava converter). */
public class TransactionException extends SystemException {
    public TransactionException() { super(); }
    public TransactionException(String message) { super(message); }
    public TransactionException(String message, Throwable cause) { super(message, cause); }
}
