package io.github.ningpp.compat;

/** Replacement for System.Transactions.TransactionAbortedException (generated by CSharpToJava converter). */
public class TransactionAbortedException extends TransactionException {
    public TransactionAbortedException() { super(); }
    public TransactionAbortedException(String message) { super(message); }
    public TransactionAbortedException(String message, Throwable cause) { super(message, cause); }
}
