package io.github.ningpp.compat;

/** Replacement for System.Transactions.TransactionInDoubtException (generated by CSharpToJava converter). */
public class TransactionInDoubtException extends TransactionException {
    public TransactionInDoubtException() { super(); }
    public TransactionInDoubtException(String message) { super(message); }
    public TransactionInDoubtException(String message, Throwable cause) { super(message, cause); }
}
