package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.TypeTableLoadException (generated by CSharpToJava converter). */
public class TypeTableLoadException extends RuntimeException {
    public TypeTableLoadException() { super(); }
    public TypeTableLoadException(String message) { super(message); }
    public TypeTableLoadException(String message, Throwable cause) { super(message, cause); }
}
