package io.github.ningpp.compat;

/** Replacement for System.TypeAccessException (generated by CSharpToJava converter). */
public class TypeAccessException extends ClassNotFoundException {
    public TypeAccessException() { super(); }
    public TypeAccessException(String message) { super(message); }
    public TypeAccessException(String message, Throwable cause) { super(message, cause); }
}
