package io.github.ningpp.compat;

/** Replacement for System.Data.TypedDataSetGeneratorException (generated by CSharpToJava converter). */
public class TypedDataSetGeneratorException extends DataException {
    public TypedDataSetGeneratorException() { super(); }
    public TypedDataSetGeneratorException(String message) { super(message); }
    public TypedDataSetGeneratorException(String message, Throwable cause) { super(message, cause); }
}
