package io.github.ningpp.compat;

/** Replacement for System.TypeUnloadedException (generated by CSharpToJava converter). */
public class TypeUnloadedException extends SystemException {
    public TypeUnloadedException() { super(); }
    public TypeUnloadedException(String message) { super(message); }
    public TypeUnloadedException(String message, Throwable cause) { super(message, cause); }
}
