package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.Runspaces.TypeTableLoadException (generated by CSharpToJava converter). */
public class TypeTableLoadException extends RuntimeException {
    private int hresult;
    public TypeTableLoadException() { super(); }
    public TypeTableLoadException(String message) { super(message); }
    public TypeTableLoadException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
