package io.github.ningpp.compat;

/** Replacement for System.UriFormatException (generated by CSharpToJava converter). */
public class UriFormatException extends IllegalArgumentException {
    public UriFormatException() { super(); }
    public UriFormatException(String message) { super(message); }
    public UriFormatException(String message, Throwable cause) { super(message, cause); }
}
