package io.github.ningpp.compat;

/** Replacement for System.UriFormatException (generated by CSharpToJava converter). */
public class UriFormatException extends IllegalArgumentException {
    private int hresult;
    public UriFormatException() { super(); }
    public UriFormatException(String message) { super(message); }
    public UriFormatException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
