package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.ValidationMetadataException (generated by CSharpToJava converter). */
public class ValidationMetadataException extends MetadataException {
    public ValidationMetadataException() { super(); }
    public ValidationMetadataException(String message) { super(message); }
    public ValidationMetadataException(String message, Throwable cause) { super(message, cause); }
}
