package io.github.ningpp.compat;

/** Replacement for System.Data.VersionNotFoundException (generated by CSharpToJava converter). */
public class VersionNotFoundException extends DataException {
    public VersionNotFoundException() { super(); }
    public VersionNotFoundException(String message) { super(message); }
    public VersionNotFoundException(String message, Throwable cause) { super(message, cause); }
}
