package io.github.ningpp.compat;

/** Replacement for System.Threading.WaitHandleCannotBeOpenedException (generated by CSharpToJava converter). */
public class WaitHandleCannotBeOpenedException extends RuntimeException {
    public WaitHandleCannotBeOpenedException() { super(); }
    public WaitHandleCannotBeOpenedException(String message) { super(message); }
    public WaitHandleCannotBeOpenedException(String message, Throwable cause) { super(message, cause); }
}
