package io.github.ningpp.compat;

/** Replacement for System.Threading.WaitHandleCannotBeOpenedException (generated by CSharpToJava converter). */
public class WaitHandleCannotBeOpenedException extends RuntimeException {
    private int hresult;
    public WaitHandleCannotBeOpenedException() { super(); }
    public WaitHandleCannotBeOpenedException(String message) { super(message); }
    public WaitHandleCannotBeOpenedException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
