package io.github.ningpp.compat;

/** Replacement for System.ComponentModel.WarningException (generated by CSharpToJava converter). */
public class WarningException extends SystemException {
    public WarningException() { super(); }
    public WarningException(String message) { super(message); }
    public WarningException(String message, Throwable cause) { super(message, cause); }
}
