package io.github.ningpp.compat;

/** Replacement for System.WeakReference (generated by CSharpToJava converter). */
public class WeakReference {
    private java.lang.ref.WeakReference<Object> ref;

    public WeakReference(Object target) {
        this.ref = new java.lang.ref.WeakReference<>(target);
    }

    public boolean getIsAlive() {
        return ref.get() != null;
    }

    public Object getTarget() {
        return ref.get();
    }

    public void setTarget(Object value) {
        this.ref = new java.lang.ref.WeakReference<>(value);
    }
}
