package io.github.ningpp.compat;

/** Replacement for System.Net.WebException (generated by CSharpToJava converter). */
public class WebException extends IllegalStateException {
    private int hresult;
    public WebException() { super(); }
    public WebException(String message) { super(message); }
    public WebException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
