package io.github.ningpp.compat;

/** Replacement for System.Net.WebException (generated by CSharpToJava converter). */
public class WebException extends IllegalStateException {
    public WebException() { super(); }
    public WebException(String message) { super(message); }
    public WebException(String message, Throwable cause) { super(message, cause); }
}
