package io.github.ningpp.compat;

/** Replacement for System.Net.WebSockets.WebSocketException (generated by CSharpToJava converter). */
public class WebSocketException extends RuntimeException {
    private int hresult;
    public WebSocketException() { super(); }
    public WebSocketException(String message) { super(message); }
    public WebSocketException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
