package io.github.ningpp.compat;

/** Replacement for System.Net.WebSockets.WebSocketException (generated by CSharpToJava converter). */
public class WebSocketException extends RuntimeException {
    public WebSocketException() { super(); }
    public WebSocketException(String message) { super(message); }
    public WebSocketException(String message, Throwable cause) { super(message, cause); }
}
