package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.WildcardPatternException (generated by CSharpToJava converter). */
public class WildcardPatternException extends RuntimeException {
    public WildcardPatternException() { super(); }
    public WildcardPatternException(String message) { super(message); }
    public WildcardPatternException(String message, Throwable cause) { super(message, cause); }
}
