package io.github.ningpp.compat;

/** Replacement for System.Management.Automation.WildcardPatternException (generated by CSharpToJava converter). */
public class WildcardPatternException extends RuntimeException {
    private int hresult;
    public WildcardPatternException() { super(); }
    public WildcardPatternException(String message) { super(message); }
    public WildcardPatternException(String message, Throwable cause) { super(message, cause); }

    public int getHResult() { return hresult; }
    public void setHResult(int value) { this.hresult = value; }
}
