package io.github.ningpp.compat;

/** Replacement for System.Xml.XmlConvert (generated by CSharpToJava converter). */
public class XmlConvert {
    public static String toString(double  value) { return Double.toString(value); }
    public static String toString(float   value) { return Float.toString(value); }
    public static String toString(int     value) { return Integer.toString(value); }
    public static String toString(long    value) { return Long.toString(value); }
    public static String toString(boolean value) { return Boolean.toString(value); }
    public static double  toDouble(String s)     { return Double.parseDouble(s); }
    public static float   toSingle(String s)     { return Float.parseFloat(s); }
    public static int     toInt32(String s)      { return Integer.parseInt(s); }
    public static long    toInt64(String s)      { return Long.parseLong(s); }
    public static boolean toBoolean(String s)    { return Boolean.parseBoolean(s); }
}
