package io.github.ningpp.compat;

/** Replacement for System.Xml.XmlException (generated by CSharpToJava converter). */
public class XmlException extends SystemException {
    public XmlException() { super(); }
    public XmlException(String message) { super(message); }
    public XmlException(String message, Throwable cause) { super(message, cause); }
}
