package io.github.ningpp.compat;

import javax.xml.stream.XMLStreamConstants;

/** Replacement for System.Xml.XmlNodeType (generated by CSharpToJava converter). */
public class XmlNodeType {
    public static final int None            = 0;
    public static final int Element         = XMLStreamConstants.START_ELEMENT;
    public static final int Attribute       = 10;
    public static final int Text            = XMLStreamConstants.CHARACTERS;
    public static final int CDATA           = XMLStreamConstants.CDATA;
    public static final int EndElement      = XMLStreamConstants.END_ELEMENT;
    public static final int EndDocument     = XMLStreamConstants.END_DOCUMENT;
    public static final int Comment         = XMLStreamConstants.COMMENT;
    public static final int ProcessingInstruction = XMLStreamConstants.PROCESSING_INSTRUCTION;

    /** Static getter — converter generates XmlNodeType.getNone() for enum-like access. */
    public static int getNone()             { return None; }
    public static int getElement()          { return Element; }
    public static int getAttribute()        { return Attribute; }
    public static int getText()             { return Text; }
    public static int getCDATA()            { return CDATA; }
    public static int getEndElement()       { return EndElement; }
    public static int getEndDocument()      { return EndDocument; }
    public static int getComment()          { return Comment; }
    public static int getProcessingInstruction() { return ProcessingInstruction; }
}
