package io.github.ningpp.compat;

/** Replacement for System.Xml.XmlReaderSettings (generated by CSharpToJava converter). */
public class XmlReaderSettings {
    // Public field aliases used by generated C#-style property access.
    public boolean IgnoreWhitespace = false;
    public boolean IgnoreComments = false;
    public boolean CheckCharacters = true;
    public boolean isIgnoreWhitespace()          { return IgnoreWhitespace; }
    public void    setIgnoreWhitespace(boolean v) { IgnoreWhitespace = v; }
    public boolean isIgnoreComments()           { return IgnoreComments; }
    public void    setIgnoreComments(boolean v) { IgnoreComments = v; }
    public boolean isCheckCharacters()           { return CheckCharacters; }
    public void    setCheckCharacters(boolean v)  { CheckCharacters = v; }
}
