package io.github.ningpp.compat;

import java.io.InputStream;
import java.io.Reader;
import javax.xml.stream.*;
import javax.xml.stream.util.StreamReaderDelegate;

/** Replacement for System.Xml.XmlReader backed by StAX (generated by CSharpToJava converter). */
public class XmlReader implements AutoCloseable {
    protected static XMLStreamReader reader;
    /** -1 = on element, 0+ = on attribute at given index (simulates MoveToFirstAttribute navigation) */
    private static int attributeIndex = -1;
    // C#-style static property aliases frequently emitted by the converter.
    public static int NodeType = XmlNodeType.getNone();
    public static boolean IsEmptyElement = false;
    public static String Name = "";
    public static String Value = "";
    public static int ReadState = 0;

    protected XmlReader() {}

    protected XmlReader(XMLStreamReader reader) {
        XmlReader.reader = reader;
    }

    /** Whitespace-skipping StAX delegate with look-ahead empty-element detection.
     *  Mimics C# XmlReaderSettings.IgnoreWhitespace = true and C# XmlReader.IsEmptyElement.
     *  After returning a START_ELEMENT, peeks ahead: if the next meaningful event is END_ELEMENT,
     *  the element is empty — the END is consumed internally and isEmptyElement is set to true.
     *  Saved START_ELEMENT state (name, attributes) is returned via overridden accessors. */
    private static final class WhitespaceFilteringReader extends StreamReaderDelegate {
        /** true if the current START_ELEMENT is an empty/self-closing element (its END_ELEMENT was consumed) */
        boolean isEmptyElement = false;
        // Saved START_ELEMENT state (because look-ahead moves the underlying reader)
        private boolean hasSavedState = false;
        private String savedLocalName;
        private int savedAttrCount;
        private String[] savedAttrNames;
        private String[] savedAttrValues;
        // Buffered next event (from look-ahead when element is NOT empty)
        private boolean hasBuffered = false;
        private int bufferedEventType;
        WhitespaceFilteringReader(XMLStreamReader r) { super(r); }
        private boolean isSkippable(int ev) throws XMLStreamException {
            return (ev == XMLStreamConstants.CHARACTERS && super.isWhiteSpace())
                || ev == XMLStreamConstants.SPACE
                || ev == XMLStreamConstants.COMMENT;
        }
        @Override
        public int next() throws XMLStreamException {
            int ev;
            if (hasBuffered) {
                ev = bufferedEventType;
                hasBuffered = false;
            } else {
                do { ev = super.next(); } while (isSkippable(ev));
            }
            hasSavedState = false;
            isEmptyElement = false;
            if (ev == XMLStreamConstants.START_ELEMENT) {
                // Save state before look-ahead moves the underlying reader position
                savedLocalName = super.getLocalName();
                savedAttrCount = super.getAttributeCount();
                savedAttrNames = new String[savedAttrCount];
                savedAttrValues = new String[savedAttrCount];
                for (int i = 0; i < savedAttrCount; i++) {
                    savedAttrNames[i] = super.getAttributeLocalName(i);
                    savedAttrValues[i] = super.getAttributeValue(i);
                }
                hasSavedState = true;
                // Look ahead: is the next non-whitespace event END_ELEMENT?
                int peek;
                do { peek = super.next(); } while (isSkippable(peek));
                if (peek == XMLStreamConstants.END_ELEMENT) {
                    isEmptyElement = true; // END consumed; getIsEmptyElement() returns true
                } else {
                    hasBuffered = true;
                    bufferedEventType = peek;
                }
            }
            return ev;
        }
        @Override public String getLocalName() {
            return hasSavedState ? savedLocalName : super.getLocalName();
        }
        @Override public int getEventType() {
            return hasSavedState ? XMLStreamConstants.START_ELEMENT : super.getEventType();
        }
        @Override public boolean isStartElement() {
            return hasSavedState || super.isStartElement();
        }
        @Override public boolean isEndElement() {
            return !hasSavedState && super.isEndElement();
        }
        @Override public int getAttributeCount() {
            return hasSavedState ? savedAttrCount : super.getAttributeCount();
        }
        @Override public String getAttributeLocalName(int i) {
            return (hasSavedState && i >= 0 && i < savedAttrCount) ? savedAttrNames[i] : super.getAttributeLocalName(i);
        }
        @Override public String getAttributeValue(int i) {
            return (hasSavedState && i >= 0 && i < savedAttrCount) ? savedAttrValues[i] : super.getAttributeValue(i);
        }
        @Override public String getAttributeValue(String ns, String name) {
            if (hasSavedState) {
                for (int i = 0; i < savedAttrCount; i++) {
                    if (savedAttrNames[i].equals(name)) return savedAttrValues[i];
                }
                return null;
            }
            return super.getAttributeValue(ns, name);
        }
        @Override public String getElementText() throws XMLStreamException {
            if (isEmptyElement) {
                hasSavedState = false;
                isEmptyElement = false;
                return "";
            }
            StringBuilder sb = new StringBuilder();
            if (hasBuffered) {
                if (bufferedEventType == XMLStreamConstants.CHARACTERS || bufferedEventType == XMLStreamConstants.CDATA) {
                    sb.append(super.getText());
                }
                if (bufferedEventType == XMLStreamConstants.END_ELEMENT) {
                    hasBuffered = false;
                    hasSavedState = false;
                    return sb.toString();
                }
                hasBuffered = false;
                hasSavedState = false;
            } else {
                hasSavedState = false;
            }
            while (super.hasNext()) {
                int ev = super.next();
                if (ev == XMLStreamConstants.END_ELEMENT) return sb.toString();
                if (ev == XMLStreamConstants.CHARACTERS || ev == XMLStreamConstants.CDATA) {
                    sb.append(super.getText());
                }
            }
            throw new XMLStreamException("Unexpected end of document in getElementText");
        }
    }

    /** Factory — mirrors XmlReader.Create(source, settings) in C#. */
    public static XmlReader create(Object source, Object settings) {
        try {
            boolean ignoreWs = (settings instanceof XmlReaderSettings) && ((XmlReaderSettings) settings).isIgnoreWhitespace();
            XMLInputFactory factory = XMLInputFactory.newInstance();
            factory.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, false);
            factory.setProperty(XMLInputFactory.SUPPORT_DTD, false);
            if (source instanceof InputStream) {
                XMLStreamReader base = factory.createXMLStreamReader((InputStream) source);
                return new XmlReader(ignoreWs ? new WhitespaceFilteringReader(base) : base);
            } else if (source instanceof Reader) {
                XMLStreamReader base = factory.createXMLStreamReader((Reader) source);
                return new XmlReader(ignoreWs ? new WhitespaceFilteringReader(base) : base);
            } else if (source instanceof XmlReader) {
                if (ignoreWs && reader != null && !(reader instanceof WhitespaceFilteringReader)) {
                    reader = new WhitespaceFilteringReader(reader);
                }
                return (XmlReader) source;
            }
            throw new RuntimeException("Unsupported XmlReader source: " + (source == null ? "null" : source.getClass().getName()));
        } catch (XMLStreamException e) {
            throw new RuntimeException(e);
        }
    }

    /** Convenience overload used by converted code paths. */
    public static XmlReader create(Object source) {
        return create(source, null);
    }

    public static int getNodeType() {
        attributeIndex = -1;
        if (reader == null) return XmlNodeType.getNone();
        // C# XmlReader.NodeType returns None when ReadState is EndOfFile.
        // StAX reports END_DOCUMENT (8) for this state; map it to None (0)
        // to match C# semantics so loops like `while (!done)` can detect EOF.
        // Also check hasNext() as a fallback: if the stream is exhausted, return None.
        try {
            if (!reader.hasNext()) return XmlNodeType.getNone();
        } catch (Exception e) { return XmlNodeType.getNone(); }
        int eventType = reader.getEventType();
        if (eventType == XMLStreamConstants.END_DOCUMENT) return XmlNodeType.getNone();
        return eventType;
    }

    public static boolean isStartElement() {
        attributeIndex = -1;
        return reader != null && reader.isStartElement();
    }

    public static boolean isStartElement(String name) {
        attributeIndex = -1;
        return reader != null && reader.isStartElement()
            && name.equalsIgnoreCase(reader.getLocalName());
    }

    /** Returns true if the current START_ELEMENT is a self-closing/empty element (e.g. &lt;foo/&gt;). */
    public static boolean getIsEmptyElement() {
        return (reader instanceof WhitespaceFilteringReader) && ((WhitespaceFilteringReader) reader).isEmptyElement;
    }

    public static String getName() {
        try {
            if (reader == null) return "";
            if (attributeIndex >= 0) return reader.getAttributeLocalName(attributeIndex);
            return reader.getLocalName();
        }
        catch (Exception e) { return ""; }
    }

    public static String getValue() {
        try {
            if (reader == null) return "";
            if (attributeIndex >= 0) return reader.getAttributeValue(attributeIndex);
            return reader.getText();
        }
        catch (Exception e) { return ""; }
    }

    public static String getAttribute(String name) {
        return reader != null ? reader.getAttributeValue(null, name) : null;
    }

    public static boolean read() {
        try {
            if (reader == null || !reader.hasNext()) return false;
            attributeIndex = -1;
            reader.next();
            return true;
        } catch (XMLStreamException e) { return false; }
    }

    public static void readEndElement() {
        try {
            attributeIndex = -1;
            if (reader == null) return;
            // If on an empty element whose END was consumed by look-ahead, just advance.
            if (reader.isStartElement() && reader instanceof WhitespaceFilteringReader
                && ((WhitespaceFilteringReader) reader).isEmptyElement) {
                if (reader.hasNext()) reader.next();
                return;
            }
            while (reader.hasNext() && !reader.isEndElement()) reader.next();
            if (reader.hasNext()) reader.next();
        } catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static double readElementContentAsDouble() {
        try { return reader != null ? Double.parseDouble(reader.getElementText().trim()) : 0.0; }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static int readElementContentAsInt() {
        try { return reader != null ? Integer.parseInt(reader.getElementText().trim()) : 0; }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static String readElementContentAsString() {
        try { return reader != null ? reader.getElementText() : ""; }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static boolean readElementContentAsBoolean() {
        try { return reader != null && Boolean.parseBoolean(reader.getElementText().trim()); }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static void moveToContent() {
        try {
            attributeIndex = -1;
            if (reader == null) return;
            while (reader.hasNext()) {
                int t = reader.getEventType();
                if (t == XMLStreamConstants.START_ELEMENT
                    || t == XMLStreamConstants.END_ELEMENT
                    || t == XMLStreamConstants.END_DOCUMENT) return;
                reader.next();
            }
        } catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static boolean moveToFirstAttribute() {
        if (reader != null && reader.isStartElement() && reader.getAttributeCount() > 0) {
            attributeIndex = 0;
            return true;
        }
        return false;
    }

    public static void skip() {
        try {
            attributeIndex = -1;
            if (reader == null) return;
            if (!reader.isStartElement()) {
                // In C#, XmlReader.Skip() on non-start-element acts like Read() (advances to next node).
                if (reader.hasNext()) reader.next();
                return;
            }
            // If empty element, its END_ELEMENT was already consumed by look-ahead. Just advance.
            if (reader instanceof WhitespaceFilteringReader && ((WhitespaceFilteringReader) reader).isEmptyElement) {
                if (reader.hasNext()) reader.next();
                return;
            }
            int depth = 1;
            while (depth > 0 && reader.hasNext()) {
                reader.next();
                if (reader.isStartElement()) {
                    // If this child is an empty element, don't increment depth (its END was consumed)
                    if (!(reader instanceof WhitespaceFilteringReader) || !((WhitespaceFilteringReader) reader).isEmptyElement) {
                        depth++;
                    }
                }
                else if (reader.isEndElement()) depth--;
            }
            if (reader.hasNext()) reader.next();
        } catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static int getReadState() {
        if (reader == null) return io.github.ningpp.compat.ReadState.getClosed();
        try { return reader.hasNext() ? io.github.ningpp.compat.ReadState.getInteractive() : io.github.ningpp.compat.ReadState.getEndOfFile(); }
        catch (Exception e) { return io.github.ningpp.compat.ReadState.getError(); }
    }

    @Override
    public void close() throws Exception {
        if (reader != null) try { reader.close(); } catch (XMLStreamException ignored) {}
    }
}
