package io.github.ningpp.compat;

/** Replacement for System.Xml.Schema.XmlSchemaException (generated by CSharpToJava converter). */
public class XmlSchemaException extends SystemException {
    public XmlSchemaException() { super(); }
    public XmlSchemaException(String message) { super(message); }
    public XmlSchemaException(String message, Throwable cause) { super(message, cause); }
}
