package io.github.ningpp.compat;

/** Replacement for System.Security.XmlSyntaxException (generated by CSharpToJava converter). */
public class XmlSyntaxException extends SystemException {
    public XmlSyntaxException() { super(); }
    public XmlSyntaxException(String message) { super(message); }
    public XmlSyntaxException(String message, Throwable cause) { super(message, cause); }
}
