package io.github.ningpp.compat;

/** Replacement for System.Xml.Schema.XmlSchemaValidationException (generated by CSharpToJava converter). */
public class XmlSchemaValidationException extends XmlSchemaException {
    public XmlSchemaValidationException() { super(); }
    public XmlSchemaValidationException(String message) { super(message); }
    public XmlSchemaValidationException(String message, Throwable cause) { super(message, cause); }
}
