package io.github.ningpp.compat;

import java.io.InputStream;
import java.io.OutputStream;
import java.io.Writer;
import javax.xml.stream.*;

/** Replacement for System.Xml.XmlWriter backed by StAX (generated by CSharpToJava converter). */
public class XmlWriter {
    protected static XMLStreamWriter writer;

    protected XmlWriter() {}

    protected XmlWriter(XMLStreamWriter writer) {
        XmlWriter.writer = writer;
    }

    /** Factory — mirrors XmlWriter.Create(output, settings) in C#. */
    public static XmlWriter create(Object output, Object settings) {
        try {
            XMLOutputFactory factory = XMLOutputFactory.newInstance();
            if (output instanceof OutputStream) {
                return new XmlWriter(factory.createXMLStreamWriter((OutputStream) output, "UTF-8"));
            } else if (output instanceof Writer) {
                return new XmlWriter(factory.createXMLStreamWriter((Writer) output));
            }
            // InputStream passed as output is a C# idiom mismatch — return no-op writer
            return new XmlWriter();
        } catch (XMLStreamException e) {
            throw new RuntimeException(e);
        }
    }

    /** Convenience overload used by converted code paths. */
    public static XmlWriter create(Object output) {
        return create(output, null);
    }

    public static void writeStartElement(String localName) {
        try { if (writer != null) writer.writeStartElement(localName); }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static void writeEndElement() {
        try { if (writer != null) writer.writeEndElement(); }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static void writeAttributeString(String localName, String value) {
        try { if (writer != null) writer.writeAttribute(localName, value != null ? value : ""); }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static void writeAttributeString(String prefix, String localName, String ns, String value) {
        try {
            if (writer != null) {
                if (prefix != null && !prefix.isEmpty()) writer.writeAttribute(prefix, ns != null ? ns : "", localName, value != null ? value : "");
                else writer.writeAttribute(localName, value != null ? value : "");
            }
        } catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static void writeStartElement(String localName, String ns) {
        try {
            if (writer != null) {
                if (ns != null && !ns.isEmpty()) writer.writeStartElement("", localName, ns);
                else writer.writeStartElement(localName);
            }
        } catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static void writeElementString(String localName, String value) {
        try {
            if (writer != null) {
                writer.writeStartElement(localName);
                writer.writeCharacters(value != null ? value : "");
                writer.writeEndElement();
            }
        } catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static void writeString(String text) {
        try { if (writer != null) writer.writeCharacters(text != null ? text : ""); }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    /** Writes raw XML-ish text as character data (compatibility shim for converted calls). */
    public static void writeRaw(String text) {
        writeString(text);
    }

    public static void writeComment(String text) {
        try { if (writer != null) writer.writeComment(text != null ? text : ""); }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static void writeEndDocument() {
        try { if (writer != null) writer.writeEndDocument(); }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static void flush() {
        try { if (writer != null) writer.flush(); }
        catch (XMLStreamException e) { throw new RuntimeException(e); }
    }

    public static void close() {
        if (writer != null) {
            try { writer.flush(); }  catch (XMLStreamException ignored) {}
            try { writer.close(); }  catch (XMLStreamException ignored) {}
        }
    }
}
