package io.github.ningpp.compat;

/** Replacement for System.Xml.XmlWriterSettings (generated by CSharpToJava converter). */
public class XmlWriterSettings {
    // Public field aliases used by generated C#-style property access.
    public String Encoding = "UTF-8";
    public boolean Indent = false;
    public String IndentChars = "  ";
    public boolean OmitXmlDeclaration = false;
    public String  getEncoding()                    { return Encoding; }
    public void    setEncoding(String v)             { Encoding = v; }
    public boolean isIndent()                       { return Indent; }
    public void    setIndent(boolean v)              { Indent = v; }
    public String  getIndentChars()                 { return IndentChars; }
    public void    setIndentChars(String v)          { IndentChars = v; }
    public boolean isOmitXmlDeclaration()           { return OmitXmlDeclaration; }
    public void    setOmitXmlDeclaration(boolean v)  { OmitXmlDeclaration = v; }
}
