package io.github.ningpp.compat;

/** Replacement for System.Xml.XPath.XPathException (generated by CSharpToJava converter). */
public class XPathException extends SystemException {
    public XPathException() { super(); }
    public XPathException(String message) { super(message); }
    public XPathException(String message, Throwable cause) { super(message, cause); }
}
