package io.github.ningpp.compat;

/** Replacement for System.Xml.Xsl.XsltCompileException (generated by CSharpToJava converter). */
public class XsltCompileException extends XsltException {
    public XsltCompileException() { super(); }
    public XsltCompileException(String message) { super(message); }
    public XsltCompileException(String message, Throwable cause) { super(message, cause); }
}
