using CSharpToJava.Core.Context;
using CSharpToJava.Core.Pipeline;

namespace CSharpToJava.Tests;

/// <summary>
/// Tests that property-to-method mappings (e.g., Count → size()) are correctly applied
/// inside conditional access expressions (e.g., (x as ICollection&lt;T&gt;)?.Count).
/// This pattern is generated by the LINQ rewriter when the source collection is
/// an IEnumerable (not ICollection) and the rewriter tries to pre-allocate with Count.
/// </summary>
public class ConditionalAccessPropertyMappingTests
{
    /// <summary>
    /// Reproduces: Java compile error "找不到符号: 变量 Count 位置: 接口 Collection"
    /// when LINQ Select is used on an IEnumerable parameter.
    /// The LINQ rewriter generates (items as ICollection&lt;T&gt;)?.Count which must
    /// become .size() in Java, not .Count.
    /// </summary>
    [Fact]
    public void LinqSelect_OnIEnumerable_CountMappedToSize()
    {
        var result = Convert(@"
using System.Collections.Generic;
using System.Linq;
class Sample
{
    List<int> M(IEnumerable<string> items)
    {
        return items.Select(x => x.Length).ToList();
    }
}");

        Assert.True(result.Success, string.Join("\n", result.Diagnostics));
        // The LINQ rewriter may generate (items as ICollection<string>)?.Count
        // which must be mapped to .size() in Java
        Assert.DoesNotContain(".Count", result.GeneratedCode, StringComparison.Ordinal);
        if (result.GeneratedCode.Contains("size()"))
            Assert.Contains("size()", result.GeneratedCode, StringComparison.Ordinal);
    }

    /// <summary>
    /// Direct conditional access on collection: (x as ICollection&lt;T&gt;)?.Count
    /// must produce .size() not .Count in Java output.
    /// </summary>
    [Fact]
    public void ConditionalAccess_Count_OnICollection_MappedToSize()
    {
        var result = Convert(@"
using System.Collections.Generic;
class Sample
{
    int? M(IEnumerable<string> items)
    {
        return (items as ICollection<string>)?.Count;
    }
}");

        Assert.True(result.Success, string.Join("\n", result.Diagnostics));
        Assert.DoesNotContain(".Count", result.GeneratedCode, StringComparison.Ordinal);
        Assert.Contains(".size()", result.GeneratedCode, StringComparison.Ordinal);
    }

    /// <summary>
    /// Conditional access with GetValueOrDefault: ((x as ICollection&lt;T&gt;)?.Count).GetValueOrDefault()
    /// This is the exact pattern generated by the LINQ rewriter.
    /// </summary>
    [Fact]
    public void ConditionalAccess_Count_GetValueOrDefault_MappedToSize()
    {
        var result = Convert(@"
using System.Collections.Generic;
class Sample
{
    int M(IEnumerable<string> items)
    {
        return ((items as ICollection<string>)?.Count).GetValueOrDefault();
    }
}");

        Assert.True(result.Success, string.Join("\n", result.Diagnostics));
        Assert.DoesNotContain(".Count", result.GeneratedCode, StringComparison.Ordinal);
    }

    private static ConversionResult Convert(string sourceCode)
    {
        var pipeline = new ConversionPipeline();
        return pipeline.Convert(new ConversionRequest
        {
            SourceCode = sourceCode,
            FileName = "Test.cs",
            Options = new ConversionOptions(),
        });
    }
}
