using CSharpToJava.Core.Context;
using CSharpToJava.Core.Pipeline;

namespace CSharpToJava.Tests;

/// <summary>
/// Tests for issue #29: user-defined C# method whose Java camelCase name collides
/// with an auto-generated property setter/getter was silently dropped.
///
/// Root cause: PropertyTransformer generates getter/setter with standard Java Bean
/// names (e.g., setFirstEdge for property FirstEdge). When a user-defined method
/// SetFirstEdge(PathEdge) is converted to camelCase setFirstEdge, the duplicate
/// detection in AddMethodIfNotDuplicateInternal drops the user method silently
/// because neither the private-setter-override nor covariant-return-type rules apply.
///
/// Fix: IsAutoGenerated flag on property accessors + conflict resolution that renames
/// the user-defined method to PascalCase (e.g., SetFirstEdge) while keeping the
/// auto-generated accessor with the standard Java Bean name.
/// </summary>
public class MethodPropertyNameCollisionTests
{
    /// <summary>
    /// Issue #29 core scenario: property FirstEdge { get; set; } generates setFirstEdge(),
    /// and user method SetFirstEdge(PathEdge edge) also maps to setFirstEdge().
    /// After fix, both methods must survive — the user method renamed to PascalCase.
    /// </summary>
    [Fact]
    public void SetterAndMethod_SameNameAndSignature_UserMethodRenamedToPascalCase()
    {
        var result = Convert(@"
namespace Demo
{
    class Path
    {
        internal PathEdge FirstEdge { get; set; }
        internal PathEdge LastEdge { get; set; }

        internal void SetFirstEdge(PathEdge edge)
        {
            LastEdge = FirstEdge = edge;
            edge.Path = this;
        }
    }
    class PathEdge
    {
        internal Path Path { get; set; }
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Auto-generated property setter MUST exist with standard Java Bean name
        Assert.Contains("setFirstEdge(", code, StringComparison.Ordinal);
        // Auto-generated property getter MUST exist
        Assert.Contains("getFirstEdge(", code, StringComparison.Ordinal);
        // Auto-generated property setter for LastEdge MUST exist
        Assert.Contains("setLastEdge(", code, StringComparison.Ordinal);

        // User-defined method MUST exist, renamed to PascalCase to avoid collision
        Assert.Contains("SetFirstEdge(", code, StringComparison.Ordinal);
        // The method body logic must be present (chained assignment)
        Assert.Contains("setLastEdge(", code, StringComparison.Ordinal);
        Assert.Contains("edge.setPath(this)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// Reverse declaration order: user method SetFirstEdge declared BEFORE property FirstEdge.
    /// The fix must handle both processing orders correctly.
    /// </summary>
    [Fact]
    public void MethodBeforeProperty_SameNameCollision_UserMethodStillRenamed()
    {
        var result = Convert(@"
namespace Demo
{
    class Path
    {
        internal void SetFirstEdge(PathEdge edge)
        {
            LastEdge = FirstEdge = edge;
            edge.Path = this;
        }

        internal PathEdge FirstEdge { get; set; }
        internal PathEdge LastEdge { get; set; }
    }
    class PathEdge
    {
        internal Path Path { get; set; }
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Both must survive regardless of declaration order
        Assert.Contains("setFirstEdge(", code, StringComparison.Ordinal);
        Assert.Contains("SetFirstEdge(", code, StringComparison.Ordinal);
        Assert.Contains("edge.setPath(this)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// Getter collision: property Value { get; } generates getValue(), and user method
    /// GetValue() also maps to getValue(). User method should be renamed to PascalCase.
    /// </summary>
    [Fact]
    public void GetterAndMethod_SameNameAndSignature_UserMethodRenamedToPascalCase()
    {
        var result = Convert(@"
class Container
{
    public int Value { get; }
    public int GetValue() { return Value * 2; }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Auto-generated getter MUST exist
        Assert.Contains("getValue()", code, StringComparison.Ordinal);
        // User-defined method MUST exist, renamed to PascalCase
        Assert.Contains("GetValue()", code, StringComparison.Ordinal);
        // Method body should be present
        Assert.Contains("return getValue() * 2", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// Edge case: method has same name as property setter but DIFFERENT parameter types.
    /// Since ErasedParamSig checks parameter types (not just count), these should NOT collide
    /// and both should keep the same name as valid Java overloads.
    /// </summary>
    [Fact]
    public void SameName_DifferentParameterTypes_NoCollision_BothKeepSameName()
    {
        var result = Convert(@"
class Container
{
    public int Value { get; set; }
    // setValue(String) vs setValue(int) — different erased signatures
    public void SetValue(string s) { }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Both should exist as setValue with different parameter types (Java overloading)
        Assert.Contains("setValue(int", code, StringComparison.Ordinal);
        Assert.Contains("setValue(String", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// Edge case: method has same name as property setter but DIFFERENT parameter count.
    /// Should NOT collide — both methods survive with standard camelCase names.
    /// </summary>
    [Fact]
    public void SameName_DifferentParameterCount_NoCollision_BothKeepSameName()
    {
        var result = Convert(@"
class Container
{
    public int Value { get; set; }
    // setValue() vs setValue(int) — different parameter count => no collision
    public void SetValue() { }
    // setValue(int, int) vs setValue(int) — different count => no collision
    public void SetValue(int x, int y) { }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Property setter
        Assert.Contains("setValue(int", code, StringComparison.Ordinal);
        // Parameterless overload
        Assert.Contains("setValue()", code, StringComparison.Ordinal);
        // Two-parameter overload
        Assert.Contains("setValue(int x, int y)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// No regression: standalone property with no colliding method should still
    /// generate normal getter/setter.
    /// </summary>
    [Fact]
    public void PropertyOnly_NoCollidingMethod_NormalGetterSetter()
    {
        var result = Convert(@"
class Normal
{
    public string Name { get; set; }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("getName()", code, StringComparison.Ordinal);
        Assert.Contains("setName(String", code, StringComparison.Ordinal);
        // No PascalCase method should appear
        Assert.DoesNotContain("SetName(", code, StringComparison.Ordinal);
    }

    private static ConversionResult Convert(string sourceCode)
    {
        var pipeline = new ConversionPipeline();
        return pipeline.Convert(new ConversionRequest
        {
            SourceCode = sourceCode,
            FileName = "Sample.cs",
            Options = new ConversionOptions(),
        });
    }
}
