using CSharpToJava.Core.Context;
using CSharpToJava.Core.Pipeline;

namespace CSharpToJava.Tests;

/// <summary>
/// Tests for operator overload methods colliding with user-defined methods.
///
/// Root cause: OperatorTransformer generated Java methods from C# operator overloads
/// (e.g., operator+(Point,Point) → add(Point,Point)) but did not set IsAutoGenerated = true.
/// When a user-defined method (e.g., Add(Point,Point) → add(Point,Point)) collided with
/// the same name and erased signature, AddMethodIfNotDuplicateInternal silently dropped
/// the user method because none of the collision-resolution rules matched.
///
/// Fix: OperatorTransformer now marks all generated methods with IsAutoGenerated = true,
/// so the existing conflict resolution renames the user-defined method to PascalCase.
/// </summary>
public class OperatorMethodNameCollisionTests
{
    /// <summary>
    /// operator+(Point,Point) → add(Point,Point) collides with Add(Point,Point) → add(Point,Point).
    /// Operator method keeps camelCase; user method renamed to PascalCase "Add".
    /// </summary>
    [Fact]
    public void AdditionOperatorAndAddMethod_SameSignature_UserMethodRenamedToPascalCase()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator +(Point a, Point b)
    {
        return new Point(a.X + b.X, a.Y + b.Y);
    }

    public static Point Add(Point a, Point b)
    {
        return a + b;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Operator-generated method MUST exist with camelCase name
        Assert.Contains("public static Point add(Point a, Point b)", code, StringComparison.Ordinal);
        // User-defined method MUST exist, renamed to PascalCase
        Assert.Contains("public static Point Add(Point a, Point b)", code, StringComparison.Ordinal);
        // User method body delegates to operator method
        Assert.Contains("return add(a, b)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// operator-(Point,Point) → subtract(Point,Point) collides with Subtract(Point,Point).
    /// </summary>
    [Fact]
    public void SubtractionOperatorAndSubtractMethod_SameSignature_UserMethodRenamedToPascalCase()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator -(Point a, Point b)
    {
        return new Point(a.X - b.X, a.Y - b.Y);
    }

    public static Point Subtract(Point a, Point b)
    {
        return a - b;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point subtract(Point a, Point b)", code, StringComparison.Ordinal);
        Assert.Contains("public static Point Subtract(Point a, Point b)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// operator*(double,Point) → multiply(double,Point) collides with Multiply(double,Point).
    /// </summary>
    [Fact]
    public void ScalarMultiplyOperatorAndMultiplyMethod_SameSignature_UserMethodRenamedToPascalCase()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator *(double c, Point p)
    {
        return new Point(c * p.X, c * p.Y);
    }

    public static Point Multiply(double c, Point p)
    {
        return c * p;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point multiply(double c, Point p)", code, StringComparison.Ordinal);
        Assert.Contains("public static Point Multiply(double c, Point p)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// operator/(Point,double) → divide(Point,double) collides with Divide(Point,double).
    /// </summary>
    [Fact]
    public void DivisionOperatorAndDivideMethod_SameSignature_UserMethodRenamedToPascalCase()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator /(Point p, double c)
    {
        return new Point(p.X / c, p.Y / c);
    }

    public static Point Divide(Point p, double c)
    {
        return p / c;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point divide(Point p, double c)", code, StringComparison.Ordinal);
        Assert.Contains("public static Point Divide(Point p, double c)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// Unary operator-(Point) → negate(Point) (static, 1 param) does NOT collide with
    /// instance method Negate() → negate() (0 params). Both survive with camelCase names.
    /// </summary>
    [Fact]
    public void UnaryNegateOperatorAndInstanceNegateMethod_DifferentParamCount_NoCollision()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator -(Point p)
    {
        return new Point(-p.X, -p.Y);
    }

    public Point Negate()
    {
        return -this;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Both methods survive — different parameter counts, no collision
        Assert.Contains("negate(Point p)", code, StringComparison.Ordinal);
        Assert.Contains("public Point negate()", code, StringComparison.Ordinal);
        // Instance method calls the static operator method
        Assert.Contains("return negate(this)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// operator*(Point,Point) returns double (dot product), while operator*(double,Point)
    /// returns Point (scalar multiply). Different signatures, no collision.
    /// </summary>
    [Fact]
    public void DotProductAndScalarMultiply_DifferentSignatures_NoCollision()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static double operator *(Point a, Point b)
    {
        return a.X * b.X + a.Y * b.Y;
    }

    public static Point operator *(double c, Point p)
    {
        return new Point(c * p.X, c * p.Y);
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Dot product: multiply(Point, Point) → double
        Assert.Contains("public static double multiply(Point a, Point b)", code, StringComparison.Ordinal);
        // Scalar multiply: multiply(double, Point) → Point
        Assert.Contains("public static Point multiply(double c, Point p)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// Reverse declaration order: user-defined Add() appears BEFORE operator+.
    /// Collision resolution must work regardless of declaration order.
    /// </summary>
    [Fact]
    public void UserMethodBeforeOperator_SameSignature_UserMethodStillRenamed()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point Add(Point a, Point b)
    {
        return a + b;
    }

    public static Point operator +(Point a, Point b)
    {
        return new Point(a.X + b.X, a.Y + b.Y);
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point add(Point a, Point b)", code, StringComparison.Ordinal);
        Assert.Contains("public static Point Add(Point a, Point b)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// User method named "valueEquals" (Java name of operator==) collides with operator==.
    /// User method should be renamed to PascalCase.
    /// </summary>
    [Fact]
    public void EqualityOperatorAndValueEqualsMethod_SameSignature_UserMethodRenamed()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static bool operator ==(Point a, Point b)
    {
        return a.X == b.X && a.Y == b.Y;
    }

    public static bool operator !=(Point a, Point b)
    {
        return !(a == b);
    }

    // User method whose camelCase name matches operator's Java name
    public static bool ValueEquals(Point a, Point b)
    {
        return a == b;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static boolean valueEquals(Point a, Point b)", code, StringComparison.Ordinal);
        Assert.Contains("public static boolean notEquals(Point a, Point b)", code, StringComparison.Ordinal);
        // User ValueEquals method renamed to PascalCase
        Assert.Contains("public static boolean ValueEquals(Point a, Point b)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// No regression: standalone operator without colliding user method should
    /// generate the normal operator method name.
    /// </summary>
    [Fact]
    public void OperatorOnly_NoCollidingMethod_NormalOperatorMethod()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator +(Point a, Point b)
    {
        return new Point(a.X + b.X, a.Y + b.Y);
    }

    public static Point operator -(Point a, Point b)
    {
        return new Point(a.X - b.X, a.Y - b.Y);
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point add(Point a, Point b)", code, StringComparison.Ordinal);
        Assert.Contains("public static Point subtract(Point a, Point b)", code, StringComparison.Ordinal);
        // No PascalCase Add/Subtract should appear
        Assert.DoesNotContain("public static Point Add(", code, StringComparison.Ordinal);
        Assert.DoesNotContain("public static Point Subtract(", code, StringComparison.Ordinal);
    }

    private static ConversionResult Convert(string sourceCode)
    {
        var pipeline = new ConversionPipeline();
        return pipeline.Convert(new ConversionRequest
        {
            SourceCode = sourceCode,
            FileName = "Sample.cs",
            Options = new ConversionOptions(),
        });
    }
}
