using CSharpToJava.Core.Context;
using CSharpToJava.Core.Pipeline;

namespace CSharpToJava.Tests;

/// <summary>
/// Tests for operator overload methods colliding with user-defined methods.
///
/// Root cause: OperatorTransformer generated Java methods from C# operator overloads
/// (e.g., operator+(Point,Point) → add(Point,Point)) but did not set IsAutoGenerated = true.
/// When a user-defined method (e.g., Add(Point,Point) → add(Point,Point)) collided with
/// the same name and erased signature, AddMethodIfNotDuplicateInternal silently dropped
/// the user method because none of the collision-resolution rules matched.
///
/// Fix: OperatorTransformer now marks all generated methods with IsAutoGenerated = true,
/// so the existing conflict resolution renames the user-defined method to PascalCase.
/// </summary>
public class OperatorMethodNameCollisionTests
{
    /// <summary>
    /// operator+(Point,Point) → add(Point,Point) collides with Add(Point,Point) → add(Point,Point).
    /// Operator method keeps camelCase; user method renamed to PascalCase "Add".
    /// </summary>
    [Fact]
    public void AdditionOperatorAndAddMethod_SameSignature_UserMethodRenamedToPascalCase()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator +(Point a, Point b)
    {
        return new Point(a.X + b.X, a.Y + b.Y);
    }

    public static Point Add(Point a, Point b)
    {
        return a + b;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Operator-generated method MUST exist with camelCase name
        Assert.Contains("public static Point add(Point a, Point b)", code, StringComparison.Ordinal);
        // User-defined method MUST exist, renamed to PascalCase
        Assert.Contains("public static Point Add(Point a, Point b)", code, StringComparison.Ordinal);
        // User method body delegates to operator method
        Assert.Contains("return add(a, b)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// operator-(Point,Point) → subtract(Point,Point) collides with Subtract(Point,Point).
    /// </summary>
    [Fact]
    public void SubtractionOperatorAndSubtractMethod_SameSignature_UserMethodRenamedToPascalCase()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator -(Point a, Point b)
    {
        return new Point(a.X - b.X, a.Y - b.Y);
    }

    public static Point Subtract(Point a, Point b)
    {
        return a - b;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point subtract(Point a, Point b)", code, StringComparison.Ordinal);
        Assert.Contains("public static Point Subtract(Point a, Point b)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// operator*(double,Point) → multiply(double,Point) collides with Multiply(double,Point).
    /// </summary>
    [Fact]
    public void ScalarMultiplyOperatorAndMultiplyMethod_SameSignature_UserMethodRenamedToPascalCase()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator *(double c, Point p)
    {
        return new Point(c * p.X, c * p.Y);
    }

    public static Point Multiply(double c, Point p)
    {
        return c * p;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point multiply(double c, Point p)", code, StringComparison.Ordinal);
        Assert.Contains("public static Point Multiply(double c, Point p)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// operator/(Point,double) → divide(Point,double) collides with Divide(Point,double).
    /// </summary>
    [Fact]
    public void DivisionOperatorAndDivideMethod_SameSignature_UserMethodRenamedToPascalCase()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator /(Point p, double c)
    {
        return new Point(p.X / c, p.Y / c);
    }

    public static Point Divide(Point p, double c)
    {
        return p / c;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point divide(Point p, double c)", code, StringComparison.Ordinal);
        Assert.Contains("public static Point Divide(Point p, double c)", code, StringComparison.Ordinal);
    }

    [Fact]
    public void DivisionOperator_DoubleLeftPointRight_CallSiteUsesOperatorMethod()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator /(double x, Point p)
    {
        return new Point(x / p.X, x / p.Y);
    }

    public static Point Abc(double padding, Point p)
    {
        return padding / p;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point divide(double x, Point p)", code, StringComparison.Ordinal);
        Assert.Contains("return divide(padding, p)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// Unary operator-(Point) → negate(Point) (static, 1 param) does NOT collide with
    /// instance method Negate() → negate() (0 params). Both survive with camelCase names.
    /// </summary>
    [Fact]
    public void UnaryNegateOperatorAndInstanceNegateMethod_DifferentParamCount_NoCollision()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator -(Point p)
    {
        return new Point(-p.X, -p.Y);
    }

    public Point Negate()
    {
        return -this;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Both methods survive — different parameter counts, no collision
        Assert.Contains("negate(Point p)", code, StringComparison.Ordinal);
        Assert.Contains("public Point negate()", code, StringComparison.Ordinal);
        // Instance method calls the static operator method
        Assert.Contains("return negate(this)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// operator*(Point,Point) returns double (dot product), while operator*(double,Point)
    /// returns Point (scalar multiply). Different signatures, no collision.
    /// </summary>
    [Fact]
    public void DotProductAndScalarMultiply_DifferentSignatures_NoCollision()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static double operator *(Point a, Point b)
    {
        return a.X * b.X + a.Y * b.Y;
    }

    public static Point operator *(double c, Point p)
    {
        return new Point(c * p.X, c * p.Y);
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Dot product: multiply(Point, Point) → double
        Assert.Contains("public static double multiply(Point a, Point b)", code, StringComparison.Ordinal);
        // Scalar multiply: multiply(double, Point) → Point
        Assert.Contains("public static Point multiply(double c, Point p)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// Reverse declaration order: user-defined Add() appears BEFORE operator+.
    /// Collision resolution must work regardless of declaration order.
    /// </summary>
    [Fact]
    public void UserMethodBeforeOperator_SameSignature_UserMethodStillRenamed()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point Add(Point a, Point b)
    {
        return a + b;
    }

    public static Point operator +(Point a, Point b)
    {
        return new Point(a.X + b.X, a.Y + b.Y);
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point add(Point a, Point b)", code, StringComparison.Ordinal);
        Assert.Contains("public static Point Add(Point a, Point b)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// User method named "valueEquals" (Java name of operator==) collides with operator==.
    /// User method should be renamed to PascalCase.
    /// </summary>
    [Fact]
    public void EqualityOperatorAndValueEqualsMethod_SameSignature_UserMethodRenamed()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static bool operator ==(Point a, Point b)
    {
        return a.X == b.X && a.Y == b.Y;
    }

    public static bool operator !=(Point a, Point b)
    {
        return !(a == b);
    }

    // User method whose camelCase name matches operator's Java name
    public static bool ValueEquals(Point a, Point b)
    {
        return a == b;
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static boolean valueEquals(Point a, Point b)", code, StringComparison.Ordinal);
        Assert.Contains("public static boolean notEquals(Point a, Point b)", code, StringComparison.Ordinal);
        // User ValueEquals method renamed to PascalCase
        Assert.Contains("public static boolean ValueEquals(Point a, Point b)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// No regression: standalone operator without colliding user method should
    /// generate the normal operator method name.
    /// </summary>
    [Fact]
    public void OperatorOnly_NoCollidingMethod_NormalOperatorMethod()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator +(Point a, Point b)
    {
        return new Point(a.X + b.X, a.Y + b.Y);
    }

    public static Point operator -(Point a, Point b)
    {
        return new Point(a.X - b.X, a.Y - b.Y);
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        Assert.Contains("public static Point add(Point a, Point b)", code, StringComparison.Ordinal);
        Assert.Contains("public static Point subtract(Point a, Point b)", code, StringComparison.Ordinal);
        // No PascalCase Add/Subtract should appear
        Assert.DoesNotContain("public static Point Add(", code, StringComparison.Ordinal);
        Assert.DoesNotContain("public static Point Subtract(", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// Inside an operator body, primitive arithmetic on member fields (e.g. point0.X + point1.X
    /// where X is double) MUST remain as Java operators, not be converted to operator method calls.
    /// Regression test: InferOperatorTypeFromSyntax was incorrectly returning the receiver type (Point)
    /// instead of null for member accesses whose type is built-in (double).
    /// </summary>
    [Fact]
    public void OperatorBody_PrimitiveArithmetic_KeptAsJavaOperators()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator +(Point a, Point b)
    {
        return new Point(a.X + b.X, a.Y + b.Y);
    }

    public static Point operator -(Point a, Point b)
    {
        return new Point(a.X - b.X, a.Y - b.Y);
    }

    public static double operator *(Point a, Point b)
    {
        return a.X * b.X + a.Y * b.Y;
    }

    public static Point operator *(double c, Point p)
    {
        return new Point(c * p.X, c * p.Y);
    }

    public static Point operator /(Point p, double c)
    {
        return new Point(p.X / c, p.Y / c);
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // operator+ body: primitive + on double fields must stay as Java +
        Assert.Contains("a.X + b.X", code, StringComparison.Ordinal);
        Assert.Contains("a.Y + b.Y", code, StringComparison.Ordinal);
        // operator+ body must NOT convert double + to add()
        Assert.DoesNotContain("add(a.X", code, StringComparison.Ordinal);

        // operator- body: primitive - on double fields must stay as Java -
        Assert.Contains("a.X - b.X", code, StringComparison.Ordinal);

        // operator* (dot product) body: primitive * and + on doubles
        Assert.Contains("a.X * b.X + a.Y * b.Y", code, StringComparison.Ordinal);

        // operator* (scalar) body: primitive * on doubles
        Assert.Contains("c * p.X", code, StringComparison.Ordinal);

        // operator/ body: primitive / on doubles
        Assert.Contains("p.X / c", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// operator+(Point,Point) → add(Point,Point) does NOT collide with Add(Point,int)
    /// because the second parameter type differs (Point vs int). Same param count (2),
    /// but different erased signature → no collision → user method stays camelCase.
    /// </summary>
    [Fact]
    public void SameParamCount_DifferentTypes_NoCollision_StaysCamelCase()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    public static Point operator +(Point a, Point b)
    {
        return new Point(a.X + b.X, a.Y + b.Y);
    }

    // Same param count (2) as operator+, but different 2nd param type (int ≠ Point)
    public static Point Add(Point a, int b)
    {
        return new Point(a.X + b, a.Y + b);
    }

    // Call site that invokes Add — should use camelCase
    public static Point Caller(Point p)
    {
        return Add(p, 5);
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Operator-generated method
        Assert.Contains("public static Point add(Point a, Point b)", code, StringComparison.Ordinal);
        // User method: no collision → stays camelCase
        Assert.Contains("public static Point add(Point a, int b)", code, StringComparison.Ordinal);
        // Call site uses camelCase
        Assert.Contains("return add(p, 5)", code, StringComparison.Ordinal);
        // PascalCase must NOT appear
        Assert.DoesNotContain("public static Point Add(", code, StringComparison.Ordinal);
        Assert.DoesNotContain("return Add(p", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// When a user-defined method collides with an operator (same name + same erased
    /// signature), the operator body that calls the user method must use the PascalCase
    /// name — not the camelCase operator name. Otherwise the operator recursively calls
    /// itself, causing StackOverflowError at runtime.
    ///
    /// This is the scenario from PlaneTransformation.multiply() in MSAGL.
    /// </summary>
    [Fact]
    public void OperatorBody_CallsCollidingUserMethod_UsesPascalCaseName()
    {
        var result = Convert(@"
public struct Point
{
    public double X, Y;
    public Point(double x, double y) { X = x; Y = y; }

    // operator* delegates to Multiply
    public static Point operator *(double c, Point p)
    {
        return Multiply(c, p);
    }

    // User method with actual implementation — collides with operator*
    public static Point Multiply(double c, Point p)
    {
        return new Point(c * p.X, c * p.Y);
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Operator-generated method
        Assert.Contains("public static Point multiply(double c, Point p)", code, StringComparison.Ordinal);
        // User method renamed to PascalCase (collision resolution)
        Assert.Contains("public static Point Multiply(double c, Point p)", code, StringComparison.Ordinal);
        // Operator body MUST call Multiply (PascalCase), NOT multiply (itself → recursion)
        Assert.Contains("return Multiply(c, p)", code, StringComparison.Ordinal);
        Assert.DoesNotContain("return multiply(c, p)", code, StringComparison.Ordinal);
    }

    /// <summary>
    /// When a class has multiple operator overloads with the same Java name but different
    /// parameter types, the collision check must match parameter TYPES, not just count.
    /// Example: Matrix has operator*(Matrix,Matrix) and operator*(Matrix,Point) — both
    /// generate Java method "multiply" with 2 params. The user method Multiply(Matrix,Point)
    /// collides ONLY with the second operator, not the first.
    /// </summary>
    [Fact]
    public void MultipleOperators_OneCollidesByType_UsesPascalCaseForCorrectCall()
    {
        var result = Convert(@"
public struct Matrix
{
    public double M00, M01, M02, M10, M11, M12;
    public double X, Y;
    public Matrix(double m00, double m01, double m02, double m10, double m11, double m12)
    {
        M00 = m00; M01 = m01; M02 = m02;
        M10 = m10; M11 = m11; M12 = m12;
        X = 0; Y = 0;
    }

    // operator* on Matrix×Matrix (2 params, both Matrix)
    public static Matrix operator *(Matrix a, Matrix b)
    {
        return new Matrix(
            a.M00 * b.M00 + a.M01 * b.M10, a.M00 * b.M01 + a.M01 * b.M11,
            a.M00 * b.M02 + a.M01 * b.M12 + a.M02,
            a.M10 * b.M00 + a.M11 * b.M10, a.M10 * b.M01 + a.M11 * b.M11,
            a.M10 * b.M02 + a.M11 * b.M12 + a.M12);
    }

    // operator* on Matrix×Point (2 params, Matrix+Point) — delegates to user Multiply
    public static Point operator *(Matrix a, Point p)
    {
        return Multiply(a, p);
    }

    // User method — same signature as Matrix×Point operator
    public static Point Multiply(Matrix a, Point p)
    {
        return new Point(
            a.M00 * p.X + a.M01 * p.Y + a.M02,
            a.M10 * p.X + a.M11 * p.Y + a.M12);
    }
}");

        Assert.True(result.Success);
        var code = result.GeneratedCode;

        // Both operators generate multiply with different erased signatures
        Assert.Contains("multiply(Matrix a, Matrix b)", code, StringComparison.Ordinal);
        Assert.Contains("multiply(Matrix a, Point p)", code, StringComparison.Ordinal);
        // User Multiply(Matrix, Point) collides with operator*(Matrix, Point) — renamed to PascalCase
        Assert.Contains("public static Point Multiply(Matrix a, Point p)", code, StringComparison.Ordinal);
        // The Matrix×Point operator body calls Multiply (PascalCase), not multiply
        Assert.Contains("return Multiply(a, p)", code, StringComparison.Ordinal);
    }

    private static ConversionResult Convert(string sourceCode)
    {
        var pipeline = new ConversionPipeline();
        return pipeline.Convert(new ConversionRequest
        {
            SourceCode = sourceCode,
            FileName = "Sample.cs",
            Options = new ConversionOptions(),
        });
    }
}
