// src/CSharpToJava.Core/Java2/IrDeclaration.cs
namespace CSharpToJava.Core.Java2;

public abstract class IrDeclaration : IrNode
{
    public string Name { get; set; } = "";
    public string? LeadingComment { get; set; }
}

public class IrCompilationUnit : IrDeclaration
{
    public string? Package { get; set; }
    /// <summary>
    /// 文件级头注释（如 C# 文件开头的 copyright / 文件级 &lt;summary&gt;），
    /// 来自 CompilationUnitSyntax 的 leading trivia，输出在 package 之前。
    /// </summary>
    public string? FileHeaderComment { get; set; }
    public List<string> Imports { get; } = new();
    public List<IrTypeDeclaration> TypeDeclarations { get; } = new();
}

public abstract class IrTypeDeclaration : IrDeclaration
{
    public List<string> Annotations { get; } = new();
    public IrModifiers Modifiers { get; set; } = IrModifiers.None;
    public List<IrTypeParameter> TypeParameters { get; } = new();
    public List<IrFieldDeclaration> Fields { get; } = new();
    public List<IrMethodDeclaration> Methods { get; } = new();
    public List<IrTypeDeclaration> NestedTypes { get; } = new();
}

public class IrClassDeclaration : IrTypeDeclaration
{
    public string? ExtendedType { get; set; }
    public List<string> ImplementedTypes { get; } = new();
    public List<IrConstructorDeclaration> Constructors { get; } = new();
    public bool IsRecord { get; set; }
    public bool IsConvertedFromStruct { get; set; }
    public bool IsValueClass { get; set; }
    public List<IrRecordComponent> RecordComponents { get; } = new();
}

public class IrInterfaceDeclaration : IrTypeDeclaration
{
    public List<string> ExtendedTypes { get; } = new();
}

public class IrEnumDeclaration : IrTypeDeclaration
{
    public List<IrEnumValue> Values { get; } = new();
    public List<IrConstructorDeclaration> Constructors { get; } = new();
}

public class IrEnumValue
{
    public string Name { get; set; } = "";
    public List<IrExpression> Arguments { get; } = new();
}

public class IrRecordComponent
{
    public string Type { get; set; } = "";
    public string Name { get; set; } = "";
}

public class IrFieldDeclaration : IrNode
{
    public List<string> Annotations { get; } = new();
    public IrModifiers Modifiers { get; set; } = IrModifiers.None;
    public string Type { get; set; } = "";
    public string Name { get; set; } = "";
    public string? Initializer { get; set; }
    public string? LeadingComment { get; set; }
}

public class IrMethodDeclaration : IrNode
{
    public List<string> Annotations { get; } = new();
    public IrModifiers Modifiers { get; set; } = IrModifiers.None;
    public List<IrTypeParameter> TypeParameters { get; } = new();
    public string ReturnType { get; set; } = "void";
    public string Name { get; set; } = "";
    public List<IrParameter> Parameters { get; } = new();
    public List<string> ThrownExceptions { get; } = new();
    public bool IsAutoGenerated { get; set; }
    public IrBlockStatement? Body { get; set; }
    public string? LeadingComment { get; set; }
}

public class IrConstructorDeclaration : IrNode
{
    public List<string> Annotations { get; } = new();
    public IrModifiers Modifiers { get; set; } = IrModifiers.None;
    public string TypeName { get; set; } = "";
    public List<IrParameter> Parameters { get; } = new();
    public IrBlockStatement? Body { get; set; }
    public string? LeadingComment { get; set; }
    public IrConstructorInitializer? Initializer { get; set; }
}

public class IrConstructorInitializer
{
    public bool IsThisCall { get; set; }
    public List<IrExpression> Arguments { get; } = new();
}

public class IrParameter
{
    public string Type { get; set; } = "";
    public string Name { get; set; } = "";
    public bool IsFinal { get; set; }
    public bool IsRef { get; set; }
    public bool IsOut { get; set; }
    public bool IsReadOnlyRef { get; set; }
}

public class IrTypeParameter
{
    public string Name { get; set; } = "";
    public List<string> Bounds { get; } = new();
}

[Flags]
public enum IrModifiers
{
    None = 0,
    Public = 1 << 0,
    Protected = 1 << 1,
    Private = 1 << 2,
    Static = 1 << 3,
    Final = 1 << 4,
    Abstract = 1 << 5,
}
