using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using CSharpToJava.Core.Abstractions;
using CSharpToJava.Core.Context;
using CSharpToJava.Core.Java;
using System.Text.RegularExpressions;

namespace CSharpToJava.Core.Transformers.Member;

/// <summary>
/// 索引器转换器 - 将 C# 索引器转换为 Java 方法
/// </summary>
public class IndexerTransformer : IMemberTransformer
{
    public JavaSyntaxNode Transform(MemberDeclarationSyntax node, ConversionContext context)
    {
        if (node is not IndexerDeclarationSyntax indexerDecl)
        {
            throw new ArgumentException($"Expected IndexerDeclarationSyntax, got {node.GetType()}");
        }

        var results = new List<JavaMethodDeclaration>();

        var typeInfo = context.GetTypeInfo(indexerDecl.Type);
        var returnType = typeInfo.Type != null
            ? context.MapType(typeInfo.Type)
            : "Object";

        // Fix 1: use context-aware method name selection to avoid Map/List collisions.
        // The getter name is always "get" (same across List, Map, and default).
        // The setter name is "put" when the containing class implements Map (to match Map.put contract)
        // or when the containing type is dictionary-like (name contains Dictionary/SortedList/Map),
        // to stay consistent with AssignmentTransformer.IsDictionaryLikeContainer.
        bool implementsMap = context.ImplementsInterface("Map");
        bool isDictionaryLikeType = IsDictionaryLikeTypeName(context);
        string getterName = "get";
        string setterName = (implementsMap || isDictionaryLikeType) ? "put" : "set";

        // 获取参数列表
        var parameters = new List<JavaParameter>();
        foreach (var param in indexerDecl.ParameterList?.Parameters ?? Enumerable.Empty<ParameterSyntax>())
        {
            var paramTypeInfo = context.GetTypeInfo(param.Type!);
            var javaType = paramTypeInfo.Type != null
                ? context.MapType(paramTypeInfo.Type)
                : "Object";
            parameters.Add(new JavaParameter(javaType, param.Identifier.Text));
        }

        // Fix 2: detect multi-parameter indexers so we can post-process bracket syntax.
        bool isMultiParam = parameters.Count > 1;

        // 生成 getter 方法
        var getAccessor = indexerDecl.AccessorList?.Accessors
            .FirstOrDefault(a => a.IsKind(SyntaxKind.GetAccessorDeclaration));

        if (getAccessor != null || indexerDecl.AccessorList == null)
        {
            var getter = new JavaMethodDeclaration
            {
                Name = getterName,
                ReturnType = returnType,
                Modifiers = GetAccessorModifiers(getAccessor, indexerDecl.Modifiers) | JavaModifiers.Public,
                IsAutoGenerated = true
            };

            // 添加参数
            foreach (var param in parameters)
            {
                getter.Parameters.Add(param);
            }

            if (getAccessor?.Body != null)
            {
                var statementTransformer = new Transformers.Statement.StatementTransformer();
                var body = statementTransformer.TransformBlock(getAccessor.Body, context);
                // Fix 2: replace C# multi-dim bracket syntax [a, b] with [a][b] in the body.
                getter.Body = isMultiParam ? FixMultiDimBrackets(body) : body;
            }
            else if (getAccessor?.ExpressionBody != null)
            {
                var body = Transformers.Expression.ExpressionTransformerFacade.Instance.Transform(
                    getAccessor.ExpressionBody.Expression, context);
                // Fix 2: same bracket normalisation for expression bodies.
                getter.Body = isMultiParam ? FixMultiDimBrackets(body) : body;
                getter.IsBodyExpression = true;
            }

            results.Add(getter);
        }

        // Fix 4: treat init accessor similarly to set accessor, but annotate the method.
        var setAccessor = indexerDecl.AccessorList?.Accessors
            .FirstOrDefault(a => a.IsKind(SyntaxKind.SetAccessorDeclaration));
        var initAccessor = indexerDecl.AccessorList?.Accessors
            .FirstOrDefault(a => a.IsKind(SyntaxKind.InitAccessorDeclaration));

        // setterAccessor is whichever accessor should produce the Java setter method.
        var setterAccessor = setAccessor ?? initAccessor;

        // Fix 5: in interface context, only emit a setter when there is an explicit 'set' accessor.
        //        A get-only interface indexer (or one with only 'init') must not generate a setter stub.
        if (context.IsInInterfaceBody && setAccessor == null)
        {
            setterAccessor = null;
        }

        if (setterAccessor != null)
        {
            var setter = new JavaMethodDeclaration
            {
                Name = setterName,
                // Return the set value so that compound indexer assignment (e.g. Edges[i] = value)
                // can be chained in Java as: edge = Edges.set(i, value).
                // Fix 3: for Map.put the contract also returns the previous value; we emit
                //        "return null;" as a placeholder since the previous value is not tracked.
                ReturnType = returnType,
                Modifiers = GetAccessorModifiers(setterAccessor, indexerDecl.Modifiers) | JavaModifiers.Public,
                IsAutoGenerated = true
            };

            // Fix 4: annotate init-only accessors so callers know the intended restriction.
            if (initAccessor != null && setAccessor == null)
            {
                setter.LeadingComment = "// C# init-only: should only be called during construction";
            }

            // 添加参数
            foreach (var param in parameters)
            {
                setter.Parameters.Add(param);
            }
            setter.Parameters.Add(new JavaParameter(returnType, "value"));

            // Fix 3: Map.put should return null (previous-value placeholder) rather than the new value.
            string returnStatement = (setterName == "put") ? "\nreturn null;" : "\nreturn value;";

            if (setterAccessor.Body != null)
            {
                var statementTransformer = new Transformers.Statement.StatementTransformer();
                var body = statementTransformer.TransformBlock(setterAccessor.Body, context);
                // Fix 2: normalise multi-dim bracket syntax in setter body as well.
                body = isMultiParam ? FixMultiDimBrackets(body) : body;
                setter.Body = EndsWithTerminalStatement(body) ? body : body + returnStatement;
            }
            else if (setterAccessor.ExpressionBody != null)
            {
                var body = Transformers.Expression.ExpressionTransformerFacade.Instance.Transform(
                    setterAccessor.ExpressionBody.Expression, context);
                body = isMultiParam ? FixMultiDimBrackets(body) : body;
                setter.IsBodyExpression = false; // need a block with return
                setter.Body = EndsWithTerminalStatement(body) ? body + ";" : body + ";" + returnStatement;
            }

            results.Add(setter);
        }

        return new Java.JavaMemberCollection(results.Cast<Java.JavaSyntaxNode>().ToList());
    }

    /// <summary>
    /// Checks if the current containing type is dictionary-like based on its name,
    /// mirroring the logic in AssignmentTransformer.IsDictionaryLikeContainer.
    /// </summary>
    private static bool IsDictionaryLikeTypeName(ConversionContext context)
    {
        var roslynType = context.CurrentEnclosingRoslynType;
        if (roslynType != null)
        {
            if (roslynType.Name.Contains("Dictionary", StringComparison.Ordinal)
                || roslynType.Name.Contains("SortedList", StringComparison.Ordinal)
                || roslynType.Name.Contains("Map", StringComparison.Ordinal))
                return true;
        }
        // Fallback: check the Java type name
        var javaType = context.CurrentType;
        if (javaType != null)
        {
            if (javaType.Name.Contains("Dictionary", StringComparison.Ordinal)
                || javaType.Name.Contains("SortedList", StringComparison.Ordinal)
                || javaType.Name.Contains("Map", StringComparison.Ordinal))
                return true;
        }
        return false;
    }

    /// <summary>
    /// Fix 2: Replace C# multi-dimensional bracket syntax <c>expr[a, b]</c> with
    /// chained Java bracket syntax <c>expr[a][b]</c>.
    /// Only applied when the indexer has more than one parameter.
    /// </summary>
    private static string FixMultiDimBrackets(string body)
    {
        // Match two-argument bracket expressions: [expr1, expr2]
        // Avoid matching array/collection literals with more commas.
        return Regex.Replace(body, @"\[([^\[\],]+),\s*([^\[\],]+)\]", "[$1][$2]");
    }

    /// <summary>
    /// Checks if the body already ends with a terminal statement (throw/return),
    /// in which case appending a synthetic return would create unreachable code.
    /// </summary>
    private static bool EndsWithTerminalStatement(string body)
    {
        var lastLine = body.Split('\n').LastOrDefault()?.Trim();
        return lastLine != null && (lastLine.StartsWith("throw ") || lastLine.StartsWith("return "));
    }

    private JavaModifiers GetAccessorModifiers(AccessorDeclarationSyntax? accessor, SyntaxTokenList modifiers)
    {
        JavaModifiers result = JavaModifiers.None;

        // 检查访问器上的修饰符
        if (accessor != null)
        {
            foreach (var modifier in accessor.Modifiers)
            {
                result |= modifier.Kind() switch
                {
                    SyntaxKind.PublicKeyword => JavaModifiers.Public,
                    SyntaxKind.ProtectedKeyword => JavaModifiers.Protected,
                    SyntaxKind.PrivateKeyword => JavaModifiers.Private,
                    SyntaxKind.InternalKeyword => JavaModifiers.Public,
                    _ => JavaModifiers.None
                };
            }
        }

        // 如果访问器没有修饰符，使用索引器的修饰符
        if (result == JavaModifiers.None)
        {
            foreach (var modifier in modifiers)
            {
                result |= modifier.Kind() switch
                {
                    SyntaxKind.PublicKeyword => JavaModifiers.Public,
                    SyntaxKind.ProtectedKeyword => JavaModifiers.Protected,
                    SyntaxKind.PrivateKeyword => JavaModifiers.Private,
                    SyntaxKind.InternalKeyword => JavaModifiers.Public,
                    _ => JavaModifiers.None
                };
            }
        }

        return result;
    }
}
