using System.Text;

namespace CSharpToJava.Core.Java;

internal static class JavaMemberFormatting
{
    public static void AppendAccessModifier(StringBuilder sb, JavaModifiers modifiers)
    {
        if ((modifiers & JavaModifiers.Public) != 0) sb.Append("public ");
        else if ((modifiers & JavaModifiers.Protected) != 0) sb.Append("protected ");
        else if ((modifiers & JavaModifiers.Private) != 0) sb.Append("private ");
    }
}

/// <summary>
/// Java 字段声明
/// </summary>
public class JavaFieldDeclaration : JavaSyntaxNode
{
    public List<JavaAnnotation> Annotations { get; } = new();
    public JavaModifiers Modifiers { get; set; } = JavaModifiers.None;
    public string Type { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string? Initializer { get; set; }
    /// <summary>
    /// Optional comment emitted on the line immediately before this field declaration.
    /// </summary>
    public string? LeadingComment { get; set; }

    public override string ToString(string indentation)
    {
        var sb = new StringBuilder();

        JavaCommentEmitter.AppendLeadingComment(sb, indentation, LeadingComment);

        foreach (var annotation in Annotations)
        {
            sb.Append(annotation.ToString()).Append(' ');
        }

        // 修饰符
        JavaMemberFormatting.AppendAccessModifier(sb, Modifiers);
        if ((Modifiers & JavaModifiers.Static) != 0) sb.Append("static ");
        if ((Modifiers & JavaModifiers.Final) != 0) sb.Append("final ");
        if ((Modifiers & JavaModifiers.Volatile) != 0) sb.Append("volatile ");
        if ((Modifiers & JavaModifiers.Transient) != 0) sb.Append("transient ");

        sb.Append(Type).Append(' ').Append(Name);

        if (!string.IsNullOrEmpty(Initializer))
        {
            sb.Append(" = ").Append(Initializer);
        }

        sb.Append(';');

        return sb.ToString();
    }
}

/// <summary>
/// Java 方法声明
/// </summary>
public class JavaMethodDeclaration : JavaSyntaxNode
{
    public List<JavaAnnotation> Annotations { get; } = new();
    public JavaModifiers Modifiers { get; set; } = JavaModifiers.None;
    public List<JavaTypeParameter> TypeParameters { get; } = new();
    public string ReturnType { get; set; } = "void";
    public string Name { get; set; } = string.Empty;
    public List<JavaParameter> Parameters { get; } = new();
    public List<string> ThrownExceptions { get; } = new();
    public string? Body { get; set; }
    public bool IsBodyExpression { get; set; }
    /// <summary>
    /// 标记此方法是否由属性自动生成（如 getter/setter），而非用户定义的方法。
    /// 用于解决自动生成的访问器与用户方法之间的命名冲突。
    /// </summary>
    public bool IsAutoGenerated { get; set; }
    /// <summary>
    /// 结构化方法体（优先于 Body 字符串）。设置后 ToString 将使用结构化渲染。
    /// </summary>
    public JavaMethodBody? StructuredBody { get; set; }
    /// <summary>
    /// Optional comment emitted verbatim on the line immediately before this method declaration.
    /// </summary>
    public string? LeadingComment { get; set; }

    public override string ToString(string indentation)
    {
        var sb = new StringBuilder();

        JavaCommentEmitter.AppendLeadingComment(sb, indentation, LeadingComment);

        foreach (var annotation in Annotations)
        {
            sb.AppendLine($"{indentation}{annotation.ToString()}");
        }

        // 修饰符
        JavaMemberFormatting.AppendAccessModifier(sb, Modifiers);
        if ((Modifiers & JavaModifiers.Static) != 0) sb.Append("static ");
        if ((Modifiers & JavaModifiers.Final) != 0) sb.Append("final ");
        if ((Modifiers & JavaModifiers.Abstract) != 0) sb.Append("abstract ");
        if ((Modifiers & JavaModifiers.Synchronized) != 0) sb.Append("synchronized ");
        if ((Modifiers & JavaModifiers.Default) != 0) sb.Append("default ");

        // 泛型参数
        if (TypeParameters.Count > 0)
        {
            sb.Append('<');
            sb.Append(string.Join(", ", TypeParameters.Select(tp => tp.ToString())));
            sb.Append('>');
            sb.Append(' ');
        }

        sb.Append(ReturnType).Append(' ').Append(Name).Append('(');

        // 参数
        sb.Append(string.Join(", ", Parameters.Select(p => p.ToString())));

        sb.Append(')');

        // 异常
        if (ThrownExceptions.Count > 0)
        {
            sb.Append(" throws ").Append(string.Join(", ", ThrownExceptions));
        }

        // 方法体
        if (Modifiers.HasFlag(JavaModifiers.Abstract) || (Body == null && StructuredBody == null))
        {
            sb.Append(';');
        }
        else if (StructuredBody != null)
        {
            // 结构化方法体优先
            sb.AppendLine(" {");
            var bodyStr = StructuredBody.ToString(indentation + "    ");
            if (!string.IsNullOrEmpty(bodyStr))
            {
                sb.AppendLine(bodyStr);
            }
            sb.Append(indentation).Append('}');
        }
        else if (IsBodyExpression)
        {
            sb.Append(" { ");
            if (ReturnType != "void") sb.Append("return ");
            sb.Append(Body).Append("; }");
        }
        else
        {
            sb.AppendLine(" {");
            if (!string.IsNullOrEmpty(Body))
            {
                var lines = Body.Split('\n');
                foreach (var line in lines)
                {
                    if (!string.IsNullOrWhiteSpace(line))
                    {
                        sb.AppendLine($"{indentation}    {line.Trim()}");
                    }
                }
            }
            sb.Append(indentation).Append('}');
        }

        return sb.ToString();
    }
}

/// <summary>
/// Java 构造函数声明
/// </summary>
public class JavaConstructorDeclaration : JavaSyntaxNode
{
    public List<JavaAnnotation> Annotations { get; } = new();
    public JavaModifiers Modifiers { get; set; } = JavaModifiers.None;
    public string ClassName { get; set; } = string.Empty;
    public List<JavaParameter> Parameters { get; } = new();
    public List<string> ThrownExceptions { get; } = new();
    public string? Body { get; set; }
    public string? LeadingComment { get; set; }
    /// <summary>
    /// 结构化方法体（优先于 Body 字符串）。设置后 ToString 将使用结构化渲染。
    /// </summary>
    public JavaMethodBody? StructuredBody { get; set; }
    /// <summary>
    /// Optional super/this constructor call emitted as the first statement in the body.
    /// e.g. "super(a, b)" or "this(x)".
    /// </summary>
    public string? Initializer { get; set; }

    public override string ToString(string indentation)
    {
        var sb = new StringBuilder();

        JavaCommentEmitter.AppendLeadingComment(sb, indentation, LeadingComment);

        foreach (var annotation in Annotations)
        {
            sb.AppendLine($"{indentation}{annotation.ToString()}");
        }

        // 修饰符
        JavaMemberFormatting.AppendAccessModifier(sb, Modifiers);

        sb.Append(ClassName).Append('(');

        // 参数
        sb.Append(string.Join(", ", Parameters.Select(p => p.ToString())));

        sb.Append(')');

        // 异常
        if (ThrownExceptions.Count > 0)
        {
            sb.Append(" throws ").Append(string.Join(", ", ThrownExceptions));
        }

        // 方法体
        if (StructuredBody != null)
        {
            // 结构化方法体优先
            sb.AppendLine(" {");
            if (!string.IsNullOrEmpty(Initializer))
            {
                sb.AppendLine($"{indentation}    {Initializer};");
            }
            var bodyStr = StructuredBody.ToString(indentation + "    ");
            if (!string.IsNullOrEmpty(bodyStr))
            {
                sb.AppendLine(bodyStr);
            }
            sb.Append(indentation).Append('}');
        }
        else if (Body == null && Initializer == null)
        {
            sb.Append(';');
        }
        else
        {
            sb.AppendLine(" {");
            if (!string.IsNullOrEmpty(Initializer))
            {
                sb.AppendLine($"{indentation}    {Initializer};");
            }
            if (!string.IsNullOrEmpty(Body))
            {
                var lines = Body.Split('\n');
                foreach (var line in lines)
                {
                    if (!string.IsNullOrWhiteSpace(line))
                    {
                        sb.AppendLine($"{indentation}    {line.Trim()}");
                    }
                }
            }
            sb.Append(indentation).Append('}');
        }

        return sb.ToString();
    }

}

/// <summary>
/// Java 参数
/// </summary>
public class JavaParameter
{
    public List<JavaAnnotation> Annotations { get; } = new();
    public JavaModifiers Modifiers { get; set; } = JavaModifiers.None;
    public string Type { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public bool IsVarArgs { get; set; }

    public JavaParameter(string type, string name)
    {
        Type = type;
        Name = name;
    }

    public override string ToString()
    {
        var sb = new StringBuilder();

        foreach (var annotation in Annotations)
        {
            sb.Append(annotation.ToString()).Append(' ');
        }

        if ((Modifiers & JavaModifiers.Final) != 0) sb.Append("final ");

        sb.Append(Type);

        if (IsVarArgs)
        {
            // For C# "params T[] items" → Java "T... items". Strip trailing [] from array type.
            if (sb.ToString().EndsWith("[]"))
            {
                sb.Remove(sb.Length - 2, 2);
            }
            sb.Append("...");
        }

        sb.Append(' ').Append(Name);

        return sb.ToString();
    }
}

/// <summary>
/// Java static initializer block: static { ... }
/// </summary>
public class JavaStaticInitializerBlock : JavaSyntaxNode
{
    public List<string> Statements { get; } = new();

    public override string ToString(string indentation)
    {
        var sb = new StringBuilder();
        sb.AppendLine("static {");
        foreach (var stmt in Statements)
        {
            if (!string.IsNullOrWhiteSpace(stmt))
            {
                sb.AppendLine($"{indentation}    {stmt.Trim()}");
            }
        }
        sb.Append(indentation).Append('}');
        return sb.ToString();
    }
}

/// <summary>
/// Java 修饰符标志
/// </summary>
[Flags]
public enum JavaModifiers
{
    None = 0,
    Public = 1 << 0,
    Protected = 1 << 1,
    Private = 1 << 2,
    Static = 1 << 3,
    Final = 1 << 4,
    Abstract = 1 << 5,
    Sealed = 1 << 6,
    Override = 1 << 7,
    Synchronized = 1 << 8,
    Volatile = 1 << 9,
    Transient = 1 << 10,
    Default = 1 << 11,  // 接口默认方法
    Native = 1 << 12,
}
